// AUTO-GENERATED by cloudflare-worker/scripts/gen-question-ids.mjs.
// Do NOT edit by hand — re-run `node cloudflare-worker/scripts/gen-question-ids.mjs`
// (or `npm run test:drift`) after changing any bank file.
//
// Task #5 (CH) — string-literal union of every advisor question id
// across all persona banks + the role detector. Used by writeRouter
// coverage tests + any consumer that needs an exhaustive switch.

export type AdvisorQuestionId =
  | 'admin.governance.access_review_cadence'
  | 'admin.governance.data_retention_pref'
  | 'admin.operations.intake_priority'
  | 'admin.operations.onboarding_sla'
  | 'admin.oversight.escalation_threshold'
  | 'admin.oversight.portfolio_focus'
  | 'admin.oversight.review_cadence'
  | 'admin.oversight.risk_tolerance'
  | 'admin.preferences.alert_channel'
  | 'admin.preferences.digest_freq'
  | 'admin.preferences.timezone'
  | 'advisor.calendar.notice_required_hours'
  | 'advisor.calendar.office_hours_window'
  | 'advisor.calendar.timezones_covered'
  | 'advisor.calendar.weekly_hours'
  | 'advisor.comp.equity_open'
  | 'advisor.comp.minimum_engagement_hours'
  | 'advisor.engagement.active_founders'
  | 'advisor.engagement.biggest_friction'
  | 'advisor.engagement.intros_made_qtr'
  | 'advisor.engagement.referral_likely'
  | 'advisor.engagement.satisfaction'
  | 'advisor.expertise.adoption_curve'
  | 'advisor.expertise.depth_or_breadth'
  | 'advisor.expertise.geographies'
  | 'advisor.expertise.stages'
  | 'advisor.profile.bio'
  | 'advisor.profile.display_name'
  | 'advisor.profile.exits_or_outcomes'
  | 'advisor.profile.expertise'
  | 'advisor.profile.hourly_rate_usd'
  | 'advisor.profile.linkedin_url'
  | 'advisor.profile.public_writing'
  | 'advisor.profile.sectors'
  | 'advisor.profile.years_operating'
  | 'advisor.topics.async_vs_sync'
  | 'advisor.topics.preferred_session_length_min'
  | 'advisor.topics.recent_wins'
  | 'advisor.topics.signature_session'
  | 'advisor.topics.unwilling'
  | 'advisor.topics.willing'
  | 'founder.advisors.current_advisors'
  | 'founder.advisors.gap_areas'
  | 'founder.advisors.intro_priority'
  | 'founder.advisors.most_valuable'
  | 'founder.advisors.needs'
  | 'founder.brand.tagline'
  | 'founder.brand.theme_color'
  | 'founder.capital.bridge_likely'
  | 'founder.capital.dilution_floor_pct'
  | 'founder.capital.investors_on_captable'
  | 'founder.capital.lead_status'
  | 'founder.capital.option_pool_pct'
  | 'founder.capital.preferred_lead_funds'
  | 'founder.capital.previous_round_post_usd'
  | 'founder.capital.previous_round_usd'
  | 'founder.capital.raise_active'
  | 'founder.capital.raise_target_usd'
  | 'founder.capital.runway_after_raise_months'
  | 'founder.capital.target_close_date'
  | 'founder.capital.use_of_funds'
  | 'founder.capital.valuation_target_usd'
  | 'founder.capital.warm_intro_count'
  | 'founder.captable.entity'
  | 'founder.captable.ownership'
  | 'founder.compliance.status'
  | 'founder.dd.ai_data_moat'
  | 'founder.dd.ai_inference_cost_per_1k'
  | 'founder.dd.ai_model_strategy'
  | 'founder.dd.b2b_saas_logos_paid'
  | 'founder.dd.b2b_saas_seat_expansion'
  | 'founder.dd.climate_carbon_metric'
  | 'founder.dd.consumer_cac_payback_months'
  | 'founder.dd.consumer_d30_retention_pct'
  | 'founder.dd.deeptech_tech_readiness'
  | 'founder.dd.fintech_chargeback_pct'
  | 'founder.dd.fintech_kyc'
  | 'founder.dd.fintech_licensing'
  | 'founder.dd.healthcare_hipaa_status'
  | 'founder.dd.preseed_lois'
  | 'founder.dd.seriesa_cohort_retention'
  | 'founder.dd.seriesb_growth_rate'
  | 'founder.deck.market'
  | 'founder.deck.problem'
  | 'founder.discovery.interview1.name'
  | 'founder.discovery.interview1.pains'
  | 'founder.discovery.interview2.name'
  | 'founder.discovery.interview2.pains'
  | 'founder.discovery.interview3.name'
  | 'founder.discovery.interview3.pains'
  | 'founder.financials.arr_usd'
  | 'founder.financials.bookings_qtr_usd'
  | 'founder.financials.budget_vs_actual'
  | 'founder.financials.cac_usd'
  | 'founder.financials.financial_model_link'
  | 'founder.financials.gross_margin_pct'
  | 'founder.financials.gross_revenue_retention_pct'
  | 'founder.financials.ltv_usd'
  | 'founder.financials.magic_number'
  | 'founder.financials.monthly_burn_usd'
  | 'founder.financials.mrr_usd'
  | 'founder.financials.net_revenue_retention_pct'
  | 'founder.financials.payback_months'
  | 'founder.financials.runway_months'
  | 'founder.fit.activation_definition'
  | 'founder.fit.activation_rate_pct'
  | 'founder.fit.adoption_curve'
  | 'founder.fit.churn_top_reason'
  | 'founder.fit.discovery_volume_qtr'
  | 'founder.fit.expansion_signal'
  | 'founder.fit.icp_segments'
  | 'founder.fit.icp_statement'
  | 'founder.fit.icp_v_buyer'
  | 'founder.fit.ipspf_signal'
  | 'founder.fit.nps_or_csat'
  | 'founder.fit.retention_30d_pct'
  | 'founder.gtm.avg_acv_usd'
  | 'founder.gtm.brand_awareness'
  | 'founder.gtm.channel_cac_split'
  | 'founder.gtm.community_motion'
  | 'founder.gtm.customer_advisory_board'
  | 'founder.gtm.first_call_to_close_pct'
  | 'founder.gtm.inbound_lead_volume_wk'
  | 'founder.gtm.outbound_volume_wk'
  | 'founder.gtm.pricing_changes_planned'
  | 'founder.gtm.pricing_model'
  | 'founder.gtm.primary_channel'
  | 'founder.lab.advisors.cadence'
  | 'founder.lab.advisors.intro_target'
  | 'founder.lab.advisors.priority1'
  | 'founder.lab.advisors.style'
  | 'founder.lab.advisors.warm_path'
  | 'founder.lab.capital.first_raise_target'
  | 'founder.lab.capital.instrument'
  | 'founder.lab.capital.lead_investor'
  | 'founder.lab.capital.runway_target_months'
  | 'founder.lab.capital.target_investors'
  | 'founder.lab.capital.warm_intros'
  | 'founder.lab.deck.ask'
  | 'founder.lab.deck.business_model'
  | 'founder.lab.deck.competition_map'
  | 'founder.lab.deck.demo_link'
  | 'founder.lab.deck.go_to_market'
  | 'founder.lab.deck.moat'
  | 'founder.lab.deck.solution'
  | 'founder.lab.deck.team_slide'
  | 'founder.lab.deck.why_now'
  | 'founder.lab.discovery.alternatives'
  | 'founder.lab.discovery.deal_breaker'
  | 'founder.lab.discovery.followup_scheduled'
  | 'founder.lab.discovery.icp_buyer_vs_user'
  | 'founder.lab.discovery.icp_v1'
  | 'founder.lab.discovery.pivot_signal'
  | 'founder.lab.discovery.signal_score'
  | 'founder.lab.discovery.willingness_to_pay'
  | 'founder.lab.legal.83b_planned'
  | 'founder.lab.legal.advisor_seats'
  | 'founder.lab.legal.ip_assignment'
  | 'founder.lab.legal.prior_employer_ip'
  | 'founder.lab.legal.state'
  | 'founder.lab.metrics.first_north_star'
  | 'founder.lab.metrics.signal_v_noise'
  | 'founder.lab.metrics.tracking_tool'
  | 'founder.lab.metrics.weekly_target'
  | 'founder.lab.ops.accounting_provider'
  | 'founder.lab.ops.bank_setup'
  | 'founder.lab.ops.budget_template'
  | 'founder.lab.ops.communication_norm'
  | 'founder.lab.ops.first_hire_comp'
  | 'founder.lab.ops.first_hire_role'
  | 'founder.lab.ops.first_hire_when'
  | 'founder.lab.ops.governance_doc'
  | 'founder.lab.ops.payroll_provider'
  | 'founder.lab.ops.weekly_review'
  | 'founder.lab.roadmap.kr_for_obj1'
  | 'founder.lab.roadmap.kr_for_obj2'
  | 'founder.lab.roadmap.kr_for_obj3'
  | 'founder.lab.roadmap.weekly_cadence'
  | 'founder.lab.team.cofounder_gap'
  | 'founder.lab.team.dealbreakers'
  | 'founder.lab.team.equity_philosophy'
  | 'founder.lab.team.first_5_hires'
  | 'founder.lab.team.remote_or_office'
  | 'founder.lab.wellbeing.biggest_blocker'
  | 'founder.lab.wellbeing.cofounder_pulse'
  | 'founder.lab.wellbeing.energy'
  | 'founder.lab.wellbeing.exercise_freq'
  | 'founder.lab.wellbeing.scary_question'
  | 'founder.lab.wellbeing.sleep_hours'
  | 'founder.lab.wellbeing.support'
  | 'founder.legal.dpa_template'
  | 'founder.legal.export_controls'
  | 'founder.legal.foreign_subsidiaries'
  | 'founder.legal.ip_assignment_status'
  | 'founder.legal.litigation_active'
  | 'founder.legal.patents_filed'
  | 'founder.legal.privacy_policy'
  | 'founder.legal.security_certs'
  | 'founder.legal.terms_of_service_current'
  | 'founder.legal.trademarks_filed'
  | 'founder.okrs.q1_objective1'
  | 'founder.okrs.q1_objective2'
  | 'founder.okrs.q1_objective3'
  | 'founder.ops.allhands_cadence'
  | 'founder.ops.board_cadence'
  | 'founder.ops.bug_triage_sla_hrs'
  | 'founder.ops.knowledge_base'
  | 'founder.ops.okrs_cadence'
  | 'founder.ops.oncall_rotation'
  | 'founder.ops.standup_format'
  | 'founder.ops.tooling_stack'
  | 'founder.ops.weekly_metric_cadence'
  | 'founder.partners.active_count'
  | 'founder.partners.biggest_friction'
  | 'founder.partners.health_score'
  | 'founder.pipeline.avg_sales_cycle_days'
  | 'founder.pipeline.size_usd'
  | 'founder.pipeline.top_deals'
  | 'founder.pipeline.win_rate_pct'
  | 'founder.product.dev_velocity'
  | 'founder.product.next_big_bet'
  | 'founder.product.platform_choice'
  | 'founder.product.qa_coverage'
  | 'founder.product.tech_debt_score'
  | 'founder.product.what_breaks'
  | 'founder.product.what_works'
  | 'founder.project.cac_usd'
  | 'founder.project.contact_email'
  | 'founder.project.gross_margin_pct'
  | 'founder.project.logo_url'
  | 'founder.project.name'
  | 'founder.project.pitch'
  | 'founder.project.sector'
  | 'founder.project.som_usd'
  | 'founder.project.stage'
  | 'founder.project.tagline'
  | 'founder.project.traction'
  | 'founder.project.traction_summary'
  | 'founder.project.vision'
  | 'founder.team.attrition_12m'
  | 'founder.team.cofounders'
  | 'founder.team.compensation_philosophy'
  | 'founder.team.culture_doc_link'
  | 'founder.team.diversity_snapshot'
  | 'founder.team.equity_refresh_policy'
  | 'founder.team.exec_team_complete'
  | 'founder.team.first_eng_hired'
  | 'founder.team.headcount_by_function'
  | 'founder.team.headcount_total'
  | 'founder.team.hires_planned_qtr'
  | 'founder.team.remote_policy'
  | 'founder.wellbeing.biggest_stressor'
  | 'founder.wellbeing.energy_score'
  | 'founder.wellbeing.sleep_hours'
  | 'founder.wellbeing.support_system'
  | 'founder.wellbeing.therapist_or_coach'
  | 'founder.wellbeing.vacation_planned'
  | 'investor.coinvest.minimum_lead_check_usd'
  | 'investor.coinvest.preferences'
  | 'investor.coinvest.preferred_partners'
  | 'investor.dd.background_checks'
  | 'investor.dd.checklist_link'
  | 'investor.dd.competitive_diligence_method'
  | 'investor.dd.customer_calls_required'
  | 'investor.dd.financial_diligence_depth'
  | 'investor.dd.legal_review_outsourced'
  | 'investor.dd.red_flags_recent'
  | 'investor.dd.references_required'
  | 'investor.dd.tech_diligence_partner'
  | 'investor.dd.valuation_framework'
  | 'investor.lp.communication_pain'
  | 'investor.lp.dpi_to_date_x'
  | 'investor.lp.next_fund_planning'
  | 'investor.lp.report_cadence'
  | 'investor.lp.report_format'
  | 'investor.lp.tvpi_to_date_x'
  | 'investor.pipeline.avg_dd_days'
  | 'investor.pipeline.deal_volume'
  | 'investor.pipeline.deals_per_partner'
  | 'investor.pipeline.first_meetings_qtr'
  | 'investor.pipeline.investments_closed_qtr'
  | 'investor.pipeline.scout_program'
  | 'investor.pipeline.source_split'
  | 'investor.pipeline.term_sheets_qtr'
  | 'investor.portfolio.board_seats'
  | 'investor.portfolio.exits_to_date'
  | 'investor.portfolio.followon_reserves_pct'
  | 'investor.portfolio.intros_made_qtr'
  | 'investor.portfolio.observer_seats'
  | 'investor.portfolio.review_cadence'
  | 'investor.portfolio.support_offered'
  | 'investor.portfolio.total_companies'
  | 'investor.profile.fund_size_usd'
  | 'investor.profile.fund_vintage'
  | 'investor.profile.geo_focus'
  | 'investor.profile.investor_type'
  | 'investor.profile.lp_base'
  | 'investor.profile.sectors'
  | 'investor.profile.stages'
  | 'investor.profile.thesis'
  | 'investor.profile.ticket_band'
  | 'investor.sector.ai_inference_econ'
  | 'investor.sector.climate_metric_required'
  | 'investor.sector.consumer_payback_floor'
  | 'investor.sector.deeptech_capital_intensity'
  | 'investor.sector.fintech_regulatory'
  | 'investor.sector.healthcare_reimbursement'
  | 'investor.thesis.adoption_curve_focus'
  | 'investor.thesis.contrarian_view'
  | 'investor.thesis.deal_breakers'
  | 'investor.thesis.founder_archetype'
  | 'investor.thesis.macro_trends'
  | 'investor.thesis.market_size_floor_usd'
  | 'investor.thesis.must_haves'
  | 'investor.thesis.passes_recent'
  | 'investor.watchlist.alert_cadence'
  | 'investor.watchlist.seed_companies'
  | 'investor.watchlist.shadow_companies'
  | 'investor.watchlist.signals_of_interest'
  | 'partner.comp.model'
  | 'partner.conflicts.list'
  | 'partner.cv.average_dd_days'
  | 'partner.cv.balance_sheet_or_separate'
  | 'partner.cv.biggest_friction'
  | 'partner.cv.coinvest_partners'
  | 'partner.cv.commercial_bundle_offered'
  | 'partner.cv.conflicts_competitors'
  | 'partner.cv.conflicts_existing_portcos'
  | 'partner.cv.cvc_team_size'
  | 'partner.cv.cvc_unit_age_years'
  | 'partner.cv.dd.board_seats_required'
  | 'partner.cv.dd.brand_use_restrictions'
  | 'partner.cv.dd.bridge_support'
  | 'partner.cv.dd.commercial_signoff_required'
  | 'partner.cv.dd.commercial_team_intros'
  | 'partner.cv.dd.commercial_velocity_days'
  | 'partner.cv.dd.followon_signal_window'
  | 'partner.cv.dd.lp_communication_role'
  | 'partner.cv.dd.preferred_exit_path'
  | 'partner.cv.dd.pro_rata_intent'
  | 'partner.cv.dd.product_roadmap_input'
  | 'partner.cv.dd.public_pr_consent'
  | 'partner.cv.dd.right_of_first_refusal'
  | 'partner.cv.deals_closed_qtr'
  | 'partner.cv.deals_screened_qtr'
  | 'partner.cv.dilution_neutral_clauses'
  | 'partner.cv.executive_sponsor'
  | 'partner.cv.followon_reserve_pct'
  | 'partner.cv.fund_size_usd'
  | 'partner.cv.geos_active'
  | 'partner.cv.investments_per_yr'
  | 'partner.cv.lead_or_follow'
  | 'partner.cv.lps_or_internal_committee'
  | 'partner.cv.next_year_priorities'
  | 'partner.cv.parent_company'
  | 'partner.cv.preferred_comms'
  | 'partner.cv.quarter_focus'
  | 'partner.cv.referral_nps'
  | 'partner.cv.regulatory_constraints'
  | 'partner.cv.review_cadence'
  | 'partner.cv.satisfaction_score'
  | 'partner.cv.strategic_vs_financial'
  | 'partner.cv.success_metric'
  | 'partner.cv.suggestion_for_studio'
  | 'partner.cv.support_offered'
  | 'partner.cv.target_sectors'
  | 'partner.cv.target_stages'
  | 'partner.cv.thesis_one_line'
  | 'partner.cv.ticket_band_usd'
  | 'partner.cv.warm_intro_required'
  | 'partner.cv.weekly_digest_optin'
  | 'partner.dealflow.channels'
  | 'partner.deals.interest'
  | 'partner.firm.name'
  | 'partner.ma.adoption_curve'
  | 'partner.ma.async_or_sync'
  | 'partner.ma.biggest_friction'
  | 'partner.ma.calendar_link'
  | 'partner.ma.case_studies_open'
  | 'partner.ma.cash_rate_usd_hr'
  | 'partner.ma.coaching_credentials'
  | 'partner.ma.community_participation'
  | 'partner.ma.confidentiality_practice'
  | 'partner.ma.conflicts_companies'
  | 'partner.ma.conflicts_funds'
  | 'partner.ma.current_advisor_seats'
  | 'partner.ma.current_eir_engagements'
  | 'partner.ma.dd.board_observer_open'
  | 'partner.ma.dd.crisis_support'
  | 'partner.ma.dd.exec_search_partners'
  | 'partner.ma.dd.feedback_style'
  | 'partner.ma.dd.fundraising_help'
  | 'partner.ma.dd.go_to_market'
  | 'partner.ma.dd.hiring_help'
  | 'partner.ma.dd.intl_geo_expertise'
  | 'partner.ma.dd.podcast_or_writing_consent'
  | 'partner.ma.dd.preferred_meeting_format'
  | 'partner.ma.dd.product_strategy'
  | 'partner.ma.dd.public_speaking_open'
  | 'partner.ma.dd.regulatory_navigation'
  | 'partner.ma.dd.workshops_offered'
  | 'partner.ma.equity_floor_pct'
  | 'partner.ma.founder_archetype'
  | 'partner.ma.functional_expertise'
  | 'partner.ma.geos_active'
  | 'partner.ma.intake_process'
  | 'partner.ma.intros_offered_qtr'
  | 'partner.ma.minimum_engagement_months'
  | 'partner.ma.notable_outcomes'
  | 'partner.ma.preferred_comms'
  | 'partner.ma.pricing_model'
  | 'partner.ma.quarter_focus'
  | 'partner.ma.referral_nps'
  | 'partner.ma.role_type'
  | 'partner.ma.satisfaction_score'
  | 'partner.ma.session_length_min'
  | 'partner.ma.signature_topic'
  | 'partner.ma.success_metric'
  | 'partner.ma.suggestion_for_studio'
  | 'partner.ma.target_sectors'
  | 'partner.ma.target_stages'
  | 'partner.ma.weekly_digest_optin'
  | 'partner.ma.weekly_hours_open'
  | 'partner.ma.years_operating'
  | 'partner.profile.focus'
  | 'partner.rate.hourly'
  | 'partner.rate.project'
  | 'partner.role.kind'
  | 'partner.services.offered'
  | 'partner.sp.availability_office_hours'
  | 'partner.sp.biggest_friction'
  | 'partner.sp.case_study_consent'
  | 'partner.sp.case_study_link'
  | 'partner.sp.cold_inbound_open'
  | 'partner.sp.confidentiality_walls'
  | 'partner.sp.conflicts_companies'
  | 'partner.sp.conflicts_sectors'
  | 'partner.sp.current_capacity_pct'
  | 'partner.sp.dd.ai_specialty'
  | 'partner.sp.dd.data_handling'
  | 'partner.sp.dd.engagement_kpi'
  | 'partner.sp.dd.fintech_specialty'
  | 'partner.sp.dd.healthcare_specialty'
  | 'partner.sp.dd.intl_expansion'
  | 'partner.sp.dd.licensing_held'
  | 'partner.sp.dd.security_compliance'
  | 'partner.sp.dd.team_seniority_mix'
  | 'partner.sp.dd.tooling_integrations'
  | 'partner.sp.deal_volume_pref_qtr'
  | 'partner.sp.deferred_fees_open'
  | 'partner.sp.escalation_contact'
  | 'partner.sp.exclusivity_clauses'
  | 'partner.sp.expansion_goal'
  | 'partner.sp.firm_type'
  | 'partner.sp.geos_served'
  | 'partner.sp.headquarter_geo'
  | 'partner.sp.improvement_suggestion'
  | 'partner.sp.intake_process'
  | 'partner.sp.intro_friendly'
  | 'partner.sp.kickoff_time_days'
  | 'partner.sp.preferred_comms_channel'
  | 'partner.sp.pricing_model'
  | 'partner.sp.priority_focus_qtr'
  | 'partner.sp.references_count'
  | 'partner.sp.referral_nps'
  | 'partner.sp.satisfaction_score'
  | 'partner.sp.scope_minimum_usd'
  | 'partner.sp.services_detailed'
  | 'partner.sp.signature_offering'
  | 'partner.sp.sla_response_hours'
  | 'partner.sp.startup_discount_pct'
  | 'partner.sp.startup_team_size'
  | 'partner.sp.success_metric'
  | 'partner.sp.target_sectors'
  | 'partner.sp.target_stages'
  | 'partner.sp.team_size'
  | 'partner.sp.tooling_used'
  | 'partner.sp.weekly_digest_optin'
  | 'partner.sp.years_in_business'
  | 'partner.st.api_or_marketplace'
  | 'partner.st.assets_offered'
  | 'partner.st.audience_reach'
  | 'partner.st.biggest_friction'
  | 'partner.st.brand_assets_available'
  | 'partner.st.budget_band_usd'
  | 'partner.st.case_study_link'
  | 'partner.st.commercial_minimums'
  | 'partner.st.compliance_constraints'
  | 'partner.st.conflicts_competitors'
  | 'partner.st.conflicts_existing_partners'
  | 'partner.st.dd.api_access_program'
  | 'partner.st.dd.brand_co_marketing_examples'
  | 'partner.st.dd.competitive_intel_share'
  | 'partner.st.dd.data_sharing_open'
  | 'partner.st.dd.event_co_hosting'
  | 'partner.st.dd.executive_intros'
  | 'partner.st.dd.intl_expansion_help'
  | 'partner.st.dd.ip_licensing_open'
  | 'partner.st.dd.poc_funding_available'
  | 'partner.st.dd.procurement_path'
  | 'partner.st.dd.regulatory_help'
  | 'partner.st.dd.sustainability_priorities'
  | 'partner.st.dd.warm_intro_quota'
  | 'partner.st.exclusivity_offered'
  | 'partner.st.executive_sponsor'
  | 'partner.st.ideal_partner_archetype'
  | 'partner.st.industry'
  | 'partner.st.kpi_north_star'
  | 'partner.st.legal_template_speed_days'
  | 'partner.st.parent_company'
  | 'partner.st.partnership_type'
  | 'partner.st.partnership_volume_qtr'
  | 'partner.st.preferred_comms'
  | 'partner.st.qualifying_traction'
  | 'partner.st.quarter_focus'
  | 'partner.st.referral_economics'
  | 'partner.st.referral_nps'
  | 'partner.st.regions_active'
  | 'partner.st.review_cadence'
  | 'partner.st.satisfaction_score'
  | 'partner.st.success_examples_count'
  | 'partner.st.success_metric'
  | 'partner.st.suggestion_for_studio'
  | 'partner.st.target_sectors'
  | 'partner.st.target_stages'
  | 'partner.st.team_dedicated_to_partnerships'
  | 'partner.st.warm_intro_required'
  | 'partner.st.weekly_digest_optin'
  | 'partner.st.years_in_partnerships'
  | 'role_detect.headline'
  | 'role_detect.organization'
  | 'role_detect.primary';

export const ADVISOR_QUESTION_IDS: readonly AdvisorQuestionId[] = [
  "admin.governance.access_review_cadence",
  "admin.governance.data_retention_pref",
  "admin.operations.intake_priority",
  "admin.operations.onboarding_sla",
  "admin.oversight.escalation_threshold",
  "admin.oversight.portfolio_focus",
  "admin.oversight.review_cadence",
  "admin.oversight.risk_tolerance",
  "admin.preferences.alert_channel",
  "admin.preferences.digest_freq",
  "admin.preferences.timezone",
  "advisor.calendar.notice_required_hours",
  "advisor.calendar.office_hours_window",
  "advisor.calendar.timezones_covered",
  "advisor.calendar.weekly_hours",
  "advisor.comp.equity_open",
  "advisor.comp.minimum_engagement_hours",
  "advisor.engagement.active_founders",
  "advisor.engagement.biggest_friction",
  "advisor.engagement.intros_made_qtr",
  "advisor.engagement.referral_likely",
  "advisor.engagement.satisfaction",
  "advisor.expertise.adoption_curve",
  "advisor.expertise.depth_or_breadth",
  "advisor.expertise.geographies",
  "advisor.expertise.stages",
  "advisor.profile.bio",
  "advisor.profile.display_name",
  "advisor.profile.exits_or_outcomes",
  "advisor.profile.expertise",
  "advisor.profile.hourly_rate_usd",
  "advisor.profile.linkedin_url",
  "advisor.profile.public_writing",
  "advisor.profile.sectors",
  "advisor.profile.years_operating",
  "advisor.topics.async_vs_sync",
  "advisor.topics.preferred_session_length_min",
  "advisor.topics.recent_wins",
  "advisor.topics.signature_session",
  "advisor.topics.unwilling",
  "advisor.topics.willing",
  "founder.advisors.current_advisors",
  "founder.advisors.gap_areas",
  "founder.advisors.intro_priority",
  "founder.advisors.most_valuable",
  "founder.advisors.needs",
  "founder.brand.tagline",
  "founder.brand.theme_color",
  "founder.capital.bridge_likely",
  "founder.capital.dilution_floor_pct",
  "founder.capital.investors_on_captable",
  "founder.capital.lead_status",
  "founder.capital.option_pool_pct",
  "founder.capital.preferred_lead_funds",
  "founder.capital.previous_round_post_usd",
  "founder.capital.previous_round_usd",
  "founder.capital.raise_active",
  "founder.capital.raise_target_usd",
  "founder.capital.runway_after_raise_months",
  "founder.capital.target_close_date",
  "founder.capital.use_of_funds",
  "founder.capital.valuation_target_usd",
  "founder.capital.warm_intro_count",
  "founder.captable.entity",
  "founder.captable.ownership",
  "founder.compliance.status",
  "founder.dd.ai_data_moat",
  "founder.dd.ai_inference_cost_per_1k",
  "founder.dd.ai_model_strategy",
  "founder.dd.b2b_saas_logos_paid",
  "founder.dd.b2b_saas_seat_expansion",
  "founder.dd.climate_carbon_metric",
  "founder.dd.consumer_cac_payback_months",
  "founder.dd.consumer_d30_retention_pct",
  "founder.dd.deeptech_tech_readiness",
  "founder.dd.fintech_chargeback_pct",
  "founder.dd.fintech_kyc",
  "founder.dd.fintech_licensing",
  "founder.dd.healthcare_hipaa_status",
  "founder.dd.preseed_lois",
  "founder.dd.seriesa_cohort_retention",
  "founder.dd.seriesb_growth_rate",
  "founder.deck.market",
  "founder.deck.problem",
  "founder.discovery.interview1.name",
  "founder.discovery.interview1.pains",
  "founder.discovery.interview2.name",
  "founder.discovery.interview2.pains",
  "founder.discovery.interview3.name",
  "founder.discovery.interview3.pains",
  "founder.financials.arr_usd",
  "founder.financials.bookings_qtr_usd",
  "founder.financials.budget_vs_actual",
  "founder.financials.cac_usd",
  "founder.financials.financial_model_link",
  "founder.financials.gross_margin_pct",
  "founder.financials.gross_revenue_retention_pct",
  "founder.financials.ltv_usd",
  "founder.financials.magic_number",
  "founder.financials.monthly_burn_usd",
  "founder.financials.mrr_usd",
  "founder.financials.net_revenue_retention_pct",
  "founder.financials.payback_months",
  "founder.financials.runway_months",
  "founder.fit.activation_definition",
  "founder.fit.activation_rate_pct",
  "founder.fit.adoption_curve",
  "founder.fit.churn_top_reason",
  "founder.fit.discovery_volume_qtr",
  "founder.fit.expansion_signal",
  "founder.fit.icp_segments",
  "founder.fit.icp_statement",
  "founder.fit.icp_v_buyer",
  "founder.fit.ipspf_signal",
  "founder.fit.nps_or_csat",
  "founder.fit.retention_30d_pct",
  "founder.gtm.avg_acv_usd",
  "founder.gtm.brand_awareness",
  "founder.gtm.channel_cac_split",
  "founder.gtm.community_motion",
  "founder.gtm.customer_advisory_board",
  "founder.gtm.first_call_to_close_pct",
  "founder.gtm.inbound_lead_volume_wk",
  "founder.gtm.outbound_volume_wk",
  "founder.gtm.pricing_changes_planned",
  "founder.gtm.pricing_model",
  "founder.gtm.primary_channel",
  "founder.lab.advisors.cadence",
  "founder.lab.advisors.intro_target",
  "founder.lab.advisors.priority1",
  "founder.lab.advisors.style",
  "founder.lab.advisors.warm_path",
  "founder.lab.capital.first_raise_target",
  "founder.lab.capital.instrument",
  "founder.lab.capital.lead_investor",
  "founder.lab.capital.runway_target_months",
  "founder.lab.capital.target_investors",
  "founder.lab.capital.warm_intros",
  "founder.lab.deck.ask",
  "founder.lab.deck.business_model",
  "founder.lab.deck.competition_map",
  "founder.lab.deck.demo_link",
  "founder.lab.deck.go_to_market",
  "founder.lab.deck.moat",
  "founder.lab.deck.solution",
  "founder.lab.deck.team_slide",
  "founder.lab.deck.why_now",
  "founder.lab.discovery.alternatives",
  "founder.lab.discovery.deal_breaker",
  "founder.lab.discovery.followup_scheduled",
  "founder.lab.discovery.icp_buyer_vs_user",
  "founder.lab.discovery.icp_v1",
  "founder.lab.discovery.pivot_signal",
  "founder.lab.discovery.signal_score",
  "founder.lab.discovery.willingness_to_pay",
  "founder.lab.legal.83b_planned",
  "founder.lab.legal.advisor_seats",
  "founder.lab.legal.ip_assignment",
  "founder.lab.legal.prior_employer_ip",
  "founder.lab.legal.state",
  "founder.lab.metrics.first_north_star",
  "founder.lab.metrics.signal_v_noise",
  "founder.lab.metrics.tracking_tool",
  "founder.lab.metrics.weekly_target",
  "founder.lab.ops.accounting_provider",
  "founder.lab.ops.bank_setup",
  "founder.lab.ops.budget_template",
  "founder.lab.ops.communication_norm",
  "founder.lab.ops.first_hire_comp",
  "founder.lab.ops.first_hire_role",
  "founder.lab.ops.first_hire_when",
  "founder.lab.ops.governance_doc",
  "founder.lab.ops.payroll_provider",
  "founder.lab.ops.weekly_review",
  "founder.lab.roadmap.kr_for_obj1",
  "founder.lab.roadmap.kr_for_obj2",
  "founder.lab.roadmap.kr_for_obj3",
  "founder.lab.roadmap.weekly_cadence",
  "founder.lab.team.cofounder_gap",
  "founder.lab.team.dealbreakers",
  "founder.lab.team.equity_philosophy",
  "founder.lab.team.first_5_hires",
  "founder.lab.team.remote_or_office",
  "founder.lab.wellbeing.biggest_blocker",
  "founder.lab.wellbeing.cofounder_pulse",
  "founder.lab.wellbeing.energy",
  "founder.lab.wellbeing.exercise_freq",
  "founder.lab.wellbeing.scary_question",
  "founder.lab.wellbeing.sleep_hours",
  "founder.lab.wellbeing.support",
  "founder.legal.dpa_template",
  "founder.legal.export_controls",
  "founder.legal.foreign_subsidiaries",
  "founder.legal.ip_assignment_status",
  "founder.legal.litigation_active",
  "founder.legal.patents_filed",
  "founder.legal.privacy_policy",
  "founder.legal.security_certs",
  "founder.legal.terms_of_service_current",
  "founder.legal.trademarks_filed",
  "founder.okrs.q1_objective1",
  "founder.okrs.q1_objective2",
  "founder.okrs.q1_objective3",
  "founder.ops.allhands_cadence",
  "founder.ops.board_cadence",
  "founder.ops.bug_triage_sla_hrs",
  "founder.ops.knowledge_base",
  "founder.ops.okrs_cadence",
  "founder.ops.oncall_rotation",
  "founder.ops.standup_format",
  "founder.ops.tooling_stack",
  "founder.ops.weekly_metric_cadence",
  "founder.partners.active_count",
  "founder.partners.biggest_friction",
  "founder.partners.health_score",
  "founder.pipeline.avg_sales_cycle_days",
  "founder.pipeline.size_usd",
  "founder.pipeline.top_deals",
  "founder.pipeline.win_rate_pct",
  "founder.product.dev_velocity",
  "founder.product.next_big_bet",
  "founder.product.platform_choice",
  "founder.product.qa_coverage",
  "founder.product.tech_debt_score",
  "founder.product.what_breaks",
  "founder.product.what_works",
  "founder.project.cac_usd",
  "founder.project.contact_email",
  "founder.project.gross_margin_pct",
  "founder.project.logo_url",
  "founder.project.name",
  "founder.project.pitch",
  "founder.project.sector",
  "founder.project.som_usd",
  "founder.project.stage",
  "founder.project.tagline",
  "founder.project.traction",
  "founder.project.traction_summary",
  "founder.project.vision",
  "founder.team.attrition_12m",
  "founder.team.cofounders",
  "founder.team.compensation_philosophy",
  "founder.team.culture_doc_link",
  "founder.team.diversity_snapshot",
  "founder.team.equity_refresh_policy",
  "founder.team.exec_team_complete",
  "founder.team.first_eng_hired",
  "founder.team.headcount_by_function",
  "founder.team.headcount_total",
  "founder.team.hires_planned_qtr",
  "founder.team.remote_policy",
  "founder.wellbeing.biggest_stressor",
  "founder.wellbeing.energy_score",
  "founder.wellbeing.sleep_hours",
  "founder.wellbeing.support_system",
  "founder.wellbeing.therapist_or_coach",
  "founder.wellbeing.vacation_planned",
  "investor.coinvest.minimum_lead_check_usd",
  "investor.coinvest.preferences",
  "investor.coinvest.preferred_partners",
  "investor.dd.background_checks",
  "investor.dd.checklist_link",
  "investor.dd.competitive_diligence_method",
  "investor.dd.customer_calls_required",
  "investor.dd.financial_diligence_depth",
  "investor.dd.legal_review_outsourced",
  "investor.dd.red_flags_recent",
  "investor.dd.references_required",
  "investor.dd.tech_diligence_partner",
  "investor.dd.valuation_framework",
  "investor.lp.communication_pain",
  "investor.lp.dpi_to_date_x",
  "investor.lp.next_fund_planning",
  "investor.lp.report_cadence",
  "investor.lp.report_format",
  "investor.lp.tvpi_to_date_x",
  "investor.pipeline.avg_dd_days",
  "investor.pipeline.deal_volume",
  "investor.pipeline.deals_per_partner",
  "investor.pipeline.first_meetings_qtr",
  "investor.pipeline.investments_closed_qtr",
  "investor.pipeline.scout_program",
  "investor.pipeline.source_split",
  "investor.pipeline.term_sheets_qtr",
  "investor.portfolio.board_seats",
  "investor.portfolio.exits_to_date",
  "investor.portfolio.followon_reserves_pct",
  "investor.portfolio.intros_made_qtr",
  "investor.portfolio.observer_seats",
  "investor.portfolio.review_cadence",
  "investor.portfolio.support_offered",
  "investor.portfolio.total_companies",
  "investor.profile.fund_size_usd",
  "investor.profile.fund_vintage",
  "investor.profile.geo_focus",
  "investor.profile.investor_type",
  "investor.profile.lp_base",
  "investor.profile.sectors",
  "investor.profile.stages",
  "investor.profile.thesis",
  "investor.profile.ticket_band",
  "investor.sector.ai_inference_econ",
  "investor.sector.climate_metric_required",
  "investor.sector.consumer_payback_floor",
  "investor.sector.deeptech_capital_intensity",
  "investor.sector.fintech_regulatory",
  "investor.sector.healthcare_reimbursement",
  "investor.thesis.adoption_curve_focus",
  "investor.thesis.contrarian_view",
  "investor.thesis.deal_breakers",
  "investor.thesis.founder_archetype",
  "investor.thesis.macro_trends",
  "investor.thesis.market_size_floor_usd",
  "investor.thesis.must_haves",
  "investor.thesis.passes_recent",
  "investor.watchlist.alert_cadence",
  "investor.watchlist.seed_companies",
  "investor.watchlist.shadow_companies",
  "investor.watchlist.signals_of_interest",
  "partner.comp.model",
  "partner.conflicts.list",
  "partner.cv.average_dd_days",
  "partner.cv.balance_sheet_or_separate",
  "partner.cv.biggest_friction",
  "partner.cv.coinvest_partners",
  "partner.cv.commercial_bundle_offered",
  "partner.cv.conflicts_competitors",
  "partner.cv.conflicts_existing_portcos",
  "partner.cv.cvc_team_size",
  "partner.cv.cvc_unit_age_years",
  "partner.cv.dd.board_seats_required",
  "partner.cv.dd.brand_use_restrictions",
  "partner.cv.dd.bridge_support",
  "partner.cv.dd.commercial_signoff_required",
  "partner.cv.dd.commercial_team_intros",
  "partner.cv.dd.commercial_velocity_days",
  "partner.cv.dd.followon_signal_window",
  "partner.cv.dd.lp_communication_role",
  "partner.cv.dd.preferred_exit_path",
  "partner.cv.dd.pro_rata_intent",
  "partner.cv.dd.product_roadmap_input",
  "partner.cv.dd.public_pr_consent",
  "partner.cv.dd.right_of_first_refusal",
  "partner.cv.deals_closed_qtr",
  "partner.cv.deals_screened_qtr",
  "partner.cv.dilution_neutral_clauses",
  "partner.cv.executive_sponsor",
  "partner.cv.followon_reserve_pct",
  "partner.cv.fund_size_usd",
  "partner.cv.geos_active",
  "partner.cv.investments_per_yr",
  "partner.cv.lead_or_follow",
  "partner.cv.lps_or_internal_committee",
  "partner.cv.next_year_priorities",
  "partner.cv.parent_company",
  "partner.cv.preferred_comms",
  "partner.cv.quarter_focus",
  "partner.cv.referral_nps",
  "partner.cv.regulatory_constraints",
  "partner.cv.review_cadence",
  "partner.cv.satisfaction_score",
  "partner.cv.strategic_vs_financial",
  "partner.cv.success_metric",
  "partner.cv.suggestion_for_studio",
  "partner.cv.support_offered",
  "partner.cv.target_sectors",
  "partner.cv.target_stages",
  "partner.cv.thesis_one_line",
  "partner.cv.ticket_band_usd",
  "partner.cv.warm_intro_required",
  "partner.cv.weekly_digest_optin",
  "partner.dealflow.channels",
  "partner.deals.interest",
  "partner.firm.name",
  "partner.ma.adoption_curve",
  "partner.ma.async_or_sync",
  "partner.ma.biggest_friction",
  "partner.ma.calendar_link",
  "partner.ma.case_studies_open",
  "partner.ma.cash_rate_usd_hr",
  "partner.ma.coaching_credentials",
  "partner.ma.community_participation",
  "partner.ma.confidentiality_practice",
  "partner.ma.conflicts_companies",
  "partner.ma.conflicts_funds",
  "partner.ma.current_advisor_seats",
  "partner.ma.current_eir_engagements",
  "partner.ma.dd.board_observer_open",
  "partner.ma.dd.crisis_support",
  "partner.ma.dd.exec_search_partners",
  "partner.ma.dd.feedback_style",
  "partner.ma.dd.fundraising_help",
  "partner.ma.dd.go_to_market",
  "partner.ma.dd.hiring_help",
  "partner.ma.dd.intl_geo_expertise",
  "partner.ma.dd.podcast_or_writing_consent",
  "partner.ma.dd.preferred_meeting_format",
  "partner.ma.dd.product_strategy",
  "partner.ma.dd.public_speaking_open",
  "partner.ma.dd.regulatory_navigation",
  "partner.ma.dd.workshops_offered",
  "partner.ma.equity_floor_pct",
  "partner.ma.founder_archetype",
  "partner.ma.functional_expertise",
  "partner.ma.geos_active",
  "partner.ma.intake_process",
  "partner.ma.intros_offered_qtr",
  "partner.ma.minimum_engagement_months",
  "partner.ma.notable_outcomes",
  "partner.ma.preferred_comms",
  "partner.ma.pricing_model",
  "partner.ma.quarter_focus",
  "partner.ma.referral_nps",
  "partner.ma.role_type",
  "partner.ma.satisfaction_score",
  "partner.ma.session_length_min",
  "partner.ma.signature_topic",
  "partner.ma.success_metric",
  "partner.ma.suggestion_for_studio",
  "partner.ma.target_sectors",
  "partner.ma.target_stages",
  "partner.ma.weekly_digest_optin",
  "partner.ma.weekly_hours_open",
  "partner.ma.years_operating",
  "partner.profile.focus",
  "partner.rate.hourly",
  "partner.rate.project",
  "partner.role.kind",
  "partner.services.offered",
  "partner.sp.availability_office_hours",
  "partner.sp.biggest_friction",
  "partner.sp.case_study_consent",
  "partner.sp.case_study_link",
  "partner.sp.cold_inbound_open",
  "partner.sp.confidentiality_walls",
  "partner.sp.conflicts_companies",
  "partner.sp.conflicts_sectors",
  "partner.sp.current_capacity_pct",
  "partner.sp.dd.ai_specialty",
  "partner.sp.dd.data_handling",
  "partner.sp.dd.engagement_kpi",
  "partner.sp.dd.fintech_specialty",
  "partner.sp.dd.healthcare_specialty",
  "partner.sp.dd.intl_expansion",
  "partner.sp.dd.licensing_held",
  "partner.sp.dd.security_compliance",
  "partner.sp.dd.team_seniority_mix",
  "partner.sp.dd.tooling_integrations",
  "partner.sp.deal_volume_pref_qtr",
  "partner.sp.deferred_fees_open",
  "partner.sp.escalation_contact",
  "partner.sp.exclusivity_clauses",
  "partner.sp.expansion_goal",
  "partner.sp.firm_type",
  "partner.sp.geos_served",
  "partner.sp.headquarter_geo",
  "partner.sp.improvement_suggestion",
  "partner.sp.intake_process",
  "partner.sp.intro_friendly",
  "partner.sp.kickoff_time_days",
  "partner.sp.preferred_comms_channel",
  "partner.sp.pricing_model",
  "partner.sp.priority_focus_qtr",
  "partner.sp.references_count",
  "partner.sp.referral_nps",
  "partner.sp.satisfaction_score",
  "partner.sp.scope_minimum_usd",
  "partner.sp.services_detailed",
  "partner.sp.signature_offering",
  "partner.sp.sla_response_hours",
  "partner.sp.startup_discount_pct",
  "partner.sp.startup_team_size",
  "partner.sp.success_metric",
  "partner.sp.target_sectors",
  "partner.sp.target_stages",
  "partner.sp.team_size",
  "partner.sp.tooling_used",
  "partner.sp.weekly_digest_optin",
  "partner.sp.years_in_business",
  "partner.st.api_or_marketplace",
  "partner.st.assets_offered",
  "partner.st.audience_reach",
  "partner.st.biggest_friction",
  "partner.st.brand_assets_available",
  "partner.st.budget_band_usd",
  "partner.st.case_study_link",
  "partner.st.commercial_minimums",
  "partner.st.compliance_constraints",
  "partner.st.conflicts_competitors",
  "partner.st.conflicts_existing_partners",
  "partner.st.dd.api_access_program",
  "partner.st.dd.brand_co_marketing_examples",
  "partner.st.dd.competitive_intel_share",
  "partner.st.dd.data_sharing_open",
  "partner.st.dd.event_co_hosting",
  "partner.st.dd.executive_intros",
  "partner.st.dd.intl_expansion_help",
  "partner.st.dd.ip_licensing_open",
  "partner.st.dd.poc_funding_available",
  "partner.st.dd.procurement_path",
  "partner.st.dd.regulatory_help",
  "partner.st.dd.sustainability_priorities",
  "partner.st.dd.warm_intro_quota",
  "partner.st.exclusivity_offered",
  "partner.st.executive_sponsor",
  "partner.st.ideal_partner_archetype",
  "partner.st.industry",
  "partner.st.kpi_north_star",
  "partner.st.legal_template_speed_days",
  "partner.st.parent_company",
  "partner.st.partnership_type",
  "partner.st.partnership_volume_qtr",
  "partner.st.preferred_comms",
  "partner.st.qualifying_traction",
  "partner.st.quarter_focus",
  "partner.st.referral_economics",
  "partner.st.referral_nps",
  "partner.st.regions_active",
  "partner.st.review_cadence",
  "partner.st.satisfaction_score",
  "partner.st.success_examples_count",
  "partner.st.success_metric",
  "partner.st.suggestion_for_studio",
  "partner.st.target_sectors",
  "partner.st.target_stages",
  "partner.st.team_dedicated_to_partnerships",
  "partner.st.warm_intro_required",
  "partner.st.weekly_digest_optin",
  "partner.st.years_in_partnerships",
  "role_detect.headline",
  "role_detect.organization",
  "role_detect.primary"
] as const;
