// PROFILE_ROUTING.md and PAGE_INVENTORY.md are generated from ROUTE_MAP.md and
// sidebarConfig.js. That is only worth anything if the generated copy on disk
// is actually current — a stale projection is exactly the failure this
// repository keeps paying for (a runbook that hardcoded a migration range, a
// cutover doc that hardcoded a route-table size, a production doc that cited a
// line number: each true when written, each wrong within a week).
//
// So this file is the freshness gate. Change ROUTE_MAP or the sidebar without
// re-running the generator and the build fails here, naming the command.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  outputs, parseRouteMap, parseSidebar, routesIn, workspacesFor,
} from '../../scripts/build-profile-routing.mjs';

const read = (p) => readFileSync(resolve(p), 'utf8');

test('the generated docs on disk match their sources', () => {
  for (const [path, expected] of outputs()) {
    assert.equal(
      read(path), expected,
      `${path} is stale. Re-run: node scripts/build-profile-routing.mjs`,
    );
  }
});

test('both generated docs carry the do-not-hand-edit stamp', () => {
  for (const [path] of outputs()) {
    const src = read(path);
    assert.match(src, /GENERATED by scripts\/build-profile-routing\.mjs/);
    assert.match(src, /do not hand-edit/);
  }
});

test('ROUTE_MAP still parses to the full canvas corpus', () => {
  const recs = parseRouteMap(read('documentation/architecture/ROUTE_MAP.md'));
  // The corpus is 107 canonical canvases; ROUTE_MAP's own header says so, and
  // design/canvases/README.md repeats it. If a row is added the number moves —
  // that is fine, but it must move deliberately, so it is asserted here rather
  // than left to drift silently past a parser that quietly stopped matching.
  assert.equal(recs.length, 107);
  for (const r of recs) {
    assert.ok(r.canvas.length > 0, 'every row names a canvas');
    assert.ok(r.status.length > 0, `row "${r.canvas}" has no status`);
  }
});

test('every canvas resolves to at least one workspace', () => {
  const recs = parseRouteMap(read('documentation/architecture/ROUTE_MAP.md'));
  for (const r of recs) {
    assert.ok(workspacesFor(r.persona).length > 0, `persona "${r.persona}" mapped to nothing`);
  }
});

test('the sidebar parser finds every role, and no role parses empty', () => {
  const roles = parseSidebar(read('frontend/src/sidebarConfig.js'));
  // The six shipped role sidebars. Partner/Operator is deliberately among them
  // even though the integration brief names only five workspaces — see
  // documentation/architecture/ASSUMPTIONS_LOG.md A2.
  for (const key of ['founder', 'advisor', 'investor', 'partner', 'admin', 'exploring']) {
    assert.ok(roles[key], `sidebarConfig has no ${key} role`);
    assert.ok(roles[key].length > 0, `${key} parsed to zero destinations`);
  }
});

test('the sidebar parser does not report commented-out destinations', () => {
  const roles = parseSidebar(read('frontend/src/sidebarConfig.js'));
  // The X (Twitter) broadcaster is commented out pending OAuth provisioning.
  // A parser that read comments would advertise a door that is not there.
  const all = Object.values(roles).flat();
  assert.equal(all.filter((i) => i.to === '/admin/x').length, 0);
});

test('routesIn pulls routes out of a ROUTE_MAP cell and ignores prose', () => {
  assert.deepEqual(routesIn('`/a` · `/b/:id`'), ['/a', '/b/:id']);
  assert.deepEqual(routesIn('same set'), []);
  assert.deepEqual(routesIn('`/x` (`/y` 301s to it, App.jsx:1849)'), ['/x', '/y']);
  assert.deepEqual(routesIn('— (right-rail component, no route)'), []);
});

test('a malformed ROUTE_MAP row fails loudly rather than shifting columns', () => {
  const bad = [
    '| Canvas | Persona | Proposed route | Live route today | Backend it wires to | STATUS | Notes |',
    '| --- | --- | --- | --- | --- | --- | --- |',
    '| Half a row | founder | `/x` |',
  ].join('\n');
  assert.throws(() => parseRouteMap(bad), /expected >= 7/);
});
