// Personal Advisor question bank.
// Source of truth for every question the advisor asks. Each question:
//   - is tagged to one or more personas
//   - writes to a specific page/column via the server-side write-router
//   - declares its importance for ranking inside the advisor
//   - may be gated by Spin-Out Lab week, tier, or feature unlock
//   - may be flagged for Market Intelligence extraction (sentiment, TALC)
//
// The shape mirrors what cloudflare-worker/src/services/advisor/writeRouter.ts
// expects. Keep `id` stable — it's the primary key the write-router maps on.

export type Persona =
  | 'newFounder'
  | 'existingFounder'
  | 'investor'
  | 'opPartnerCapital'
  | 'opPartnerServices'
  | 'opPartnerSourcing'
  | 'opPartnerMixed'
  | 'mentor';

export type SpinoutWeek = 1 | 2 | 3 | 4;

export type QType =
  | 'text'
  | 'textarea'
  | 'number'
  | 'currency'
  | 'percent'
  | 'date'
  | 'select'
  | 'multiselect'
  | 'range'
  | 'toggle'
  | 'file'
  | 'url'
  | 'email'
  | 'phone';

export type Importance = 'critical' | 'high' | 'med' | 'low';

export type TierKey =
  | 'free'
  | 'growth'
  | 'studio'
  | 'investor_free'
  | 'investor_pro'
  | 'investor_inst';

export type ValidateKey =
  | 'iso2country'
  | 'url'
  | 'email'
  | 'phone_e164'
  | 'positive_number'
  | 'percent_0_100'
  | 'iso_date'
  | 'slug'
  | 'iban'
  | 'tax_id';

export interface Question {
  id: string;
  persona: Persona[];
  section: string;
  page_target?: string;
  label: string;
  type: QType;
  options?: { value: string; label: string }[];
  required?: boolean;
  importance: Importance;
  unlock_required?: SpinoutWeek;
  tier_required?: TierKey;
  validate?: ValidateKey;
  min?: number;
  max?: number;
  step?: number;
  evidence?: 'required' | 'recommended';
  sentiment_eligible?: boolean;
  talc_eligible?: boolean;
  pii?: boolean;
  explainer: string;
  doc_anchor: string;
  followups?: { when: string; ask: string[] }[];
}

const SECTORS = [
  'ai_infra', 'ai_app', 'fintech', 'insurtech', 'climate', 'energy',
  'biotech', 'health', 'medtech', 'enterprise_saas', 'devtools',
  'security', 'data', 'commerce', 'consumer', 'creator', 'gaming',
  'edtech', 'legaltech', 'proptech', 'mobility', 'logistics',
  'agtech', 'foodtech', 'industrial', 'robotics', 'space',
  'defense', 'web3', 'hardware', 'marketplace', 'other',
].map(v => ({ value: v, label: v.replace(/_/g, ' ') }));

const STAGES = [
  { value: 'idea',    label: 'Idea' },
  { value: 'preseed', label: 'Pre-seed' },
  { value: 'seed',    label: 'Seed' },
  { value: 'a',       label: 'Series A' },
  { value: 'b',       label: 'Series B' },
  { value: 'c_plus',  label: 'Series C+' },
];

const TALC = [
  { value: 'innovators',      label: 'Innovators (2.5%)' },
  { value: 'early_adopters',  label: 'Early adopters (13.5%)' },
  { value: 'early_majority',  label: 'Early majority (34%)' },
  { value: 'late_majority',   label: 'Late majority (34%)' },
  { value: 'laggards',        label: 'Laggards (16%)' },
];

// ──────────────────────────────────────────────────────────────────────────
// NEW FOUNDER · SPIN-OUT LAB — WEEK 1 · Idea & Problem Validation
// ──────────────────────────────────────────────────────────────────────────

const W1: Question[] = [
  {
    id: 'newFounder.w1.about.first_name',
    persona: ['newFounder'],
    section: 'spinout.week_1.about',
    page_target: 'users.first_name',
    label: 'What name should we call you?',
    type: 'text',
    importance: 'critical',
    required: true,
    unlock_required: 1,
    pii: true,
    explainer: 'Used in greetings and any documents we generate for you.',
    doc_anchor: 'spinout/week-1',
  },
  {
    id: 'newFounder.w1.about.country',
    persona: ['newFounder'],
    section: 'spinout.week_1.about',
    page_target: 'users.country',
    label: 'Where are you based?',
    type: 'select',
    importance: 'high',
    required: true,
    unlock_required: 1,
    validate: 'iso2country',
    explainer: 'Drives jurisdiction defaults for incorporation in Week 4.',
    doc_anchor: 'spinout/week-1',
  },
  {
    id: 'newFounder.w1.about.timezone',
    persona: ['newFounder'],
    section: 'spinout.week_1.about',
    page_target: 'users.timezone',
    label: 'What time zone are you in?',
    type: 'select',
    importance: 'med',
    unlock_required: 1,
    explainer: 'So mentors and office hours show in your local time.',
    doc_anchor: 'spinout/week-1',
  },
  {
    id: 'newFounder.w1.about.commitment',
    persona: ['newFounder'],
    section: 'spinout.week_1.about',
    page_target: 'founders.commitment',
    label: 'Are you working on this full-time, part-time, or evenings/weekends?',
    type: 'select',
    options: [
      { value: 'ft', label: 'Full-time' },
      { value: 'pt', label: 'Part-time' },
      { value: 'nights', label: 'Nights & weekends' },
    ],
    importance: 'high',
    unlock_required: 1,
    explainer: 'Investors care a lot about commitment level. Be honest.',
    doc_anchor: 'spinout/week-1',
  },
  {
    id: 'newFounder.w1.about.prior_ventures',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_1.about',
    page_target: 'founders.prior_ventures_json',
    label: 'Any prior ventures? List name, outcome, your role.',
    type: 'textarea',
    importance: 'med',
    unlock_required: 1,
    explainer: 'Helps us position your track record in your deck.',
    doc_anchor: 'spinout/week-1',
  },
  {
    id: 'newFounder.w1.idea.one_liner',
    persona: ['newFounder'],
    section: 'spinout.week_1.idea',
    page_target: 'projects.one_liner',
    label: 'Describe your idea in one sentence.',
    type: 'textarea',
    importance: 'critical',
    required: true,
    unlock_required: 1,
    sentiment_eligible: true,
    explainer: 'If you can\'t fit it in one sentence, the idea is still fuzzy.',
    doc_anchor: 'build/projects',
  },
  {
    id: 'newFounder.w1.idea.problem',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_1.idea',
    page_target: 'projects.problem_statement',
    label: 'What problem are you solving?',
    type: 'textarea',
    importance: 'critical',
    required: true,
    unlock_required: 1,
    sentiment_eligible: true,
    explainer: 'The clearer the pain, the faster customers say yes.',
    doc_anchor: 'build/projects',
  },
  {
    id: 'newFounder.w1.idea.who_hurts',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_1.idea',
    page_target: 'projects.target_icp_json',
    label: 'Who hurts the most from this problem?',
    type: 'textarea',
    importance: 'critical',
    unlock_required: 1,
    explainer: 'Be specific: job title, company size, industry, country.',
    doc_anchor: 'build/projects',
  },
  {
    id: 'newFounder.w1.idea.urgency',
    persona: ['newFounder', 'existingFounder', 'investor'],
    section: 'spinout.week_1.idea',
    page_target: 'projects.market_urgency',
    label: 'On a scale of 1–10, how urgent is this problem for them?',
    type: 'range',
    min: 1,
    max: 10,
    importance: 'high',
    unlock_required: 1,
    sentiment_eligible: true,
    explainer: 'Low urgency = hard sell. 8+ usually means they\'re hacking workarounds today.',
    doc_anchor: 'build/projects',
  },
  {
    id: 'newFounder.w1.idea.existing_solution',
    persona: ['newFounder'],
    section: 'spinout.week_1.idea',
    page_target: 'projects.existing_solution',
    label: 'How do they solve it today?',
    type: 'textarea',
    importance: 'high',
    unlock_required: 1,
    explainer: 'Spreadsheets, scripts, and competitors are all valid — name them.',
    doc_anchor: 'build/projects',
  },
  {
    id: 'newFounder.w1.idea.wedge',
    persona: ['newFounder'],
    section: 'spinout.week_1.idea',
    page_target: 'projects.wedge',
    label: 'What\'s your wedge — the one thing you do that nobody else does?',
    type: 'textarea',
    importance: 'high',
    unlock_required: 1,
    explainer: 'A wedge is narrow on purpose. Avoid "we\'re better at everything".',
    doc_anchor: 'build/projects',
  },
  {
    id: 'newFounder.w1.idea.why_you',
    persona: ['newFounder'],
    section: 'spinout.week_1.idea',
    page_target: 'projects.why_you',
    label: 'Why are you the right person to build this?',
    type: 'textarea',
    importance: 'high',
    unlock_required: 1,
    explainer: 'Domain expertise, lived experience, distribution access — any one is a strong answer.',
    doc_anchor: 'build/projects',
  },
  {
    id: 'newFounder.w1.idea.why_now',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_1.idea',
    page_target: 'projects.why_now',
    label: 'Why is now the right moment? What changed?',
    type: 'textarea',
    importance: 'high',
    unlock_required: 1,
    sentiment_eligible: true,
    explainer: 'Tech unlock, regulation, behaviour shift, cost curve — pick the strongest.',
    doc_anchor: 'build/projects',
  },
  {
    id: 'newFounder.w1.idea.sector',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_1.idea',
    page_target: 'projects.sector',
    label: 'Which sector best describes this?',
    type: 'select',
    options: SECTORS,
    importance: 'high',
    unlock_required: 1,
    explainer: 'Used to route market intelligence and matching.',
    doc_anchor: 'build/projects',
  },
  {
    id: 'newFounder.w1.idea.subsector',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_1.idea',
    page_target: 'projects.subsector',
    label: 'Any sub-sector or niche? (free text)',
    type: 'text',
    importance: 'med',
    unlock_required: 1,
    explainer: 'e.g. "claims automation for P&C insurers".',
    doc_anchor: 'build/projects',
  },
  {
    id: 'newFounder.w1.customer.icp_segment',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_1.customer',
    page_target: 'projects.icp_segment',
    label: 'Best single customer segment to start with?',
    type: 'text',
    importance: 'critical',
    unlock_required: 1,
    explainer: 'Pick one. Pluralism here kills early go-to-market.',
    doc_anchor: 'build/customer-discovery',
  },
  {
    id: 'newFounder.w1.customer.icp_size',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_1.customer',
    page_target: 'projects.icp_size',
    label: 'Typical size of that customer (employees or revenue)?',
    type: 'text',
    importance: 'high',
    unlock_required: 1,
    explainer: 'Helps size deal value and sales motion.',
    doc_anchor: 'build/customer-discovery',
  },
  {
    id: 'newFounder.w1.customer.icp_geo',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_1.customer',
    page_target: 'projects.icp_geo',
    label: 'Which geography first?',
    type: 'select',
    importance: 'high',
    unlock_required: 1,
    validate: 'iso2country',
    explainer: 'Land before you expand.',
    doc_anchor: 'build/customer-discovery',
  },
  {
    id: 'newFounder.w1.customer.willingness_to_pay',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_1.customer',
    page_target: 'projects.willingness_to_pay_usd',
    label: 'Realistic willingness-to-pay per month (USD) for this customer?',
    type: 'currency',
    importance: 'high',
    unlock_required: 1,
    explainer: 'Guess if you must — Week 1 is about hypotheses, not facts.',
    doc_anchor: 'build/customer-discovery',
  },
  {
    id: 'newFounder.w1.customer.access',
    persona: ['newFounder'],
    section: 'spinout.week_1.customer',
    page_target: 'projects.customer_access_score',
    label: 'How easily can you talk to 5 of these customers this week?',
    type: 'select',
    options: [
      { value: 'today', label: 'Today — I have warm intros' },
      { value: 'week', label: 'This week — I have cold list' },
      { value: 'tough', label: 'It\'ll be tough' },
      { value: 'none', label: 'I don\'t know any' },
    ],
    importance: 'critical',
    unlock_required: 1,
    explainer: 'No access = no discovery = no validation. We\'ll help you get there.',
    doc_anchor: 'build/customer-discovery',
  },
  {
    id: 'newFounder.w1.discovery.interview_1',
    persona: ['newFounder'],
    section: 'spinout.week_1.discovery',
    page_target: 'discovery_interviews.+',
    label: 'Tell me about your first customer interview: who, role, top quote.',
    type: 'textarea',
    importance: 'critical',
    required: true,
    unlock_required: 1,
    explainer: 'We log this as a Customer Discovery interview row.',
    doc_anchor: 'build/customer-discovery',
  },
  {
    id: 'newFounder.w1.discovery.interview_2',
    persona: ['newFounder'],
    section: 'spinout.week_1.discovery',
    page_target: 'discovery_interviews.+',
    label: 'Second interview?',
    type: 'textarea',
    importance: 'high',
    unlock_required: 1,
    explainer: 'Aim for at least 5 in Week 1.',
    doc_anchor: 'build/customer-discovery',
  },
  {
    id: 'newFounder.w1.discovery.interview_3',
    persona: ['newFounder'],
    section: 'spinout.week_1.discovery',
    page_target: 'discovery_interviews.+',
    label: 'Third interview?',
    type: 'textarea',
    importance: 'high',
    unlock_required: 1,
    explainer: 'Pattern matching kicks in around the third.',
    doc_anchor: 'build/customer-discovery',
  },
  {
    id: 'newFounder.w1.market.tam_guess',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_1.market',
    page_target: 'projects.tam_usd',
    label: 'Rough total addressable market (USD)?',
    type: 'currency',
    importance: 'high',
    unlock_required: 1,
    evidence: 'recommended',
    explainer: 'Top-down OK at this stage. We\'ll reconcile against bottom-up later.',
    doc_anchor: 'validate/market-intelligence',
  },
  {
    id: 'newFounder.w1.market.tam_source',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_1.market',
    page_target: 'projects.tam_source_url',
    label: 'URL or citation for that TAM figure?',
    type: 'url',
    importance: 'high',
    unlock_required: 1,
    evidence: 'required',
    validate: 'url',
    explainer: 'No citation = scoring engine treats TAM as unverified.',
    doc_anchor: 'validate/scoring',
  },
  {
    id: 'newFounder.w1.market.tam_bottom_up',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_1.market',
    page_target: 'projects.tam_bottom_up_usd',
    label: 'Bottom-up TAM: #customers × ACV. What\'s your back-of-envelope?',
    type: 'currency',
    importance: 'med',
    unlock_required: 1,
    explainer: 'If top-down and bottom-up disagree by more than 10×, something\'s wrong.',
    doc_anchor: 'validate/market-intelligence',
  },
  {
    id: 'newFounder.w1.market.competitors',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_1.market',
    page_target: 'projects.competitors_json',
    label: 'Top 3 competitors and how you\'re different from each.',
    type: 'textarea',
    importance: 'high',
    unlock_required: 1,
    explainer: '"None" is the wrong answer. There\'s always a status quo.',
    doc_anchor: 'validate/market-intelligence',
  },
  {
    id: 'newFounder.w1.market.talc_position',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_1.market',
    page_target: 'projects.talc_position',
    label: 'On the Technology Adoption Lifecycle, where is your sector right now?',
    type: 'select',
    options: TALC,
    importance: 'med',
    unlock_required: 1,
    talc_eligible: true,
    explainer: 'Where the market is — not where you wish it was.',
    doc_anchor: 'validate/market-intelligence',
  },
  {
    id: 'newFounder.w1.market.talc_product',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_1.market',
    page_target: 'projects.talc_product_position',
    label: 'Where is your product on that same lifecycle?',
    type: 'select',
    options: TALC,
    importance: 'med',
    unlock_required: 1,
    talc_eligible: true,
    explainer: 'Crossing the chasm = moving from early adopters to early majority.',
    doc_anchor: 'validate/market-intelligence',
  },
  {
    id: 'newFounder.w1.brand.working_name',
    persona: ['newFounder'],
    section: 'spinout.week_1.brand',
    page_target: 'projects.name',
    label: 'Working name for the venture?',
    type: 'text',
    importance: 'high',
    unlock_required: 1,
    explainer: 'Can change. Used as the project\'s name until you rebrand.',
    doc_anchor: 'build/brand-builder',
  },
];

// ──────────────────────────────────────────────────────────────────────────
// NEW FOUNDER · SPIN-OUT LAB — WEEK 2 · Solution Design & Roadmap
// ──────────────────────────────────────────────────────────────────────────

const W2: Question[] = [
  {
    id: 'newFounder.w2.solution.short',
    persona: ['newFounder'],
    section: 'spinout.week_2.solution',
    page_target: 'projects.solution',
    label: 'In two sentences, what does your solution actually do?',
    type: 'textarea',
    importance: 'critical',
    required: true,
    unlock_required: 2,
    explainer: 'Avoid adjectives. Describe the action the customer takes and the outcome they get.',
    doc_anchor: 'build/projects',
  },
  {
    id: 'newFounder.w2.solution.mvp_scope',
    persona: ['newFounder'],
    section: 'spinout.week_2.solution',
    page_target: 'projects.mvp_scope',
    label: 'What\'s in the MVP — and what\'s explicitly out?',
    type: 'textarea',
    importance: 'high',
    unlock_required: 2,
    explainer: 'Cutting scope is the founder\'s most important skill.',
    doc_anchor: 'build/projects',
  },
  {
    id: 'newFounder.w2.solution.cost_to_mvp',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_2.solution',
    page_target: 'projects.cost_to_mvp_usd',
    label: 'Estimated cost to ship MVP (USD)?',
    type: 'currency',
    importance: 'high',
    unlock_required: 2,
    explainer: 'Include people-time you value in cash.',
    doc_anchor: 'build/projects',
  },
  {
    id: 'newFounder.w2.solution.time_to_mvp',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_2.solution',
    page_target: 'projects.time_to_mvp_weeks',
    label: 'How many weeks to ship MVP?',
    type: 'number',
    min: 1,
    max: 52,
    importance: 'high',
    unlock_required: 2,
    explainer: 'Founders consistently underestimate. Be honest.',
    doc_anchor: 'build/projects',
  },
  {
    id: 'newFounder.w2.solution.tech_stack',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_2.solution',
    page_target: 'projects.tech_stack_json',
    label: 'Planned tech stack (languages, frameworks, infra)?',
    type: 'multiselect',
    options: [
      { value: 'typescript', label: 'TypeScript' }, { value: 'python', label: 'Python' },
      { value: 'go', label: 'Go' }, { value: 'rust', label: 'Rust' },
      { value: 'react', label: 'React' }, { value: 'nextjs', label: 'Next.js' },
      { value: 'cloudflare', label: 'Cloudflare Workers' }, { value: 'aws', label: 'AWS' },
      { value: 'gcp', label: 'GCP' }, { value: 'supabase', label: 'Supabase' },
      { value: 'postgres', label: 'Postgres' }, { value: 'sqlite_d1', label: 'SQLite / D1' },
      { value: 'mobile_native', label: 'Native mobile' }, { value: 'flutter', label: 'Flutter' },
      { value: 'react_native', label: 'React Native' },
    ],
    importance: 'med',
    unlock_required: 2,
    explainer: 'Sets us up to suggest the right mentors and partners.',
    doc_anchor: 'build/projects',
  },
  {
    id: 'newFounder.w2.roadmap.okr_objective_1',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_2.roadmap',
    page_target: 'roadmap_okrs.+',
    label: 'OKR #1 — what\'s the single objective for the next 90 days?',
    type: 'textarea',
    importance: 'critical',
    required: true,
    unlock_required: 2,
    explainer: 'One. Outcome-shaped. Verb + noun + measurable target.',
    doc_anchor: 'build/roadmap',
  },
  {
    id: 'newFounder.w2.roadmap.okr_kr_1',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_2.roadmap',
    page_target: 'roadmap_okrs.last.key_results',
    label: 'What 3 key results prove you hit objective #1?',
    type: 'textarea',
    importance: 'critical',
    unlock_required: 2,
    explainer: 'Numbers. Dates. Counts. Avoid "improve" and "launch" without numbers.',
    doc_anchor: 'build/roadmap',
  },
  {
    id: 'newFounder.w2.roadmap.okr_objective_2',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_2.roadmap',
    page_target: 'roadmap_okrs.+',
    label: 'OKR #2 — what\'s the supporting objective?',
    type: 'textarea',
    importance: 'high',
    unlock_required: 2,
    explainer: 'Two is enough. Three is the absolute ceiling for a small team.',
    doc_anchor: 'build/roadmap',
  },
  {
    id: 'newFounder.w2.roadmap.this_week',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_2.roadmap',
    page_target: 'roadmap_okrs.weekly',
    label: 'Top 3 deliverables this week?',
    type: 'textarea',
    importance: 'high',
    unlock_required: 2,
    explainer: 'We turn each line into a Kanban card.',
    doc_anchor: 'build/roadmap',
  },
  {
    id: 'newFounder.w2.brand.tagline',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_2.brand',
    page_target: 'projects.tagline',
    label: 'Tagline in 8 words or fewer?',
    type: 'text',
    max: 80,
    importance: 'med',
    unlock_required: 2,
    explainer: 'Imagine it on a billboard. Cutting words is the work.',
    doc_anchor: 'build/brand-builder',
  },
  {
    id: 'newFounder.w2.brand.voice',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_2.brand',
    page_target: 'projects.brand_voice',
    label: 'Brand voice in three adjectives?',
    type: 'text',
    importance: 'low',
    unlock_required: 2,
    explainer: 'e.g. "precise, irreverent, technical".',
    doc_anchor: 'build/brand-builder',
  },
  {
    id: 'newFounder.w2.brand.palette',
    persona: ['newFounder'],
    section: 'spinout.week_2.brand',
    page_target: 'projects.brand_palette_json',
    label: 'Primary + 2 accent colours (any format).',
    type: 'text',
    importance: 'low',
    unlock_required: 2,
    explainer: 'Hex or named — we\'ll normalise.',
    doc_anchor: 'build/brand-builder',
  },
  {
    id: 'newFounder.w2.deck.elevator',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_2.deck',
    page_target: 'deck_slides.elevator',
    label: 'One-paragraph elevator pitch?',
    type: 'textarea',
    importance: 'high',
    unlock_required: 2,
    explainer: 'Problem → who → solution → traction → ask. 90 seconds spoken.',
    doc_anchor: 'build/pitch-deck',
  },
  {
    id: 'newFounder.w2.deck.traction_today',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_2.deck',
    page_target: 'deck_slides.traction',
    label: 'Best traction signal you have today, no matter how small?',
    type: 'textarea',
    importance: 'high',
    unlock_required: 2,
    explainer: 'Waitlist size, LOIs, prototype demos, design partners — all valid.',
    doc_anchor: 'build/pitch-deck',
  },
];

// ──────────────────────────────────────────────────────────────────────────
// NEW FOUNDER · SPIN-OUT LAB — WEEK 3 · Validation, Co-founder, Mentors
// ──────────────────────────────────────────────────────────────────────────

const W3: Question[] = [
  {
    id: 'newFounder.w3.team.solo_or_team',
    persona: ['newFounder'],
    section: 'spinout.week_3.team',
    page_target: 'founders.team_size',
    label: 'Solo or with a co-founder?',
    type: 'select',
    options: [
      { value: 'solo', label: 'Solo' },
      { value: 'with_cofounder', label: 'I have a co-founder' },
      { value: 'looking', label: 'Looking for one' },
    ],
    importance: 'critical',
    unlock_required: 3,
    explainer: 'Solo is possible but harder. We\'ll help you find a co-founder if needed.',
    doc_anchor: 'validate/cofounder-match',
  },
  {
    id: 'newFounder.w3.team.skill_gaps',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_3.team',
    page_target: 'cofounder_preferences.skill_gaps_json',
    label: 'What skills are missing on your team? (pick all that apply)',
    type: 'multiselect',
    options: [
      { value: 'engineering', label: 'Engineering' },
      { value: 'product', label: 'Product' },
      { value: 'design', label: 'Design' },
      { value: 'sales', label: 'Sales / GTM' },
      { value: 'marketing', label: 'Marketing' },
      { value: 'finance', label: 'Finance / FP&A' },
      { value: 'legal', label: 'Legal' },
      { value: 'data', label: 'Data / ML' },
      { value: 'operations', label: 'Operations' },
      { value: 'fundraising', label: 'Fundraising' },
    ],
    importance: 'high',
    unlock_required: 3,
    explainer: 'Drives co-founder and mentor matching.',
    doc_anchor: 'validate/cofounder-match',
  },
  {
    id: 'newFounder.w3.team.cofounder_pref',
    persona: ['newFounder'],
    section: 'spinout.week_3.team',
    page_target: 'cofounder_preferences.profile',
    label: 'Ideal co-founder profile in one paragraph?',
    type: 'textarea',
    importance: 'high',
    unlock_required: 3,
    explainer: 'Skills, traits, working style, geography, equity expectations.',
    doc_anchor: 'validate/cofounder-match',
  },
  {
    id: 'newFounder.w3.mentor.help_with',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_3.mentors',
    page_target: 'mentor_requests.topics_json',
    label: 'Top 3 areas you want mentor help on?',
    type: 'multiselect',
    options: [
      { value: 'enterprise_sales', label: 'Enterprise sales' },
      { value: 'plg', label: 'Product-led growth' },
      { value: 'paid_acquisition', label: 'Paid acquisition' },
      { value: 'community', label: 'Community building' },
      { value: 'devrel', label: 'Developer relations' },
      { value: 'hiring', label: 'Hiring' },
      { value: 'pricing', label: 'Pricing & packaging' },
      { value: 'fundraising', label: 'Fundraising' },
      { value: 'compliance', label: 'Regulatory / compliance' },
      { value: 'ml', label: 'ML / data' },
      { value: 'design', label: 'Design / UX' },
      { value: 'ops', label: 'Operations / scaling' },
    ],
    importance: 'high',
    unlock_required: 3,
    explainer: 'We surface mentors who match these tags.',
    doc_anchor: 'validate/mentors',
  },
  {
    id: 'newFounder.w3.mentor.cadence',
    persona: ['newFounder'],
    section: 'spinout.week_3.mentors',
    page_target: 'mentor_requests.cadence',
    label: 'How often would you want mentor sessions?',
    type: 'select',
    options: [
      { value: 'weekly', label: 'Weekly' },
      { value: 'biweekly', label: 'Every other week' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'adhoc', label: 'As-needed' },
    ],
    importance: 'med',
    unlock_required: 3,
    explainer: 'We use this when scheduling office-hours slots.',
    doc_anchor: 'validate/mentors',
  },
  {
    id: 'newFounder.w3.validation.signal',
    persona: ['newFounder'],
    section: 'spinout.week_3.validation',
    page_target: 'projects.validation_signal',
    label: 'What\'s the strongest customer signal you got this week?',
    type: 'textarea',
    importance: 'high',
    unlock_required: 3,
    sentiment_eligible: true,
    explainer: 'Pre-orders > LOIs > "we\'d buy this" > "interesting" > silence.',
    doc_anchor: 'build/customer-discovery',
  },
  {
    id: 'newFounder.w3.validation.kill_criteria',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_3.validation',
    page_target: 'projects.kill_criteria',
    label: 'What would make you kill or pivot this idea?',
    type: 'textarea',
    importance: 'high',
    unlock_required: 3,
    explainer: 'Pre-committing to kill criteria saves months later.',
    doc_anchor: 'validate/scoring',
  },
  {
    id: 'newFounder.w3.scoring.ready',
    persona: ['newFounder'],
    section: 'spinout.week_3.scoring',
    page_target: 'projects.scoring_ready',
    label: 'Ready to run your first venture-readiness score?',
    type: 'toggle',
    importance: 'critical',
    unlock_required: 3,
    explainer: 'Pulls together everything we\'ve learned. We\'ll explain each band.',
    doc_anchor: 'validate/scoring',
  },
];

// ──────────────────────────────────────────────────────────────────────────
// NEW FOUNDER · SPIN-OUT LAB — WEEK 4 · Incorporation & Capital
// ──────────────────────────────────────────────────────────────────────────

const W4: Question[] = [
  {
    id: 'newFounder.w4.incorp.entity_type',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_4.incorp',
    page_target: 'corporate_profiles.entity_type',
    label: 'Entity type you want?',
    type: 'select',
    options: [
      { value: 'c_corp', label: 'Delaware C-Corp (default for VC-track)' },
      { value: 'llc', label: 'LLC' },
      { value: 'ltd', label: 'UK Ltd' },
      { value: 'sas', label: 'French SAS' },
      { value: 'gmbh', label: 'German GmbH' },
      { value: 'other', label: 'Other (we\'ll talk it through)' },
    ],
    importance: 'critical',
    required: true,
    unlock_required: 4,
    explainer: 'If you might raise from US VCs, Delaware C-Corp is the safe default.',
    doc_anchor: 'legal/incorporation',
  },
  {
    id: 'newFounder.w4.incorp.country',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_4.incorp',
    page_target: 'corporate_profiles.incorporation_country',
    label: 'Country of incorporation?',
    type: 'select',
    importance: 'critical',
    required: true,
    unlock_required: 4,
    validate: 'iso2country',
    explainer: 'Not always the country where you live or operate.',
    doc_anchor: 'legal/incorporation',
  },
  {
    id: 'newFounder.w4.incorp.fiscal_year_end',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_4.incorp',
    page_target: 'corporate_profiles.fiscal_year_end',
    label: 'Fiscal year end (MM-DD)?',
    type: 'text',
    importance: 'med',
    unlock_required: 4,
    explainer: '12-31 is the safest default in the US.',
    doc_anchor: 'legal/incorporation',
  },
  {
    id: 'newFounder.w4.captable.founders',
    persona: ['newFounder'],
    section: 'spinout.week_4.captable',
    page_target: 'captable_holders.+',
    label: 'List founders and their equity split (name — %).',
    type: 'textarea',
    importance: 'critical',
    required: true,
    unlock_required: 4,
    explainer: 'Even splits are common for true co-founders. Tweak for risk + commitment differences.',
    doc_anchor: 'capital/captable',
  },
  {
    id: 'newFounder.w4.captable.vesting',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_4.captable',
    page_target: 'captable_holders.vesting',
    label: 'Vesting schedule for founders?',
    type: 'select',
    options: [
      { value: '4y_1y_cliff', label: '4 years, 1-year cliff (standard)' },
      { value: '4y_no_cliff', label: '4 years, no cliff' },
      { value: 'custom', label: 'Custom — we\'ll discuss' },
    ],
    importance: 'critical',
    unlock_required: 4,
    explainer: '4y / 1y cliff is the VC standard.',
    doc_anchor: 'capital/captable',
  },
  {
    id: 'newFounder.w4.captable.option_pool',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_4.captable',
    page_target: 'captable.option_pool_pct',
    label: 'Option pool size at incorporation (%)?',
    type: 'percent',
    importance: 'high',
    unlock_required: 4,
    explainer: '10–15% is common pre-seed. Bigger pool = more dilution of founders pre-raise.',
    doc_anchor: 'capital/captable',
  },
  {
    id: 'newFounder.w4.legal.83b_intent',
    persona: ['newFounder'],
    section: 'spinout.week_4.legal',
    page_target: 'legal_obligations.section_83b',
    label: 'File 83(b) election within 30 days of stock issuance?',
    type: 'toggle',
    importance: 'critical',
    unlock_required: 4,
    explainer: 'Miss this and you\'ll be taxed on every vesting tranche. We\'ll auto-generate the form.',
    doc_anchor: 'legal/section-83b',
  },
  {
    id: 'newFounder.w4.legal.ip_assignment',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_4.legal',
    page_target: 'legal_obligations.ip_assignment',
    label: 'Has every founder & contributor signed an IP assignment / PIIA?',
    type: 'toggle',
    importance: 'critical',
    unlock_required: 4,
    explainer: 'Investors will block until this is in place.',
    doc_anchor: 'legal/ip',
  },
  {
    id: 'newFounder.w4.fundraise.amount',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_4.fundraise',
    page_target: 'rounds.target_amount_usd',
    label: 'How much are you raising in this round (USD)?',
    type: 'currency',
    importance: 'critical',
    unlock_required: 4,
    explainer: 'Tie it to a 18–24 month runway target.',
    doc_anchor: 'capital/capital',
  },
  {
    id: 'newFounder.w4.fundraise.valuation_cap',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_4.fundraise',
    page_target: 'rounds.valuation_cap_usd',
    label: 'Target valuation cap (USD)?',
    type: 'currency',
    importance: 'high',
    unlock_required: 4,
    explainer: 'For SAFEs: the cap converts to ownership at the next priced round.',
    doc_anchor: 'capital/capital',
  },
  {
    id: 'newFounder.w4.fundraise.instrument',
    persona: ['newFounder', 'existingFounder'],
    section: 'spinout.week_4.fundraise',
    page_target: 'rounds.instrument',
    label: 'Instrument for this round?',
    type: 'select',
    options: [
      { value: 'safe_post', label: 'SAFE (post-money)' },
      { value: 'safe_pre', label: 'SAFE (pre-money)' },
      { value: 'convertible_note', label: 'Convertible note' },
      { value: 'priced_round', label: 'Priced round (preferred stock)' },
    ],
    importance: 'high',
    unlock_required: 4,
    explainer: 'Post-money SAFE is the most common in the US pre-seed/seed.',
    doc_anchor: 'capital/capital',
  },
];

// ──────────────────────────────────────────────────────────────────────────
// EXISTING FOUNDER — BUILD section
// ──────────────────────────────────────────────────────────────────────────

const EX_BUILD: Question[] = [
  {
    id: 'existingFounder.build.pipeline.stage_1',
    persona: ['existingFounder'],
    section: 'build.pipeline',
    page_target: 'pipeline_stages.+',
    label: 'Name your first deal stage (e.g. "Discovery", "Demo booked")?',
    type: 'text',
    importance: 'high',
    explainer: 'Drives your Pipeline kanban columns.',
    doc_anchor: 'core/pipeline',
  },
  {
    id: 'existingFounder.build.pipeline.deals_in_play',
    persona: ['existingFounder'],
    section: 'build.pipeline',
    page_target: 'deals.count_active',
    label: 'How many deals are currently active in your pipeline?',
    type: 'number',
    min: 0,
    importance: 'high',
    explainer: 'Sanity check for pipeline coverage.',
    doc_anchor: 'core/pipeline',
  },
  {
    id: 'existingFounder.build.pipeline.avg_cycle',
    persona: ['existingFounder'],
    section: 'build.pipeline',
    page_target: 'deals.avg_cycle_days',
    label: 'Average sales-cycle length in days?',
    type: 'number',
    importance: 'high',
    explainer: 'Used in fundraise + capital-need projections.',
    doc_anchor: 'core/pipeline',
  },
  {
    id: 'existingFounder.build.pipeline.win_rate',
    persona: ['existingFounder'],
    section: 'build.pipeline',
    page_target: 'deals.win_rate_pct',
    label: 'Current win rate (%)?',
    type: 'percent',
    validate: 'percent_0_100',
    importance: 'high',
    explainer: 'For B2B SaaS, 15–25% is typical at qualified-lead stage.',
    doc_anchor: 'core/pipeline',
  },
  {
    id: 'existingFounder.build.studioops.cadence',
    persona: ['existingFounder'],
    section: 'build.studioops',
    page_target: 'studioops.cadence',
    label: 'What\'s your weekly operating cadence (standups, reviews, retros)?',
    type: 'textarea',
    importance: 'med',
    explainer: 'We turn this into a recurring Studio Ops template.',
    doc_anchor: 'core/studio-ops',
  },
  {
    id: 'existingFounder.build.studioops.team_size',
    persona: ['existingFounder'],
    section: 'build.studioops',
    page_target: 'projects.team_size',
    label: 'Team size today (people, not FTE)?',
    type: 'number',
    min: 1,
    importance: 'high',
    explainer: 'Drives burn estimates and process recommendations.',
    doc_anchor: 'core/studio-ops',
  },
  {
    id: 'existingFounder.build.studioops.next_hire',
    persona: ['existingFounder'],
    section: 'build.studioops',
    page_target: 'studioops.next_hires_json',
    label: 'Next 3 hires in order of priority?',
    type: 'textarea',
    importance: 'high',
    explainer: 'Investors will ask this. Have an answer.',
    doc_anchor: 'core/studio-ops',
  },
  {
    id: 'existingFounder.build.brand.landing_url',
    persona: ['existingFounder'],
    section: 'build.brand',
    page_target: 'projects.landing_url',
    label: 'Landing-page URL?',
    type: 'url',
    validate: 'url',
    importance: 'med',
    explainer: 'We\'ll scan it for Lighthouse + SEO basics.',
    doc_anchor: 'core/brand-builder',
  },
  {
    id: 'existingFounder.build.brand.headline',
    persona: ['existingFounder'],
    section: 'build.brand',
    page_target: 'projects.landing_headline',
    label: 'Landing-page H1?',
    type: 'text',
    importance: 'med',
    explainer: 'Should pass the "5-second test": is the offer clear?',
    doc_anchor: 'core/brand-builder',
  },
  {
    id: 'existingFounder.build.deck.slide_problem',
    persona: ['existingFounder'],
    section: 'build.deck',
    page_target: 'deck_slides.problem',
    label: 'Problem slide — your sharpest single line?',
    type: 'textarea',
    importance: 'high',
    explainer: 'Specific > universal. Cost > nuisance.',
    doc_anchor: 'core/pitch-deck',
  },
  {
    id: 'existingFounder.build.deck.slide_solution',
    persona: ['existingFounder'],
    section: 'build.deck',
    page_target: 'deck_slides.solution',
    label: 'Solution slide — what does the product do in plain terms?',
    type: 'textarea',
    importance: 'high',
    explainer: 'Show, don\'t tell. One product screenshot if you have it.',
    doc_anchor: 'core/pitch-deck',
  },
  {
    id: 'existingFounder.build.deck.slide_traction',
    persona: ['existingFounder'],
    section: 'build.deck',
    page_target: 'deck_slides.traction',
    label: 'Traction slide — single most impressive number?',
    type: 'textarea',
    importance: 'high',
    explainer: 'Revenue > paying customers > active users > waitlist.',
    doc_anchor: 'core/pitch-deck',
  },
  {
    id: 'existingFounder.build.deck.slide_team',
    persona: ['existingFounder'],
    section: 'build.deck',
    page_target: 'deck_slides.team',
    label: 'Team slide — why your team specifically?',
    type: 'textarea',
    importance: 'high',
    explainer: 'Founder/market fit is the single biggest signal.',
    doc_anchor: 'core/pitch-deck',
  },
  {
    id: 'existingFounder.build.deck.slide_ask',
    persona: ['existingFounder'],
    section: 'build.deck',
    page_target: 'deck_slides.ask',
    label: 'Ask slide — amount, use of funds, expected runway?',
    type: 'textarea',
    importance: 'high',
    explainer: 'Be precise. "$X for 18 months to reach $Y ARR and Z hires".',
    doc_anchor: 'core/pitch-deck',
  },
  {
    id: 'existingFounder.build.financials.mrr',
    persona: ['existingFounder'],
    section: 'build.financials',
    page_target: 'financials.mrr_usd',
    label: 'Current MRR (USD)?',
    type: 'currency',
    importance: 'critical',
    evidence: 'required',
    explainer: 'Connect Stripe for verified MRR. Self-reported caps your evidence-confidence score.',
    doc_anchor: 'core/financials',
  },
  {
    id: 'existingFounder.build.financials.arr',
    persona: ['existingFounder'],
    section: 'build.financials',
    page_target: 'financials.arr_usd',
    label: 'ARR (USD)?',
    type: 'currency',
    importance: 'high',
    evidence: 'required',
    explainer: 'Should be ≈ MRR × 12. Mismatches flag for review.',
    doc_anchor: 'core/financials',
  },
  {
    id: 'existingFounder.build.financials.gross_margin',
    persona: ['existingFounder'],
    section: 'build.financials',
    page_target: 'financials.gross_margin_pct',
    label: 'Gross margin (%)?',
    type: 'percent',
    validate: 'percent_0_100',
    importance: 'high',
    explainer: 'Software 70%+, marketplaces 15-25%, services 30-50%.',
    doc_anchor: 'core/financials',
  },
  {
    id: 'existingFounder.build.financials.burn',
    persona: ['existingFounder'],
    section: 'build.financials',
    page_target: 'financials.monthly_burn_usd',
    label: 'Monthly burn (USD)?',
    type: 'currency',
    importance: 'critical',
    evidence: 'required',
    explainer: 'Net burn = cash out − cash in.',
    doc_anchor: 'core/financials',
  },
  {
    id: 'existingFounder.build.financials.cash_in_bank',
    persona: ['existingFounder'],
    section: 'build.financials',
    page_target: 'financials.cash_in_bank_usd',
    label: 'Cash in bank (USD)?',
    type: 'currency',
    importance: 'critical',
    evidence: 'required',
    explainer: 'Connect Plaid / Stripe Treasury for verified balance.',
    doc_anchor: 'core/financials',
  },
  {
    id: 'existingFounder.build.financials.runway',
    persona: ['existingFounder'],
    section: 'build.financials',
    page_target: 'financials.runway_months',
    label: 'Runway in months (cash / burn)?',
    type: 'number',
    importance: 'critical',
    explainer: 'We auto-calculate but you can override if revenue offsets burn.',
    doc_anchor: 'core/financials',
  },
  {
    id: 'existingFounder.build.financials.customers_paying',
    persona: ['existingFounder'],
    section: 'build.financials',
    page_target: 'financials.paying_customers',
    label: 'Number of paying customers?',
    type: 'number',
    importance: 'critical',
    evidence: 'recommended',
    explainer: 'For B2B, 10 logos > 1,000 free users.',
    doc_anchor: 'core/financials',
  },
  {
    id: 'existingFounder.build.financials.concentration',
    persona: ['existingFounder'],
    section: 'build.financials',
    page_target: 'financials.top5_concentration_pct',
    label: 'Top-5 customer concentration (% of revenue)?',
    type: 'percent',
    importance: 'high',
    explainer: 'Over 50% is a flag for investors. Mitigation plan?',
    doc_anchor: 'core/financials',
  },
  {
    id: 'existingFounder.build.financials.cac',
    persona: ['existingFounder'],
    section: 'build.financials',
    page_target: 'financials.cac_usd',
    label: 'Blended CAC (USD)?',
    type: 'currency',
    importance: 'high',
    explainer: '(Sales+Marketing spend) ÷ new customers.',
    doc_anchor: 'core/financials',
  },
  {
    id: 'existingFounder.build.financials.ltv',
    persona: ['existingFounder'],
    section: 'build.financials',
    page_target: 'financials.ltv_usd',
    label: 'LTV (USD)?',
    type: 'currency',
    importance: 'high',
    explainer: 'ARPU × gross margin × (1 / monthly churn rate).',
    doc_anchor: 'core/financials',
  },
  {
    id: 'existingFounder.build.financials.churn',
    persona: ['existingFounder'],
    section: 'build.financials',
    page_target: 'financials.monthly_churn_pct',
    label: 'Monthly logo churn (%)?',
    type: 'percent',
    validate: 'percent_0_100',
    importance: 'high',
    explainer: 'B2B SaaS healthy < 2%/mo. Marketplaces vary.',
    doc_anchor: 'core/financials',
  },
  {
    id: 'existingFounder.build.financials.nrr',
    persona: ['existingFounder'],
    section: 'build.financials',
    page_target: 'financials.nrr_pct',
    label: 'Net revenue retention (NRR %)?',
    type: 'percent',
    importance: 'high',
    explainer: 'Above 110% is best-in-class SaaS.',
    doc_anchor: 'core/financials',
  },
  {
    id: 'existingFounder.build.metrics.dau',
    persona: ['existingFounder'],
    section: 'build.metrics',
    page_target: 'metrics_snapshots.dau',
    label: 'Daily active users today?',
    type: 'number',
    importance: 'high',
    evidence: 'recommended',
    explainer: 'Connect Google Analytics for verified DAU.',
    doc_anchor: 'core/metrics',
  },
  {
    id: 'existingFounder.build.metrics.wau',
    persona: ['existingFounder'],
    section: 'build.metrics',
    page_target: 'metrics_snapshots.wau',
    label: 'Weekly active users?',
    type: 'number',
    importance: 'med',
    explainer: 'DAU/WAU ratio shows stickiness.',
    doc_anchor: 'core/metrics',
  },
  {
    id: 'existingFounder.build.metrics.activation_rate',
    persona: ['existingFounder'],
    section: 'build.metrics',
    page_target: 'metrics_snapshots.activation_pct',
    label: 'Activation rate (% who hit your "aha" event)?',
    type: 'percent',
    importance: 'high',
    explainer: 'Define the event clearly in your roadmap.',
    doc_anchor: 'core/metrics',
  },
  {
    id: 'existingFounder.build.metrics.time_to_value',
    persona: ['existingFounder'],
    section: 'build.metrics',
    page_target: 'metrics_snapshots.time_to_value_min',
    label: 'Median time-to-first-value (minutes from signup)?',
    type: 'number',
    importance: 'med',
    explainer: 'Under 10 minutes is excellent for self-serve.',
    doc_anchor: 'core/metrics',
  },
];

// ──────────────────────────────────────────────────────────────────────────
// EXISTING FOUNDER — CAPITAL / LEGAL / NETWORK
// ──────────────────────────────────────────────────────────────────────────

const EX_CAPITAL: Question[] = [
  {
    id: 'existingFounder.capital.round.stage',
    persona: ['existingFounder'],
    section: 'capital.round',
    page_target: 'rounds.stage',
    label: 'Stage of the round you\'re raising?',
    type: 'select',
    options: STAGES,
    importance: 'critical',
    explainer: 'Drives investor matching.',
    doc_anchor: 'capital/capital',
  },
  {
    id: 'existingFounder.capital.round.lead_status',
    persona: ['existingFounder'],
    section: 'capital.round',
    page_target: 'rounds.has_lead',
    label: 'Do you have a lead investor committed?',
    type: 'toggle',
    importance: 'high',
    explainer: 'A lead unlocks the rest of the round.',
    doc_anchor: 'capital/capital',
  },
  {
    id: 'existingFounder.capital.round.use_of_funds',
    persona: ['existingFounder'],
    section: 'capital.round',
    page_target: 'rounds.use_of_funds',
    label: 'Use of funds breakdown (% to team / product / GTM / other)?',
    type: 'textarea',
    importance: 'high',
    explainer: 'Investors will redo your math. Get it right.',
    doc_anchor: 'capital/capital',
  },
  {
    id: 'existingFounder.capital.round.milestones',
    persona: ['existingFounder'],
    section: 'capital.round',
    page_target: 'rounds.milestones',
    label: 'What 3 milestones do you expect to hit with this raise?',
    type: 'textarea',
    importance: 'high',
    explainer: 'These become the next-round narrative.',
    doc_anchor: 'capital/capital',
  },
  {
    id: 'existingFounder.capital.captable.snapshot',
    persona: ['existingFounder'],
    section: 'capital.captable',
    page_target: 'captable.snapshot_url_or_carta',
    label: 'Upload current cap table or paste Carta link.',
    type: 'file',
    importance: 'critical',
    explainer: 'Carta integration auto-syncs. Otherwise upload a current PDF.',
    doc_anchor: 'capital/captable',
  },
  {
    id: 'existingFounder.capital.captable.outstanding_safes',
    persona: ['existingFounder'],
    section: 'capital.captable',
    page_target: 'captable.outstanding_safes_usd',
    label: 'Outstanding SAFE / convertible amount (USD)?',
    type: 'currency',
    importance: 'critical',
    explainer: 'Run a waterfall with us to see priced-round dilution.',
    doc_anchor: 'capital/captable',
  },
  {
    id: 'existingFounder.capital.captable.mfn',
    persona: ['existingFounder'],
    section: 'capital.captable',
    page_target: 'captable.has_mfn_flags',
    label: 'Any MFN (most-favored-nation) clauses in existing SAFEs?',
    type: 'toggle',
    importance: 'high',
    explainer: 'MFN can ratchet up early-investor terms — important for pricing the next round.',
    doc_anchor: 'capital/captable',
  },
  {
    id: 'existingFounder.capital.reserves.target',
    persona: ['existingFounder'],
    section: 'capital.reserves',
    page_target: 'reserves.target_followon_pct',
    label: 'Target follow-on reserve (%) of round size?',
    type: 'percent',
    importance: 'med',
    explainer: 'Investor side — for founder, this is more about understanding their model.',
    doc_anchor: 'capital/reserves',
  },
];

const EX_LEGAL: Question[] = [
  {
    id: 'existingFounder.legal.incorp.confirmed',
    persona: ['existingFounder'],
    section: 'legal.incorp',
    page_target: 'corporate_profiles.confirmed',
    label: 'Is the company already incorporated?',
    type: 'toggle',
    importance: 'critical',
    explainer: 'If not, run the Incorporate flow first.',
    doc_anchor: 'legal/incorporation',
  },
  {
    id: 'existingFounder.legal.cofounder_agreement',
    persona: ['existingFounder'],
    section: 'legal.cofounder',
    page_target: 'legal_obligations.cofounder_agreement',
    label: 'Co-founder agreement signed (equity, vesting, IP, decisions)?',
    type: 'toggle',
    importance: 'critical',
    explainer: 'Lock this BEFORE the first dollar enters.',
    doc_anchor: 'legal/cofounder-agreement',
  },
  {
    id: 'existingFounder.legal.83b_filed',
    persona: ['existingFounder'],
    section: 'legal.83b',
    page_target: 'legal_obligations.section_83b',
    label: 'All founders filed 83(b) within 30 days of issuance?',
    type: 'toggle',
    importance: 'critical',
    explainer: 'If anyone missed it, raise the alarm — it\'s often fixable but only fast.',
    doc_anchor: 'legal/section-83b',
  },
  {
    id: 'existingFounder.legal.ip_assignment',
    persona: ['existingFounder'],
    section: 'legal.ip',
    page_target: 'legal_obligations.ip_assignment',
    label: 'PIIA / IP assignment signed by every founder + contributor?',
    type: 'toggle',
    importance: 'critical',
    explainer: 'Includes contractors and anyone who touched the code.',
    doc_anchor: 'legal/ip',
  },
  {
    id: 'existingFounder.legal.privacy_policy',
    persona: ['existingFounder'],
    section: 'legal.compliance',
    page_target: 'legal_obligations.privacy_policy',
    label: 'Published privacy policy + terms of service?',
    type: 'toggle',
    importance: 'high',
    explainer: 'Required for GDPR / CCPA exposure and for app stores.',
    doc_anchor: 'legal/compliance',
  },
  {
    id: 'existingFounder.legal.data_residency',
    persona: ['existingFounder'],
    section: 'legal.compliance',
    page_target: 'legal_obligations.data_residency_country',
    label: 'Where does customer data physically live?',
    type: 'select',
    importance: 'med',
    validate: 'iso2country',
    explainer: 'Material for EU customers and regulated verticals.',
    doc_anchor: 'legal/compliance',
  },
  {
    id: 'existingFounder.legal.insurance_eo',
    persona: ['existingFounder'],
    section: 'legal.compliance',
    page_target: 'legal_obligations.insurance_eo',
    label: 'E&O insurance carrier + coverage limit?',
    type: 'text',
    importance: 'med',
    explainer: 'Often a customer-procurement requirement.',
    doc_anchor: 'legal/compliance',
  },
  {
    id: 'existingFounder.legal.insurance_do',
    persona: ['existingFounder'],
    section: 'legal.compliance',
    page_target: 'legal_obligations.insurance_do',
    label: 'D&O insurance in place?',
    type: 'toggle',
    importance: 'low',
    explainer: 'Often required once you take institutional capital.',
    doc_anchor: 'legal/compliance',
  },
];

const EX_NETWORK: Question[] = [
  {
    id: 'existingFounder.network.partner_needs',
    persona: ['existingFounder'],
    section: 'network.partners',
    page_target: 'needs.+',
    label: 'What kind of partner do you need most? (pick top 2)',
    type: 'multiselect',
    options: [
      { value: 'design', label: 'Design partner' },
      { value: 'distribution', label: 'Distribution / channel' },
      { value: 'technical_dd', label: 'Technical DD' },
      { value: 'regulatory', label: 'Regulatory / legal' },
      { value: 'recruiting', label: 'Recruiting' },
      { value: 'fundraising_advisor', label: 'Fundraising advisor' },
      { value: 'marketing', label: 'Marketing / PR' },
      { value: 'data', label: 'Data / ML' },
    ],
    importance: 'high',
    sentiment_eligible: true,
    explainer: 'We match you with operating partners and mentors on the platform.',
    doc_anchor: 'network/partners',
  },
  {
    id: 'existingFounder.network.marketplace_listings',
    persona: ['existingFounder'],
    section: 'network.marketplace',
    page_target: 'marketplace_listings.+',
    label: 'Do you want to list a service / opportunity on the Marketplace?',
    type: 'textarea',
    importance: 'low',
    tier_required: 'growth',
    explainer: 'e.g. "Looking for a fractional CFO 10h/week — equity OK".',
    doc_anchor: 'network/marketplace',
  },
  {
    id: 'existingFounder.network.comarketing',
    persona: ['existingFounder'],
    section: 'network.comarketing',
    page_target: 'comarketing_pitches.+',
    label: 'Anyone you\'d like to co-market with? (peer venture, partner, channel)',
    type: 'text',
    importance: 'low',
    explainer: 'We\'ll surface mutual-fit suggestions and warm intros.',
    doc_anchor: 'network/co-marketing',
  },
];

// ──────────────────────────────────────────────────────────────────────────
// INVESTOR
// ──────────────────────────────────────────────────────────────────────────

const INV: Question[] = [
  {
    id: 'investor.firm.name',
    persona: ['investor'],
    section: 'investor.firm',
    page_target: 'investor_profiles.firm_name',
    label: 'Firm or fund name? (Type "Independent" if angel.)',
    type: 'text',
    required: true,
    importance: 'critical',
    explainer: 'Visible to founders only once a pairwise NDA is signed.',
    doc_anchor: 'investors/profile',
  },
  {
    id: 'investor.firm.role',
    persona: ['investor'],
    section: 'investor.firm',
    page_target: 'investor_profiles.role_at_firm',
    label: 'Your role at the firm?',
    type: 'select',
    options: [
      { value: 'gp', label: 'General Partner' },
      { value: 'partner', label: 'Partner' },
      { value: 'principal', label: 'Principal' },
      { value: 'associate', label: 'Associate' },
      { value: 'angel', label: 'Angel investor' },
      { value: 'family_office', label: 'Family office' },
      { value: 'corp_dev', label: 'Corporate dev / CVC' },
      { value: 'other', label: 'Other' },
    ],
    importance: 'high',
    explainer: 'Drives decision-making authority signals.',
    doc_anchor: 'investors/profile',
  },
  {
    id: 'investor.firm.aum',
    persona: ['investor'],
    section: 'investor.firm',
    page_target: 'investor_profiles.aum_usd',
    label: 'AUM (USD), if any?',
    type: 'currency',
    importance: 'med',
    pii: true,
    explainer: 'Optional. Used in aggregate analytics only.',
    doc_anchor: 'investors/profile',
  },
  {
    id: 'investor.firm.website',
    persona: ['investor'],
    section: 'investor.firm',
    page_target: 'investor_profiles.firm_website',
    label: 'Firm website?',
    type: 'url',
    validate: 'url',
    importance: 'low',
    explainer: 'Helps founders verify legitimacy.',
    doc_anchor: 'investors/profile',
  },
  {
    id: 'investor.thesis.line',
    persona: ['investor'],
    section: 'investor.thesis',
    page_target: 'investor_profiles.thesis_text',
    label: 'Your investment thesis in one sentence?',
    type: 'textarea',
    max: 280,
    required: true,
    importance: 'critical',
    sentiment_eligible: true,
    explainer: 'Powers founder ↔ investor fit matching.',
    doc_anchor: 'investors/thesis',
  },
  {
    id: 'investor.thesis.must_haves',
    persona: ['investor'],
    section: 'investor.thesis',
    page_target: 'investor_profiles.must_haves',
    label: 'Top 3 things a founder MUST have for you to engage?',
    type: 'textarea',
    importance: 'high',
    explainer: 'e.g. "technical founder", "$10k MRR", "design partner LOI".',
    doc_anchor: 'investors/thesis',
  },
  {
    id: 'investor.thesis.allergies',
    persona: ['investor'],
    section: 'investor.thesis',
    page_target: 'investor_profiles.allergies_text',
    label: 'Hard pass / allergies?',
    type: 'textarea',
    importance: 'high',
    explainer: 'Sectors, geographies, business models you refuse.',
    doc_anchor: 'investors/thesis',
  },
  {
    id: 'investor.scope.sectors',
    persona: ['investor'],
    section: 'investor.scope',
    page_target: 'investor_profiles.sectors_json',
    label: 'Primary sectors you invest in?',
    type: 'multiselect',
    options: SECTORS,
    required: true,
    importance: 'critical',
    explainer: 'Used to route Axal Investor Signals + deal flow.',
    doc_anchor: 'investors/profile',
  },
  {
    id: 'investor.scope.geos',
    persona: ['investor'],
    section: 'investor.scope',
    page_target: 'investor_profiles.geos_json',
    label: 'Geographies you actively invest in?',
    type: 'multiselect',
    options: [
      { value: 'us', label: 'United States' }, { value: 'ca', label: 'Canada' },
      { value: 'mx', label: 'Mexico' }, { value: 'eu', label: 'European Union' },
      { value: 'uk', label: 'United Kingdom' }, { value: 'mena', label: 'MENA' },
      { value: 'apac', label: 'APAC' }, { value: 'india', label: 'India' },
      { value: 'latam', label: 'LATAM' }, { value: 'africa', label: 'Africa' },
      { value: 'global', label: 'Global' },
    ],
    importance: 'high',
    explainer: 'Drives geographic deal-flow filters.',
    doc_anchor: 'investors/profile',
  },
  {
    id: 'investor.scope.stages',
    persona: ['investor'],
    section: 'investor.scope',
    page_target: 'investor_profiles.stages_json',
    label: 'Stages?',
    type: 'multiselect',
    options: STAGES,
    importance: 'critical',
    explainer: 'Drives matching with current Axal projects.',
    doc_anchor: 'investors/profile',
  },
  {
    id: 'investor.tickets.min',
    persona: ['investor'],
    section: 'investor.tickets',
    page_target: 'investor_profiles.ticket_min_usd',
    label: 'Minimum check size (USD)?',
    type: 'currency',
    importance: 'critical',
    explainer: 'Below this we won\'t route deals to you.',
    doc_anchor: 'investors/tickets',
  },
  {
    id: 'investor.tickets.max',
    persona: ['investor'],
    section: 'investor.tickets',
    page_target: 'investor_profiles.ticket_max_usd',
    label: 'Maximum check size (USD)?',
    type: 'currency',
    importance: 'critical',
    explainer: 'Including any follow-on capacity.',
    doc_anchor: 'investors/tickets',
  },
  {
    id: 'investor.tickets.followon_reserve',
    persona: ['investor'],
    section: 'investor.tickets',
    page_target: 'investor_profiles.followon_reserve_pct',
    label: 'Follow-on reserve target (% of fund)?',
    type: 'percent',
    importance: 'high',
    explainer: 'Lets us flag deals where you might want to load up early.',
    doc_anchor: 'investors/tickets',
  },
  {
    id: 'investor.deployment.target_annual',
    persona: ['investor'],
    section: 'investor.deployment',
    page_target: 'investor_profiles.deployment_target_usd',
    label: 'Annual deployment target (USD)?',
    type: 'currency',
    importance: 'high',
    explainer: 'For pacing analytics.',
    doc_anchor: 'investors/deployment',
  },
  {
    id: 'investor.deployment.lead_follow',
    persona: ['investor'],
    section: 'investor.deployment',
    page_target: 'investor_profiles.lead_or_follow',
    label: 'Lead, follow, or both?',
    type: 'select',
    options: [
      { value: 'lead', label: 'Lead only' },
      { value: 'follow', label: 'Follow only' },
      { value: 'both', label: 'Both' },
    ],
    importance: 'high',
    explainer: 'Founders desperately need leads. Tells us where to point you.',
    doc_anchor: 'investors/deployment',
  },
  {
    id: 'investor.deployment.coinvest',
    persona: ['investor'],
    section: 'investor.deployment',
    page_target: 'investor_profiles.coinvest_pref',
    label: 'Open to co-invest on Axal-led deals?',
    type: 'toggle',
    importance: 'med',
    tier_required: 'investor_pro',
    explainer: 'Unlocks right-of-first-look on Axal-led rounds at Institutional tier.',
    doc_anchor: 'investors/coinvest',
  },
  {
    id: 'investor.dd.bar',
    persona: ['investor'],
    section: 'investor.dd',
    page_target: 'investor_profiles.dd_bar_text',
    label: 'What evidence MUST exist for you to commit?',
    type: 'textarea',
    importance: 'high',
    explainer: 'Drives the DD scope on shared diligence cases.',
    doc_anchor: 'investors/diligence',
  },
  {
    id: 'investor.dd.references',
    persona: ['investor'],
    section: 'investor.dd',
    page_target: 'investor_profiles.dd_requires_refs',
    label: 'Do you require founder reference calls before committing?',
    type: 'toggle',
    importance: 'med',
    explainer: 'Default = yes for most institutional investors.',
    doc_anchor: 'investors/diligence',
  },
  {
    id: 'investor.signals.triggers',
    persona: ['investor'],
    section: 'investor.signals',
    page_target: 'investor_profiles.signal_triggers_json',
    label: 'What should trigger an "alert me" on a deal?',
    type: 'multiselect',
    options: [
      { value: 'mrr_gt_10k', label: 'MRR > $10k' },
      { value: 'mrr_gt_100k', label: 'MRR > $100k' },
      { value: 'fund_round_open', label: 'Round opens in my sector' },
      { value: 'design_partner', label: 'Signed design partner' },
      { value: 'second_time_founder', label: 'Repeat founder' },
      { value: 'paying_logos_5', label: '≥ 5 paying logos' },
      { value: 'regulated_market', label: 'Regulated market entry' },
    ],
    importance: 'med',
    explainer: 'We watch every Axal project and ping you on match.',
    doc_anchor: 'investors/signals',
  },
  {
    id: 'investor.portfolio.size',
    persona: ['investor'],
    section: 'investor.portfolio',
    page_target: 'investor_profiles.portfolio_size',
    label: 'Active portfolio company count?',
    type: 'number',
    importance: 'med',
    explainer: 'Helps gauge capacity.',
    doc_anchor: 'investors/portfolio',
  },
  {
    id: 'investor.portfolio.lookalikes',
    persona: ['investor'],
    section: 'investor.portfolio',
    page_target: 'investor_profiles.lookalikes_text',
    label: 'Name 3 of your investments that represent your sweet spot.',
    type: 'textarea',
    importance: 'high',
    sentiment_eligible: true,
    explainer: 'We use embeddings on these to surface lookalike deals.',
    doc_anchor: 'investors/portfolio',
  },
  {
    id: 'investor.partners.needs',
    persona: ['investor'],
    section: 'investor.partners',
    page_target: 'investor_profiles.partner_needs_json',
    label: 'What service partners do you regularly need?',
    type: 'multiselect',
    options: [
      { value: 'tech_dd', label: 'Technical DD' },
      { value: 'mkt_dd', label: 'Commercial DD' },
      { value: 'legal', label: 'Legal counsel' },
      { value: 'tax', label: 'Tax / structuring' },
      { value: 'recruiting', label: 'Recruiting / talent' },
      { value: 'aml_kyc', label: 'AML / KYC service' },
      { value: 'comms', label: 'PR / Comms' },
      { value: 'data', label: 'Data / benchmarks' },
    ],
    importance: 'med',
    explainer: 'We match you with operating partners on the platform.',
    doc_anchor: 'investors/partners',
  },
  {
    id: 'investor.conflicts.disclose',
    persona: ['investor'],
    section: 'investor.conflicts',
    page_target: 'investor_profiles.conflicts_text',
    label: 'Any conflicts of interest we should know about?',
    type: 'textarea',
    importance: 'high',
    explainer: 'Board seats, advisor roles, competing investments — disclose.',
    doc_anchor: 'investors/conflicts',
  },
  {
    id: 'investor.contribute_signals',
    persona: ['investor'],
    section: 'investor.privacy',
    page_target: 'user_settings.contribute_investor_signals',
    label: 'Contribute your anonymised profile to Axal Investor Signals?',
    type: 'toggle',
    importance: 'low',
    explainer: 'Aggregated only. n<5 cells suppressed. Opt out any time.',
    doc_anchor: 'account/privacy',
  },
];

// ──────────────────────────────────────────────────────────────────────────
// OPERATING PARTNER — four flavours
// ──────────────────────────────────────────────────────────────────────────

const OP_COMMON: Question[] = [
  {
    id: 'opPartner.firm.name',
    persona: ['opPartnerCapital', 'opPartnerServices', 'opPartnerSourcing', 'opPartnerMixed'],
    section: 'opPartner.firm',
    page_target: 'partner_profiles.firm_name',
    label: 'Firm or your name (if independent)?',
    type: 'text',
    required: true,
    importance: 'critical',
    explainer: 'Visible to admin and matched founders.',
    doc_anchor: 'partners/profile',
  },
  {
    id: 'opPartner.firm.website',
    persona: ['opPartnerCapital', 'opPartnerServices', 'opPartnerSourcing', 'opPartnerMixed'],
    section: 'opPartner.firm',
    page_target: 'partner_profiles.firm_website',
    label: 'Website?',
    type: 'url',
    validate: 'url',
    importance: 'med',
    explainer: 'For verification + public profile.',
    doc_anchor: 'partners/profile',
  },
  {
    id: 'opPartner.firm.geos',
    persona: ['opPartnerCapital', 'opPartnerServices', 'opPartnerSourcing', 'opPartnerMixed'],
    section: 'opPartner.firm',
    page_target: 'partner_profiles.geos_json',
    label: 'Geographies you operate in?',
    type: 'multiselect',
    options: [
      { value: 'us', label: 'United States' }, { value: 'eu', label: 'EU' },
      { value: 'uk', label: 'UK' }, { value: 'mena', label: 'MENA' },
      { value: 'apac', label: 'APAC' }, { value: 'latam', label: 'LATAM' },
      { value: 'africa', label: 'Africa' }, { value: 'global', label: 'Global' },
    ],
    importance: 'high',
    explainer: 'Matching by geo for compliance + relationship reasons.',
    doc_anchor: 'partners/profile',
  },
  {
    id: 'opPartner.firm.sectors',
    persona: ['opPartnerCapital', 'opPartnerServices', 'opPartnerSourcing', 'opPartnerMixed'],
    section: 'opPartner.firm',
    page_target: 'partner_profiles.sectors_json',
    label: 'Sectors you focus on?',
    type: 'multiselect',
    options: SECTORS,
    importance: 'high',
    explainer: 'Drives founder match.',
    doc_anchor: 'partners/profile',
  },
  {
    id: 'opPartner.conflicts.disclose',
    persona: ['opPartnerCapital', 'opPartnerServices', 'opPartnerSourcing', 'opPartnerMixed'],
    section: 'opPartner.conflicts',
    page_target: 'partner_profiles.conflicts_json',
    label: 'Any conflicts of interest? (competing portfolios, advisor seats, etc.)',
    type: 'textarea',
    importance: 'critical',
    explainer: 'Required disclosure before activating the partnership.',
    doc_anchor: 'partners/conflicts',
  },
  {
    id: 'opPartner.references',
    persona: ['opPartnerCapital', 'opPartnerServices', 'opPartnerSourcing', 'opPartnerMixed'],
    section: 'opPartner.references',
    page_target: 'partner_profiles.references_json',
    label: '2-3 references we can call (name + relationship)?',
    type: 'textarea',
    importance: 'high',
    explainer: 'Axal will reach out only after you accept the deal proposal.',
    doc_anchor: 'partners/references',
  },
];

const OP_SERVICES: Question[] = [
  {
    id: 'opPartner.svc.offerings',
    persona: ['opPartnerServices', 'opPartnerMixed'],
    section: 'opPartner.svc',
    page_target: 'partner_profiles.services_offered_json',
    label: 'Which services can you offer to Axal founders?',
    type: 'multiselect',
    options: [
      { value: 'legal_general', label: 'General counsel' },
      { value: 'legal_ip', label: 'IP / patents' },
      { value: 'tax', label: 'Tax / structuring' },
      { value: 'accounting', label: 'Accounting / bookkeeping' },
      { value: 'cfo_fractional', label: 'Fractional CFO' },
      { value: 'recruiting_exec', label: 'Executive recruiting' },
      { value: 'recruiting_eng', label: 'Engineering recruiting' },
      { value: 'design', label: 'Design / brand' },
      { value: 'gtm', label: 'GTM consulting' },
      { value: 'marketing', label: 'Marketing / PR' },
      { value: 'data', label: 'Data / ML consulting' },
      { value: 'security', label: 'Security / SOC2 prep' },
      { value: 'compliance', label: 'Compliance / regulatory' },
      { value: 'product', label: 'Product consulting' },
      { value: 'sales_ops', label: 'Sales / Revops' },
    ],
    importance: 'critical',
    explainer: 'Drives matching against founder service needs.',
    doc_anchor: 'partners/services',
  },
  {
    id: 'opPartner.svc.rate_card',
    persona: ['opPartnerServices', 'opPartnerMixed'],
    section: 'opPartner.svc',
    page_target: 'partner_profiles.rate_card_json',
    label: 'Rate card or hourly range (USD)?',
    type: 'text',
    importance: 'high',
    explainer: 'Use a range. Axal can negotiate Founder-tier discounts.',
    doc_anchor: 'partners/services',
  },
  {
    id: 'opPartner.svc.discount_for_axal',
    persona: ['opPartnerServices', 'opPartnerMixed'],
    section: 'opPartner.svc',
    page_target: 'partner_profiles.axal_discount_pct',
    label: 'Discount % offered to Axal-tagged founders?',
    type: 'percent',
    importance: 'high',
    explainer: 'Typical accelerator-network discounts run 15–35%.',
    doc_anchor: 'partners/services',
  },
  {
    id: 'opPartner.svc.equity_friendly',
    persona: ['opPartnerServices', 'opPartnerMixed'],
    section: 'opPartner.svc',
    page_target: 'partner_profiles.equity_friendly',
    label: 'Open to taking some equity in lieu of cash?',
    type: 'toggle',
    importance: 'med',
    explainer: 'Helps cash-strapped founders. Equity capped at agreement-defined ceiling.',
    doc_anchor: 'partners/services',
  },
  {
    id: 'opPartner.svc.capacity_hours',
    persona: ['opPartnerServices', 'opPartnerMixed'],
    section: 'opPartner.svc',
    page_target: 'partner_profiles.capacity_hours_week',
    label: 'Capacity in hours/week available for Axal founders?',
    type: 'number',
    importance: 'med',
    explainer: 'Helps us pace matches and avoid overload.',
    doc_anchor: 'partners/services',
  },
  {
    id: 'opPartner.svc.sla',
    persona: ['opPartnerServices', 'opPartnerMixed'],
    section: 'opPartner.svc',
    page_target: 'partner_profiles.sla_text',
    label: 'Response-time SLA you can commit to?',
    type: 'text',
    importance: 'med',
    explainer: 'e.g. "24h for email, 48h for first draft".',
    doc_anchor: 'partners/services',
  },
  {
    id: 'opPartner.svc.insurance',
    persona: ['opPartnerServices', 'opPartnerMixed'],
    section: 'opPartner.svc',
    page_target: 'partner_profiles.insurance_eo',
    label: 'E&O / professional indemnity insurance carrier?',
    type: 'text',
    importance: 'med',
    explainer: 'Required to deliver paid services through Axal Marketplace.',
    doc_anchor: 'partners/insurance',
  },
];

const OP_CAPITAL: Question[] = [
  {
    id: 'opPartner.cap.capacity_min',
    persona: ['opPartnerCapital', 'opPartnerMixed'],
    section: 'opPartner.cap',
    page_target: 'partner_profiles.capital_capacity_min_usd',
    label: 'Minimum capital you can deploy per deal (USD)?',
    type: 'currency',
    importance: 'critical',
    explainer: 'For both LP commitments and co-invest tickets.',
    doc_anchor: 'partners/capital',
  },
  {
    id: 'opPartner.cap.capacity_max',
    persona: ['opPartnerCapital', 'opPartnerMixed'],
    section: 'opPartner.cap',
    page_target: 'partner_profiles.capital_capacity_max_usd',
    label: 'Maximum capital you can deploy per deal (USD)?',
    type: 'currency',
    importance: 'critical',
    explainer: 'Used for round-construction matching.',
    doc_anchor: 'partners/capital',
  },
  {
    id: 'opPartner.cap.vehicle',
    persona: ['opPartnerCapital', 'opPartnerMixed'],
    section: 'opPartner.cap',
    page_target: 'partner_profiles.capital_vehicle',
    label: 'Capital vehicle?',
    type: 'select',
    options: [
      { value: 'personal', label: 'Personal / angel' },
      { value: 'fund', label: 'Fund' },
      { value: 'family_office', label: 'Family office' },
      { value: 'spv', label: 'SPV per deal' },
      { value: 'cvc', label: 'Corporate venture' },
    ],
    importance: 'high',
    explainer: 'Drives the right legal template.',
    doc_anchor: 'partners/capital',
  },
  {
    id: 'opPartner.cap.lp_capacity',
    persona: ['opPartnerCapital', 'opPartnerMixed'],
    section: 'opPartner.cap',
    page_target: 'partner_profiles.lp_capacity_usd',
    label: 'LP capacity into an Axal vehicle (USD)?',
    type: 'currency',
    importance: 'high',
    explainer: 'Optional. Triggers full KYC + Accreditation flow.',
    doc_anchor: 'partners/lp',
  },
  {
    id: 'opPartner.cap.accreditation',
    persona: ['opPartnerCapital', 'opPartnerMixed'],
    section: 'opPartner.cap',
    page_target: 'legal_obligations.accreditation',
    label: 'Are you (or your entity) an accredited investor in your jurisdiction?',
    type: 'toggle',
    importance: 'critical',
    explainer: 'Required for any capital deal. Verified through Trust Center.',
    doc_anchor: 'trust-center/accreditation',
  },
];

const OP_SOURCING: Question[] = [
  {
    id: 'opPartner.src.channels',
    persona: ['opPartnerSourcing', 'opPartnerMixed'],
    section: 'opPartner.src',
    page_target: 'partner_profiles.source_channels_json',
    label: 'Where do you find deal flow?',
    type: 'multiselect',
    options: [
      { value: 'network', label: 'Personal network' },
      { value: 'accelerator', label: 'Accelerator alumni' },
      { value: 'conferences', label: 'Conferences' },
      { value: 'university', label: 'University ecosystem' },
      { value: 'community', label: 'Community / Slack / Discord' },
      { value: 'content', label: 'Content / inbound' },
      { value: 'ecosystem_partner', label: 'Ecosystem partners' },
    ],
    importance: 'high',
    explainer: 'Helps Axal pace expected intro volume.',
    doc_anchor: 'partners/sourcing',
  },
  {
    id: 'opPartner.src.volume',
    persona: ['opPartnerSourcing', 'opPartnerMixed'],
    section: 'opPartner.src',
    page_target: 'partner_profiles.intros_per_quarter',
    label: 'Realistic qualified intros per quarter?',
    type: 'number',
    importance: 'high',
    explainer: 'Sets the minimum for the deal-sourcing partnership.',
    doc_anchor: 'partners/sourcing',
  },
  {
    id: 'opPartner.src.exclusivity',
    persona: ['opPartnerSourcing', 'opPartnerMixed'],
    section: 'opPartner.src',
    page_target: 'partner_profiles.exclusive_to_axal',
    label: 'Will these intros be exclusive to Axal?',
    type: 'select',
    options: [
      { value: 'exclusive', label: 'Yes — exclusive' },
      { value: 'right_of_first', label: 'Right of first look' },
      { value: 'non_exclusive', label: 'Non-exclusive' },
    ],
    importance: 'high',
    explainer: 'Drives the rev-share + fee economics.',
    doc_anchor: 'partners/sourcing',
  },
  {
    id: 'opPartner.src.revshare_pref',
    persona: ['opPartnerSourcing', 'opPartnerMixed'],
    section: 'opPartner.src',
    page_target: 'partner_profiles.preferred_revshare_pct',
    label: 'Preferred finder fee or rev-share (%)?',
    type: 'percent',
    importance: 'high',
    explainer: 'Industry typical 2–5% of first-round capital. Negotiable.',
    doc_anchor: 'partners/sourcing',
  },
];

const OP_PREFERENCES: Question[] = [
  {
    id: 'opPartner.deal.types_interest',
    persona: ['opPartnerCapital', 'opPartnerServices', 'opPartnerSourcing', 'opPartnerMixed'],
    section: 'opPartner.deal',
    page_target: 'partner_profiles.deal_types_interest_json',
    label: 'Which deal types interest you?',
    type: 'multiselect',
    options: [
      { value: 'equity_for_platform', label: 'Equity for platform access' },
      { value: 'services_for_access', label: 'Services for access' },
      { value: 'deal_sourcing', label: 'Deal-sourcing revshare' },
      { value: 'capital', label: 'Capital partnership (LP / co-invest)' },
      { value: 'custom', label: 'Custom' },
    ],
    importance: 'high',
    explainer: 'Drives the proposal shape we generate after meeting.',
    doc_anchor: 'partners/deals',
  },
  {
    id: 'opPartner.deal.term_months',
    persona: ['opPartnerCapital', 'opPartnerServices', 'opPartnerSourcing', 'opPartnerMixed'],
    section: 'opPartner.deal',
    page_target: 'partner_profiles.preferred_term_months',
    label: 'Preferred term length (months)?',
    type: 'number',
    importance: 'med',
    explainer: '12–24 months is common.',
    doc_anchor: 'partners/deals',
  },
  {
    id: 'opPartner.deal.demand_view',
    persona: ['opPartnerCapital', 'opPartnerServices', 'opPartnerSourcing', 'opPartnerMixed'],
    section: 'opPartner.deal',
    page_target: 'partner_profiles.demand_view',
    label: 'What demand do you see in the Axal ecosystem you want to serve?',
    type: 'textarea',
    importance: 'med',
    sentiment_eligible: true,
    explainer: 'We use this to align you with founder needs in Demand & Supply Atlas.',
    doc_anchor: 'partners/demand',
  },
];

// ──────────────────────────────────────────────────────────────────────────
// MENTOR
// ──────────────────────────────────────────────────────────────────────────

const MEN: Question[] = [
  {
    id: 'mentor.about.expertise_tags',
    persona: ['mentor'],
    section: 'mentor.expertise',
    page_target: 'mentor_profiles.tags_json',
    label: 'Your expertise areas (pick up to 6)?',
    type: 'multiselect',
    options: [
      { value: 'enterprise_sales', label: 'Enterprise sales' },
      { value: 'plg', label: 'Product-led growth' },
      { value: 'paid_acquisition', label: 'Paid acquisition' },
      { value: 'community', label: 'Community' },
      { value: 'devrel', label: 'DevRel' },
      { value: 'hiring', label: 'Hiring' },
      { value: 'fundraising', label: 'Fundraising' },
      { value: 'pricing', label: 'Pricing & packaging' },
      { value: 'compliance', label: 'Compliance / regulatory' },
      { value: 'design', label: 'Design / UX' },
      { value: 'ml', label: 'ML / data' },
      { value: 'mobile', label: 'Mobile' },
      { value: 'infra', label: 'Infrastructure' },
      { value: 'ops', label: 'Operations / scaling' },
      { value: 'gov_relations', label: 'Government relations' },
      { value: 'media', label: 'Media / PR' },
    ],
    required: true,
    importance: 'critical',
    explainer: 'Drives founder matching and search.',
    doc_anchor: 'mentors/profile',
  },
  {
    id: 'mentor.about.sectors',
    persona: ['mentor'],
    section: 'mentor.expertise',
    page_target: 'mentor_profiles.sectors_json',
    label: 'Sectors you mentor in?',
    type: 'multiselect',
    options: SECTORS,
    importance: 'high',
    explainer: 'Pair with expertise tags for tight matching.',
    doc_anchor: 'mentors/profile',
  },
  {
    id: 'mentor.about.stages',
    persona: ['mentor'],
    section: 'mentor.expertise',
    page_target: 'mentor_profiles.stages_json',
    label: 'Stages you\'re best for?',
    type: 'multiselect',
    options: STAGES,
    importance: 'high',
    explainer: 'Pre-seed mentors are different from Series A mentors.',
    doc_anchor: 'mentors/profile',
  },
  {
    id: 'mentor.about.capacity',
    persona: ['mentor'],
    section: 'mentor.capacity',
    page_target: 'mentor_profiles.weekly_capacity_hours',
    label: 'Hours per week you can commit?',
    type: 'number',
    min: 0,
    max: 40,
    importance: 'high',
    explainer: 'Drives slot-availability calculations.',
    doc_anchor: 'mentors/capacity',
  },
  {
    id: 'mentor.about.languages',
    persona: ['mentor'],
    section: 'mentor.capacity',
    page_target: 'mentor_profiles.languages_json',
    label: 'Languages you can mentor in?',
    type: 'multiselect',
    options: [
      { value: 'en', label: 'English' }, { value: 'fr', label: 'French' },
      { value: 'es', label: 'Spanish' }, { value: 'pt', label: 'Portuguese' },
      { value: 'de', label: 'German' }, { value: 'ar', label: 'Arabic' },
      { value: 'zh', label: 'Mandarin' }, { value: 'ja', label: 'Japanese' },
      { value: 'hi', label: 'Hindi' },
    ],
    importance: 'med',
    explainer: 'Helps non-anglophone founders find you.',
    doc_anchor: 'mentors/profile',
  },
  {
    id: 'mentor.comp.preference',
    persona: ['mentor'],
    section: 'mentor.comp',
    page_target: 'mentor_profiles.comp_preference',
    label: 'Compensation preference?',
    type: 'select',
    options: [
      { value: 'probono', label: 'Pro bono' },
      { value: 'equity', label: 'Equity (advisor grants)' },
      { value: 'cash', label: 'Cash' },
      { value: 'mixed', label: 'Mixed cash + equity' },
    ],
    importance: 'high',
    explainer: 'Drives the engagement contract template.',
    doc_anchor: 'mentors/compensation',
  },
  {
    id: 'mentor.comp.equity_range',
    persona: ['mentor'],
    section: 'mentor.comp',
    page_target: 'mentor_profiles.equity_pct_range',
    label: 'If equity: typical advisor-grant range (% range)?',
    type: 'text',
    importance: 'med',
    explainer: '0.1%–1% is the typical FAST template range.',
    doc_anchor: 'mentors/compensation',
  },
  {
    id: 'mentor.declines',
    persona: ['mentor'],
    section: 'mentor.scope',
    page_target: 'mentor_profiles.declines_text',
    label: 'Topics you won\'t advise on?',
    type: 'textarea',
    importance: 'med',
    explainer: 'Helps Axal avoid bad-fit matches.',
    doc_anchor: 'mentors/scope',
  },
  {
    id: 'mentor.references',
    persona: ['mentor'],
    section: 'mentor.references',
    page_target: 'mentor_profiles.references_text',
    label: '2-3 founders or operators we can reference-check?',
    type: 'textarea',
    importance: 'high',
    explainer: 'Quietly contacted only with your consent.',
    doc_anchor: 'mentors/references',
  },
  {
    id: 'mentor.calendar.provider',
    persona: ['mentor'],
    section: 'mentor.calendar',
    page_target: 'mentor_profiles.calendar_provider',
    label: 'Calendar provider for booking?',
    type: 'select',
    options: [
      { value: 'calendly', label: 'Calendly' },
      { value: 'google', label: 'Google Calendar' },
      { value: 'outlook', label: 'Outlook' },
      { value: 'savvycal', label: 'SavvyCal' },
      { value: 'manual', label: 'I\'ll handle it manually' },
    ],
    importance: 'high',
    explainer: 'Connects via Integrations so founders can self-book.',
    doc_anchor: 'mentors/calendar',
  },
];

// ──────────────────────────────────────────────────────────────────────────
// Export the assembled bank.
// ──────────────────────────────────────────────────────────────────────────

export const QUESTION_BANK: Question[] = [
  ...W1, ...W2, ...W3, ...W4,
  ...EX_BUILD, ...EX_CAPITAL, ...EX_LEGAL, ...EX_NETWORK,
  ...INV,
  ...OP_COMMON, ...OP_SERVICES, ...OP_CAPITAL, ...OP_SOURCING, ...OP_PREFERENCES,
  ...MEN,
];

export function questionsForPersona(p: Persona, opts: {
  week?: SpinoutWeek;
  tier?: TierKey;
  section?: string;
} = {}): Question[] {
  return QUESTION_BANK.filter(q => {
    if (!q.persona.includes(p)) return false;
    if (q.unlock_required && opts.week && q.unlock_required > opts.week) return false;
    if (q.section && opts.section && !q.section.startsWith(opts.section)) return false;
    return true;
  });
}

export function questionById(id: string): Question | undefined {
  return QUESTION_BANK.find(q => q.id === id);
}

export const PERSONAS_ALL: Persona[] = [
  'newFounder', 'existingFounder', 'investor',
  'opPartnerCapital', 'opPartnerServices', 'opPartnerSourcing', 'opPartnerMixed',
  'mentor',
];
