-- Task #2 (AR) — Persona Banks + Spin-Out Week Gating.
--
-- Documentation-only / no-op migration.
--
-- The advisor's week-gated bank reads `users.spinout_lab_week`.
-- This column was already added to the live D1 database before this
-- migration was numbered, via:
--   wrangler d1 execute studioos-db --remote \
--     --command "ALTER TABLE users ADD COLUMN spinout_lab_week INTEGER DEFAULT 1"
--
-- D1/SQLite has no `ALTER TABLE ... ADD COLUMN IF NOT EXISTS`, so
-- including a raw ALTER here would fail on prod with `duplicate
-- column name` and roll the whole file back. To keep the migration
-- runner clean on every environment, this file is intentionally a
-- no-op (`SELECT 1`).
--
-- For fresh D1/SQLite instances, the worker's
-- `ensureAdvisorWeekColumn()` helper (cloudflare-worker/src/routes/
-- advisor.ts) performs a lazy `PRAGMA table_info(users)` check on
-- the first /advisor request and runs the ALTER if the column is
-- missing. Local pytest fixtures and dev SQLite are also covered
-- by that helper.

SELECT 1;
