-- 180 — advisor organization, which the advisor writes, reads back, and never had.
--
-- `writeRouter` handles three role-detection answers the same way: it writes
-- the value, then a later read decides whether to ask the question again.
-- `role`, `headline` and `bio` all exist. `organization` never did, and the
-- damage compounds:
--
--   the write   had nowhere to persist the answer and returned a noop.
--
--   the read    `SELECT organization, headline FROM users` throws on the first
--               unknown column, so the whole row comes back null. That is the
--               expensive part: `headline` is stored correctly, but its
--               answered-check rides on the same SELECT, so BOTH questions are
--               marked unanswered forever.
--
-- Net effect: the advisor asks a founder for their organisation, discards the
-- answer, tells them it is remembered, and asks again next session — and asks
-- for their headline again too, despite having stored it.
--
-- `users` is already at D1's 100-column limit in production. Per-user extension
-- fields therefore live in the existing one-to-one `user_profile_ext` sidecar
-- (migration 131), rather than adding another column to `users`.

ALTER TABLE user_profile_ext ADD COLUMN organization TEXT;
