-- 180 — users.organization, which the advisor writes, reads back, and never had.
--
-- `writeRouter` handles three role-detection answers the same way: it writes
-- the value to a `users` column, then a later read decides whether to ask the
-- question again. `role`, `headline` and `bio` all exist. `organization` never
-- did, and the damage compounds:
--
--   the write   `UPDATE users SET organization = ?` throws into its catch,
--               which returns { status: 'noop', hint: 'organization column not
--               available; remembered for later.' } — and nothing remembers it.
--
--   the read    `SELECT organization, headline FROM users` throws on the first
--               unknown column, so the whole row comes back null. That is the
--               expensive part: `headline` is stored correctly, but its
--               answered-check rides on the same SELECT, so BOTH questions are
--               marked unanswered forever.
--
-- Net effect: the advisor asks a founder for their organisation, discards the
-- answer, tells them it is remembered, and asks again next session — and asks
-- for their headline again too, despite having stored it.
--
-- Added rather than removed because the intent is unambiguous: the question is
-- authored, the write is authored, the read is authored, and the two sibling
-- columns beside it work.

ALTER TABLE users ADD COLUMN organization TEXT;
