-- 229 — sector market taxonomy for Research · Markets.
-- Counts are discovery-universe counts supplied by Axal, not TAM or valuation.
CREATE TABLE IF NOT EXISTS research_market_directory (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  company_count INTEGER NOT NULL,
  source_name TEXT NOT NULL,
  source_boundary TEXT NOT NULL,
  as_of TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_research_market_directory_name ON research_market_directory(name);
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('advertising','Advertising',488,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('agtech','AgTech',724,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('ai','AI',3083,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('analytics','Analytics',967,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('ar-vr','AR/VR',414,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('audiotech','AudioTech',45,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('autotech','AutoTech',170,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('biotech','BioTech',1168,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('chemicals','Chemicals',69,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('climatetech-cleantech','ClimateTech/CleanTech',1662,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('cloud-infrastructure','Cloud Infrastructure',955,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('constructiontech','ConstructionTech',233,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('consumer-health','Consumer Health',1038,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('consumer-internet','Consumer Internet',2192,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('cosmetics','Cosmetics',71,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('creator-passion-economy','Creator/Passion Economy',197,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('cybersecurity','Cybersecurity',796,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('data-services','Data Services',728,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('deeptech','DeepTech',828,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('defensetech','DefenseTech',103,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('developer-tools','Developer Tools',818,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('diagnostics','Diagnostics',154,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('digital-health','Digital Health',1163,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('direct-to-consumer-dtc','Direct-to-Consumer (DTC)',288,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('drug-delivery','Drug Delivery',79,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('e-commerce','E-commerce',1915,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('education','Education',1069,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('energytech','EnergyTech',673,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('enterprise-applications','Enterprise Applications',1098,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('enterprise-infrastructure','Enterprise Infrastructure',325,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('enterprise','Enterprise',2928,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('entertainment-sports','Entertainment & Sports',539,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('fashion','Fashion',242,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('fintech','FinTech',3800,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('food-and-beverage','Food and Beverage',724,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('future-of-work','Future of Work',668,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('games','Games',469,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('gaming-esports','Gaming/eSports',543,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('general-tech','General Tech',44,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('generative-tech-ai','Generative Tech/AI',474,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('gig-economy','Gig Economy',96,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('govtech','GovTech',148,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('hardware','Hardware',529,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('health-hospital-services','Health & Hospital Services',1693,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('health-it','Health IT',1560,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('human-capital-hrtech','Human Capital/HRTech',352,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('impact','Impact',520,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('insurance','Insurance',536,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('iot','IoT',800,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('legaltech','LegalTech',147,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('local-services','Local Services',256,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('lodging-hospitality','Lodging/Hospitality',139,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('logistics','Logistics',558,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('manufacturing','Manufacturing',458,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('marketingtech','MarketingTech',544,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('marketplaces','Marketplaces',1749,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('material-science','Material Science',200,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('media-content','Media/Content',845,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('medical-devices','Medical Devices',473,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('messaging','Messaging',213,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('parenting-families','Parenting/Families',152,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('payments','Payments',730,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('pharmaceuticals','Pharmaceuticals',329,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('real-estate-proptech','Real Estate/PropTech',968,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('retail','Retail',575,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('robotics','Robotics',651,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('saas','SaaS',3151,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('sales-crm','Sales & CRM',436,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('security','Security',500,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('semiconductors','Semiconductors',154,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('smart-cities-urbantech','Smart Cities/UrbanTech',100,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('smb-software','SMB Software',784,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('social-commerce','Social Commerce',467,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('social-networks','Social Networks',1192,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('space','Space',372,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('supply-chain-tech','Supply Chain Tech',282,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('therapeutics','Therapeutics',201,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('transportationtech','TransportationTech',657,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('travel','Travel',297,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('web3-blockchain','Web3/Blockchain',1247,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('web3-crypto','Web3/Crypto',1375,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
INSERT OR IGNORE INTO research_market_directory (slug,name,company_count,source_name,source_boundary,as_of) VALUES ('wellness-fitness','Wellness & Fitness',449,'Axal-provided sector taxonomy','Counts are supplied taxonomy counts for discovery and are not independently verified market-size or company-count claims.','2026-09-30');
