-- 366 — verified public startup offers for the Founder Perks marketplace.
--
-- These are official provider programs researched from their public pages.
-- They intentionally enter the admin queue as in_review: public availability
-- does not establish an Axal partnership, referral relationship, or eligibility.
-- INSERT OR IGNORE makes this safe after the same rows were seeded directly
-- during the initial production import.

INSERT OR IGNORE INTO perks (
  uid, partner_user_id, partner_name, category, offer, blurb, detail,
  kind, credits, required_tier, price_cents, fulfilment, redeem_url,
  claim_cap, status, review_note, featured, company_id, ends_at,
  grant_scope, value_cents, editorial_note
) VALUES
('aws-activate-startup-credits',NULL,'AWS','Cloud & Infrastructure','Up to $200,000 in AWS Activate Credits','Apply for AWS Activate credits to offset eligible AWS infrastructure, data, and AI/ML costs.','Official AWS page states startups can apply for up to $200,000 in AWS Activate Credits; eligibility and award size depend on the program/application. This is an external provider application, not an Axal-issued credit.','credits',0,NULL,NULL,'link','https://aws.amazon.com/startups/join?destination=/credits/apply',NULL,'in_review','Official source verified. Axal partnership, referral status, and founder eligibility require admin confirmation before approval.',0,NULL,NULL,'external_program',20000000,'Source: https://aws.amazon.com/activate/'),
('google-startups-cloud-credits',NULL,'Google Cloud','Cloud & Infrastructure','Up to $350,000 in Google Cloud credits','Cloud credits for eligible startups, including an enhanced amount for AI-first companies.','Google for Startups states pre-funded startups may receive $2,000, Seed to Series A startups $200,000, and AI-first startups up to $350,000, subject to program requirements and application review.','credits',0,NULL,NULL,'link','https://cloud.google.com/startup/apply',NULL,'in_review','Official source verified. Axal partnership and founder eligibility are unconfirmed.',0,NULL,NULL,'external_program',35000000,'Source: https://cloud.google.com/startup'),
('microsoft-for-startups-credits',NULL,'Microsoft','Cloud & Infrastructure','Up to $150,000 in Microsoft for Startups credits','Azure credits plus access to AI tools, developer resources, and startup support.','Microsoft for Startups publicly advertises up to $150,000 in credits. Benefit access and eligibility are handled through the Microsoft for Startups portal.','credits',0,NULL,NULL,'link','https://go.microsoft.com/fwlink/?linkid=2325925&clcid=0x409&culture=en-us&country=us',NULL,'in_review','Official source verified. Axal investor-network status and founder eligibility require admin confirmation.',0,NULL,NULL,'external_program',15000000,'Source: https://www.microsoft.com/en-us/startups'),
('cloudflare-for-startups',NULL,'Cloudflare','Cloud & Infrastructure','Up to $350,000 in Cloudflare credits','Startup tiers provide usage credits plus selected security, networking, support, and technical benefits.','Cloudflare states its program offers $10,000, $100,000, or up to $350,000 in credits depending on funding and eligibility. Credits are valid for one year or until consumed; the program page lists qualification requirements and exclusions.','credits',0,NULL,NULL,'link','https://www.cloudflare.com/lp/startups/',NULL,'in_review','Official source verified. Affiliated-partner status and Axal eligibility require admin confirmation.',0,NULL,NULL,'external_program',35000000,'Source: https://www.cloudflare.com/startups/'),
('mongodb-for-startups-atlas',NULL,'MongoDB','Cloud & Infrastructure','MongoDB Atlas startup credits','Promo credits for eligible early-stage software startups, with technical guidance and a one-on-one expert session.','MongoDB states its base tier targets startups under seven years old and Series A or earlier, with a product-focused business and public website/LinkedIn presence. Applicants may apply directly or through a VC, accelerator, or incubator; accepted startups receive a promo code and have 12 months to activate/use credits.','credits',0,NULL,NULL,'link','https://www.mongodb.com/solutions/startups',NULL,'in_review','Official source verified. Exact credit amount is not stated on the public page reviewed; do not display a dollar value until confirmed. Axal referral status is unconfirmed.',0,NULL,NULL,'external_program',NULL,'Source: https://www.mongodb.com/solutions/startups'),
('github-for-startups-credits',NULL,'GitHub','Software Stack','Up to $10,000 in GitHub credits','Credits can be used across GitHub Enterprise, Copilot, Advanced Security, Actions, and other eligible metered offerings.','GitHub states eligible startups receive $10,000 in credits for up to 12 months. Eligibility includes affiliation with a GitHub for Startups partner, outside funding up to Series B, and being new to GitHub Enterprise; credits are one-time and expire after consumption or 12 months.','credits',0,NULL,NULL,'link','https://github.com/enterprise/startups/partners?locale=en-US',NULL,'in_review','Official source verified. Axal is not represented as an approved GitHub partner; admin must confirm partner/referral status before approval.',0,NULL,NULL,'external_program',1000000,'Source: https://github.com/enterprise/startups'),
('notion-for-startups-business',NULL,'Notion','Software Stack','1 to 6 months free Notion Business Plan','Eligible startups may receive free Business Plan access, including Notion AI.','Notion states partner-affiliated startups may receive six months free, non-partner startups three months, and some SMBs or teams under ten employees one month. Offer is for new, non-paying customers and is applied once after approval.','credits',0,NULL,NULL,'link','https://www.notion.so/startups-apply',NULL,'in_review','Official source verified. Axal partner status and eligibility are unconfirmed; admin must confirm whether a partner code is available.',0,NULL,NULL,'external_program',NULL,'Source: https://www.notion.com/help/notion-for-startups'),
('hubspot-for-startups-discount',NULL,'HubSpot','Customer Acquisition / GTM','30% to 90% off eligible HubSpot products','Startup pricing for eligible net-new Professional or Enterprise products.','HubSpot states eligible pre-seed, Seed, and Series A startups can receive 90% off year one, 50% off year two, and 25% off year three; startups associated with approved entrepreneurial organizations may receive 30% off year one and 15% off year two. Annual commitment and eligibility rules apply.','credits',0,NULL,NULL,'link','https://app.hubspot.com/signup-hubspot/hubspot-for-startups',NULL,'in_review','Official source verified. Axal approved-partner/funding verification status is unconfirmed; admin must confirm before approval.',0,NULL,NULL,'external_program',NULL,'Source: https://www.hubspot.com/startups'),
('stripe-atlas-startup-formation',NULL,'Stripe','Legal & Corporate','Stripe Atlas incorporation plus $2,500 Stripe credits and $50,000+ partner discounts','Paid Delaware incorporation service with tax ID, equity issuance, 83(b) filing, SAFE tools, Stripe credits, and partner discounts.','Stripe lists a $500 one-time setup fee, $2,500 in Stripe product credits for the first year after incorporation, and access to over $50,000 in partner discounts. This is a paid service; Atlas is not a law firm and eligibility/jurisdiction must be reviewed by the founder.','money',0,NULL,50000,'link','https://dashboard.stripe.com/register/atlas',NULL,'in_review','Official source verified. This is not an Axal-negotiated discount; admin approval should preserve the paid engagement label and source terms.',0,NULL,NULL,'external_program',NULL,'Source: https://stripe.com/atlas'),
('openai-for-startups-credits',NULL,'OpenAI','AI','API credits and startup support through eligible VC partners','Eligible VC-backed startups may receive OpenAI API credits, rate-limit upgrades, technical support, and startup events.','OpenAI states that credits are available through eligible VC partners and that applicants need a unique referral code, product description, company contacts, and funding details. The public page does not state a universal credit amount.','credits',0,NULL,NULL,'intro','https://openai.com/leads/startup/',NULL,'in_review','Official source verified. This requires an eligible VC referral; Axal partner status and any available credit amount are unconfirmed and require admin confirmation.',0,NULL,NULL,'external_program',NULL,'Source: https://openai.com/startups/'),
('vercel-for-startups',NULL,'Vercel','Cloud & Infrastructure','Up to $30,000 in Vercel Flexible Commitment Amount','Eligible startup teams may receive Vercel platform credits, Enterprise-tier access, and startup-focused support.','Vercel states that Vercel for Startups provides eligible teams up to $30,000 in Flexible Commitment Amount, Enterprise-tier access, and startup-focused support. Participation is subject to the startup program and application process.','credits',0,NULL,NULL,'link','https://vercel.com/signup',NULL,'in_review','Official source verified. Vercel partner status and founder eligibility are unconfirmed; admin approval is required.',0,NULL,NULL,'external_program',3000000,'Source: https://vercel.com/startups'),
('digitalocean-startups-credits',NULL,'DigitalOcean','Cloud & Infrastructure','DigitalOcean Startups credits for 12 months','Startup credits for qualifying infrastructure services, with selected GPU packages reviewed separately.','DigitalOcean states the Startups program includes 12 months of credits. Applicants are evaluated using criteria including raising $10 million or less, a company website, corporate email, and a new DigitalOcean team account. The credit award amount is determined through the program/partner process and is not stated as a universal amount on the public page.','credits',0,NULL,NULL,'link','https://sammydigitalocean.typeform.com/hatch',NULL,'in_review','Official source verified. The public page says award level is determined through the program; Axal partner status and exact award are unconfirmed.',0,NULL,NULL,'external_program',NULL,'Source: https://www.digitalocean.com/hatch');
