/**
 * D111 — the money-adjacent RPC calls, and the one thing a binding cannot do.
 *
 * A SERVICE BINDING DOES NOT IDENTIFY ITS CALLER (D.7). Every branch→HQ method
 * therefore takes the branch's code as an argument, which makes the code
 * ATTRIBUTION and not authentication: any Worker in the account can call the
 * entrypoint and pass any code. For `escalate` that is acceptable — the worst
 * case is a mislabelled queue item. For `reportUsage` it is not: the figure it
 * writes is what a statement is drawn from, so a call that could claim to be
 * `fr` could change what Axal VC France is billed.
 *
 * So `reportUsage` carries a per-deployment secret, and this file is mostly
 * about the ways that check can quietly stop checking:
 *
 *   · A DEPLOYMENT WITH NO HASH MUST REFUSE. Every branch provisioned before
 *     the hash was wired has NULL there, and "null means skip" would remove the
 *     guard from exactly the deployments nobody has audited. This is not
 *     hypothetical: `RPC_SECRET_SHA256` was generated by the provisioning
 *     workflow and used once, so until PR 9 no real branch had a hash at all.
 *   · THE HASH IS WHAT IS STORED. A read of `licence_deployments` must not be
 *     enough to impersonate a branch.
 *   · A NULL FIGURE MUST STAY NULL. A branch that cannot measure a stream is
 *     the normal case, not an edge one, and a 0 stored there draws a statement
 *     that reads as a complete quarter which earned less.
 *
 * Called as plain functions rather than through `rpc/index.ts`, which imports
 * `cloudflare:workers` and cannot load under `node --test` at all. That is why
 * the entrypoint classes hold no logic: everything asserted here would
 * otherwise be verifiable only by deploying.
 *
 * Run with:
 *   node --experimental-strip-types --no-warnings --import ./cloudflare-worker/test/_ts-loader.mjs --test cloudflare-worker/test/branch_usage_report.test.ts
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DatabaseSync } from 'node:sqlite';

import { authenticateBranch, reportUsage } from '../src/rpc/hqOps.ts';
import { branchRevenueSummary, applyPromoCeiling } from '../src/rpc/branchOps.ts';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const MIGRATION_260 = readFileSync(
  resolve(ROOT, 'cloudflare-worker/sql/migrations/260_subsidiary_statements.sql'), 'utf8',
);

/**
 * The one real secret in this file. Its digest is COMPUTED by the fixture and
 * never hand-typed: a stored hash that had been pasted in would keep matching
 * after the hashing changed, which is the one thing this fixture must not do.
 */
const SECRET = 'rpc-secret-for-fr-0123456789abcdef';

function coerce(a: any[]): any[] {
  return a.map((v) => (v === undefined ? null : v === true ? 1 : v === false ? 0 : v));
}

function makeD1(db: InstanceType<typeof DatabaseSync>) {
  return {
    prepare(sql: string) {
      let b: any[] = [];
      const api: any = {
        bind: (...x: any[]) => { b = coerce(x); return api; },
        async first() { return db.prepare(sql).get(...b) ?? null; },
        async all() { return { results: db.prepare(sql).all(...b) }; },
        async run() {
          const r = db.prepare(sql).run(...b);
          return { meta: { last_row_id: Number(r.lastInsertRowid), changes: Number(r.changes) } };
        },
      };
      return api;
    },
    async exec(sql: string) { db.exec(sql); return { count: 0, duration: 0 }; },
  };
}

/** The same digest `authenticateBranch` computes, so the fixture cannot drift. */
async function sha256Hex(s: string): Promise<string> {
  const buf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(s));
  return [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

const HQ_SCHEMA = `
  CREATE TABLE territory_licences (id INTEGER PRIMARY KEY AUTOINCREMENT, uid TEXT UNIQUE NOT NULL,
    licence_ref TEXT UNIQUE NOT NULL, legal_entity_name TEXT NOT NULL, brand_name TEXT NOT NULL,
    revenue_share_bps INTEGER, currency TEXT NOT NULL DEFAULT 'EUR', status TEXT NOT NULL DEFAULT 'active');
  CREATE TABLE licence_deployments (id INTEGER PRIMARY KEY AUTOINCREMENT, licence_uid TEXT NOT NULL UNIQUE,
    code TEXT NOT NULL UNIQUE, hostname TEXT NOT NULL, worker_name TEXT NOT NULL, d1_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'live', rpc_secret_hash TEXT);
`;

/** HQ, with `fr` provisioned and `old` carrying no hash. */
async function hqEnv() {
  const db = new DatabaseSync(':memory:', { enableForeignKeyConstraints: false });
  db.exec(HQ_SCHEMA);
  db.exec(MIGRATION_260);
  db.prepare(
    `INSERT INTO territory_licences (uid, licence_ref, legal_entity_name, brand_name, revenue_share_bps, currency)
     VALUES (?,?,?,?,?,?)`,
  ).run('lic_fr', 'AXL-001', 'Axal VC France SAS', 'Axal VC France', 3500, 'EUR');
  db.prepare(
    `INSERT INTO territory_licences (uid, licence_ref, legal_entity_name, brand_name, revenue_share_bps, currency)
     VALUES (?,?,?,?,?,?)`,
  ).run('lic_old', 'AXL-002', 'Axal VC DACH GmbH', 'Axal VC DACH', 3500, 'EUR');

  const d = db.prepare(
    `INSERT INTO licence_deployments (licence_uid, code, hostname, worker_name, d1_name, rpc_secret_hash)
     VALUES (?,?,?,?,?,?)`,
  );
  d.run('lic_fr', 'fr', 'fr.axal.vc', 'studioos-fr', 'studioos-fr', await sha256Hex(SECRET));
  // Provisioned before the hash was wired: the case the guard must not skip.
  d.run('lic_old', 'old', 'old.axal.vc', 'studioos-old', 'studioos-old', null);

  // HQ: BRANCH_CODE unset. That is what `requireHq` reads.
  return { env: { DB: makeD1(db) } as any, db };
}

const BRANCH_SCHEMA = `
  CREATE TABLE ai_usage_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, est_cost_usd REAL, created_at TEXT);
  CREATE TABLE branch_promo_ceiling (id INTEGER PRIMARY KEY, period TEXT, ceiling_cents INTEGER,
    currency TEXT, issued_cents INTEGER, pushed_at TEXT, updated_at TEXT);
  CREATE TABLE branch_licence (id INTEGER PRIMARY KEY, status TEXT, pushed_at TEXT);
`;

/** A branch Worker, which is what `BRANCH_CODE` being set means. */
function branchEnv() {
  const db = new DatabaseSync(':memory:', { enableForeignKeyConstraints: false });
  db.exec(BRANCH_SCHEMA);
  return { env: { DB: makeD1(db), BRANCH_CODE: 'fr', BRANCH_NAME: 'Axal VC France' } as any, db };
}

const figures = (over: Partial<Record<string, unknown>>[] = []) => ([
  { stream: 'other', gross_cents: 400_000, currency: 'EUR' },
  ...over,
] as any[]);

/* ------------------------------------------------------------------ *
 * authenticateBranch                                                  *
 * ------------------------------------------------------------------ */

test('the right secret authenticates, and returns the licence the code maps to', async () => {
  const { env } = await hqEnv();
  const who = await authenticateBranch(env, 'fr', SECRET);
  assert.deepEqual(who, { code: 'fr', licence_uid: 'lic_fr' });
});

test('a wrong secret, an absent secret and an unknown code each refuse', async () => {
  const { env } = await hqEnv();
  await assert.rejects(() => authenticateBranch(env, 'fr', `${SECRET}x`), /wrong secret/);
  await assert.rejects(() => authenticateBranch(env, 'fr', ''), /presented no secret/);
  await assert.rejects(() => authenticateBranch(env, 'nope', SECRET), /not a provisioned branch/);
  // Not a branch code at all — refused before any table is read.
  for (const bad of ['fr;drop', '../x', '', 'f', 'fr rm -rf', 'f'.repeat(40)]) {
    await assert.rejects(() => authenticateBranch(env, bad, SECRET), /valid branch code/,
      `${JSON.stringify(bad)} was accepted as a branch code`);
  }
});

test('a code is normalised to lower case, and still needs that branch\'s own secret', async () => {
  // THE OPPOSITE RULE FROM THE DEPLOY ROUTE, which validates a new code exactly
  // as typed because there the string is a name being chosen. Here it is an
  // identifier being presented, so `FR` resolving to `fr` reaches no branch the
  // caller could not already reach — and the secret check is untouched by it.
  const { env } = await hqEnv();
  assert.deepEqual(await authenticateBranch(env, ' FR ', SECRET), { code: 'fr', licence_uid: 'lic_fr' });
  await assert.rejects(() => authenticateBranch(env, 'FR', 'not-it'), /wrong secret/,
    'normalising the code also skipped the secret');
});

test('a deployment with no hash on file refuses, and says what to do', async () => {
  // THE DEFAULT THAT MATTERS. Treating NULL as "no check configured, allow"
  // would disable the guard on every branch provisioned before it existed.
  const { env } = await hqEnv();
  await assert.rejects(
    () => authenticateBranch(env, 'old', SECRET),
    (e: Error) => /no rpc_secret_hash on file/.test(e.message) && /branch-provision/.test(e.message),
  );
});

test('what HQ stores is the hash, so reading the table cannot impersonate a branch', async () => {
  const { env, db } = await hqEnv();
  const stored = (db.prepare('SELECT rpc_secret_hash FROM licence_deployments WHERE code = ?').get('fr') as any)
    .rpc_secret_hash as string;

  assert.equal(stored.length, 64, 'the stored value is not a SHA-256 digest');
  assert.notEqual(stored, SECRET);
  assert.equal(stored.includes(SECRET), false, 'the secret itself is recoverable from the table');
  // And the digest, presented as if it were the secret, does not work — the
  // check hashes what it is given rather than comparing it raw.
  await assert.rejects(() => authenticateBranch(env, 'fr', stored), /wrong secret/);
});

test('a hash stored upper-case still matches — the shell that writes it may not lower it', async () => {
  const { env, db } = await hqEnv();
  const stored = (db.prepare('SELECT rpc_secret_hash FROM licence_deployments WHERE code = ?').get('fr') as any)
    .rpc_secret_hash as string;
  db.prepare('UPDATE licence_deployments SET rpc_secret_hash = ? WHERE code = ?')
    .run(stored.toUpperCase(), 'fr');
  const who = await authenticateBranch(env, 'fr', SECRET);
  assert.equal(who.code, 'fr');
});

test('HQ methods refuse to run on a branch', async () => {
  const { env } = await hqEnv();
  const onBranch = { ...env, BRANCH_CODE: 'fr' };
  await assert.rejects(() => authenticateBranch(onBranch, 'fr', SECRET));
  await assert.rejects(() => reportUsage(onBranch, 'fr', SECRET, '2026-Q3', figures()));
});

/* ------------------------------------------------------------------ *
 * reportUsage                                                         *
 * ------------------------------------------------------------------ */

test('a report writes one row per stream, stamped by the branch', async () => {
  const { env, db } = await hqEnv();
  const r = await reportUsage(env, 'fr', SECRET, '2026-Q3', figures([
    { stream: 'token_margin', gross_cents: null, currency: 'USD', available: false, estimate_basis: 'cost was USD 12.00' },
  ]));
  assert.deepEqual(r, { ok: true, period: '2026-Q3', streams: 2 });

  const rows = db.prepare('SELECT * FROM subsidiary_usage_reports ORDER BY stream').all() as any[];
  assert.equal(rows.length, 2);
  assert.equal(rows[0].stream, 'other');
  assert.equal(rows[0].gross_cents, 400_000);
  assert.equal(rows[0].licence_uid, 'lic_fr', 'the report was filed against the wrong licence');
  assert.equal(rows[0].branch_code, 'fr');
  assert.ok(rows[0].reported_at, 'a report arrived with no stamp');
});

test('a figure the branch could not measure is stored NULL, never 0', async () => {
  const { env, db } = await hqEnv();
  await reportUsage(env, 'fr', SECRET, '2026-Q3', [
    { stream: 'subscriptions', gross_cents: null, currency: 'EUR', available: false },
    // available:false WITH a number — the branch sent a figure it does not
    // stand behind, and the flag is what decides, not the presence of a value.
    { stream: 'licence_fees', gross_cents: 999, currency: 'EUR', available: false },
  ] as any);

  const rows = db.prepare('SELECT stream, gross_cents FROM subsidiary_usage_reports ORDER BY stream').all() as any[];
  assert.equal(rows.find((x) => x.stream === 'subscriptions').gross_cents, null);
  assert.equal(rows.find((x) => x.stream === 'licence_fees').gross_cents, null,
    'an unavailable stream kept a number the branch disclaimed');
});

test('a figure that is not a finite number is stored NULL, never coerced to 0 (D266)', async () => {
  // THE ONE READING THIS FUNCTION EXISTS TO REFUSE. `Number(x) || 0` turned a
  // figure that did not parse into a zero, which a statement then sums as a
  // measured quarter that earned nothing. Not parsing is not measuring.
  const { env, db } = await hqEnv();
  await reportUsage(env, 'fr', SECRET, '2026-Q3', [
    { stream: 'a', gross_cents: 'not a number' },
    { stream: 'b', gross_cents: Number.NaN },
    { stream: 'c', gross_cents: Number.POSITIVE_INFINITY },
    { stream: 'd', gross_cents: '1234.9' },
    { stream: 'e', gross_cents: 0 },
  ] as any);
  const by = Object.fromEntries((db.prepare('SELECT stream, gross_cents FROM subsidiary_usage_reports').all() as any[])
    .map((x) => [x.stream, x.gross_cents]));
  assert.equal(by.a, null, 'a string that does not parse was stored as a figure');
  assert.equal(by.b, null, 'NaN was stored as a figure');
  assert.equal(by.c, null, 'Infinity was stored as a figure');
  assert.equal(by.d, 1234, 'a numeric string is still a figure, truncated to whole cents');
  assert.equal(by.e, 0, 'a real zero is a measured zero and stays one');
});

test('a re-report replaces the figure rather than adding a second quarter', async () => {
  const { env, db } = await hqEnv();
  await reportUsage(env, 'fr', SECRET, '2026-Q3', figures());
  await reportUsage(env, 'fr', SECRET, '2026-Q3', [
    { stream: 'other', gross_cents: 450_000, currency: 'EUR' },
  ] as any);

  const rows = db.prepare('SELECT * FROM subsidiary_usage_reports').all() as any[];
  assert.equal(rows.length, 1, 'a correction was filed as a second period of trading');
  assert.equal(rows[0].gross_cents, 450_000);
});

test('a report with a wrong secret writes nothing at all', async () => {
  const { env, db } = await hqEnv();
  await assert.rejects(() => reportUsage(env, 'fr', 'not-it', '2026-Q3', figures()), /wrong secret/);
  assert.equal((db.prepare('SELECT COUNT(*) AS n FROM subsidiary_usage_reports').get() as any).n, 0);
});

test('a report against a period that is not a quarter writes nothing', async () => {
  const { env, db } = await hqEnv();
  for (const bad of ['2026-13', '2026-Q5', 'Q3', '']) {
    await assert.rejects(() => reportUsage(env, 'fr', SECRET, bad, figures()), /is not a period/);
  }
  assert.equal((db.prepare('SELECT COUNT(*) AS n FROM subsidiary_usage_reports').get() as any).n, 0);
});

test('a nameless stream is dropped rather than written as an empty one', async () => {
  const { env, db } = await hqEnv();
  const r = await reportUsage(env, 'fr', SECRET, '2026-Q3', [
    { stream: '   ', gross_cents: 1 }, { stream: 'other', gross_cents: 2 },
  ] as any);
  assert.equal(r.streams, 1);
  const rows = db.prepare('SELECT stream FROM subsidiary_usage_reports').all() as any[];
  assert.deepEqual(rows.map((x) => x.stream), ['other']);
});

/* ------------------------------------------------------------------ *
 * The branch side                                                     *
 * ------------------------------------------------------------------ */

test('a branch reports every stream it cannot measure, with a reason for each', async () => {
  const { env } = branchEnv();
  const s = await branchRevenueSummary(env, '2026-Q3');

  assert.equal(s.branch, 'fr');
  assert.deepEqual(s.streams.map((x) => x.stream), ['subscriptions', 'licence_fees', 'token_margin']);
  for (const x of s.streams) {
    assert.equal(x.available, false, `${x.stream} claims to be measurable`);
    assert.equal(x.gross_cents, null, `${x.stream} reported a figure it says it cannot measure`);
    assert.ok(String(x.reason || '').length > 20, `${x.stream} is absent with no usable reason`);
  }
});

test('the token COST is carried as a basis, never as revenue', async () => {
  // The one measured number on a branch. Reporting it as `token_margin`'s
  // gross would let a statement sum a COST as revenue — so it rides in
  // `estimate_basis`, which nothing adds up.
  const { env, db } = branchEnv();
  const ins = db.prepare('INSERT INTO ai_usage_logs (est_cost_usd, created_at) VALUES (?,?)');
  ins.run(10.25, '2026-08-01T00:00:00Z');
  ins.run(2.5, '2026-09-30T23:59:59Z');
  ins.run(99, '2026-10-01T00:00:01Z');   // Q4 — must not be counted
  ins.run(99, '2026-06-30T23:59:59Z');   // Q2 — must not be counted

  const s = await branchRevenueSummary(env, '2026-Q3');
  const token = s.streams.find((x) => x.stream === 'token_margin')!;
  assert.equal(token.gross_cents, null);
  assert.equal(token.is_estimate, true);
  assert.match(String(token.estimate_basis), /USD 12\.75/, 'the quarter bounds let another quarter in');
  assert.match(String(token.estimate_basis), /2 calls/);
});

test('branchRevenueSummary refuses a period that is not a quarter, and refuses to run at HQ', async () => {
  const { env } = branchEnv();
  await assert.rejects(() => branchRevenueSummary(env, '2026-13'), /is not a period/);
  const atHq = { ...env, BRANCH_CODE: '' };
  await assert.rejects(() => branchRevenueSummary(atHq, '2026-Q3'), /only live on a branch/);
});

test('a pushed ceiling is stored as one dated copy and leaves the issued figure alone', async () => {
  const { env, db } = branchEnv();
  db.prepare(
    'INSERT INTO branch_promo_ceiling (id, period, ceiling_cents, currency, issued_cents) VALUES (1,?,?,?,?)',
  ).run('2026-Q3', 100_000, 'EUR', 40_000);

  await applyPromoCeiling(env, {
    period: '2026-Q3', ceiling_cents: 500_000, currency: 'eur', pushed_at: '2026-09-15T10:00:00Z',
  });

  const rows = db.prepare('SELECT * FROM branch_promo_ceiling').all() as any[];
  assert.equal(rows.length, 1, 'a second ceiling row appeared on the branch');
  assert.equal(rows[0].ceiling_cents, 500_000);
  assert.equal(rows[0].currency, 'EUR', 'the currency was stored as it arrived rather than normalised');
  assert.equal(rows[0].pushed_at, '2026-09-15T10:00:00Z');
  // THE BRANCH OWNS THIS ONE. A push that reset it would erase the branch's
  // own count every time HQ moved the ceiling.
  assert.equal(rows[0].issued_cents, 40_000, 'a ceiling push erased the branch\'s issued figure');
});

test('applyPromoCeiling refuses to run at HQ', async () => {
  const { env, db } = branchEnv();
  const atHq = { ...env, BRANCH_CODE: '' };
  await assert.rejects(() => applyPromoCeiling(atHq, {
    period: '2026-Q3', ceiling_cents: 1, currency: 'EUR', pushed_at: '2026-09-15T10:00:00Z',
  }), /only live on a branch/);
  assert.equal((db.prepare('SELECT COUNT(*) AS n FROM branch_promo_ceiling').get() as any).n, 0);
});
