import React from 'react';
import { Link, useParams } from 'react-router-dom';
import { ExternalLink, ArrowLeft, ShieldCheck } from 'lucide-react';
import { Card } from '../../ui';
import data from '../../data/companyDirectory.json';
import finance from '../../data/financialSnapshots.json';
import { BrainCircuit } from 'lucide-react';

function Fact({ label, value }) {
  return <div><div className="text-[10px] font-extrabold uppercase tracking-[.08em] text-axal-faint">{label}</div><div className="mt-1 text-[13px] text-axal-ink dark:text-gray-100">{value || 'Not recorded'}</div></div>;
}

export default function CompanyProfile() {
  const { uid } = useParams();
  const company = (data.items || []).find((x) => x.uid === uid);
  if (!company) return <Card variant="dashed"><h1 className="text-sm font-extrabold">Company not found</h1><Link to="/research/companies" className="mt-2 inline-block text-[12px] text-axal-violet underline">Back to companies</Link></Card>;
  const analysisUrl = `/build/competitors?market=${encodeURIComponent(company.name)}&website=${encodeURIComponent(company.website)}`;
  const snapshot = Object.values(finance.companies || {}).find((x) => company.website?.toLowerCase().includes(x.domain) || company.name?.toLowerCase().includes(x.name.split(',')[0].toLowerCase()));
  const phoenixSnapshot = snapshot ? finance.phoenix?.companies?.[snapshot.domain] : null;
  const fmpSnapshot = snapshot ? finance.fmp?.companies?.[snapshot.ticker] : null;
  return <div data-testid="company-profile" className="space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><Link to="/research/companies" className="inline-flex items-center gap-1 text-[12px] font-semibold text-axal-violet underline dark:text-violet-300"><ArrowLeft size={13} /> Companies</Link><Link to={`/research/gtm?domain=${encodeURIComponent(snapshot?.domain || '')}`} className="inline-flex items-center gap-1 rounded-lg bg-violet-700 px-3 py-2 text-[12px] font-bold text-white"><BrainCircuit size={14} /> Open GTM intelligence</Link></div>
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start">
      <div><div className="text-[10px] font-extrabold uppercase tracking-[.1em] text-axal-faint">Company profile · public baseline</div><h1 className="mt-1 text-2xl font-extrabold tracking-tight text-axal-ink dark:text-gray-100">{company.name}</h1><a href={company.website} target="_blank" rel="noreferrer" className="mt-1 inline-flex items-center gap-1 text-[12px] text-axal-violet underline">{company.website}<ExternalLink size={12} /></a></div>
      <Link to={analysisUrl} className="inline-flex items-center justify-center rounded-lg bg-violet-700 px-3 py-2 text-[12px] font-semibold text-white hover:bg-violet-800">Run competitor analysis →</Link>
    </div>
    <Card className="border-emerald-200 bg-emerald-50/60 dark:border-emerald-900 dark:bg-emerald-950/20"><div className="flex items-start gap-2 text-[12px] leading-relaxed text-emerald-950 dark:text-emerald-100"><ShieldCheck size={15} className="mt-0.5 shrink-0" /><span><strong>Evidence label:</strong> identity facts come from Wikidata. {snapshot ? 'The financial snapshot below is provider-reported public-market data, as-of 29 September 2026.' : 'Funding, valuation, revenue, market size, risk, and competitive position are intentionally not inferred from this baseline.'}</span></div></Card>
    <Card><div className="grid grid-cols-2 gap-x-5 gap-y-5 sm:grid-cols-4"><Fact label="Country" value={company.country} /><Fact label="Founded" value={company.founded_year} /><Fact label="Sector" value={company.sector} /><Fact label="Wikidata ID" value={company.uid.toUpperCase()} /></div></Card>
    {snapshot && <><Card><div className="flex items-baseline justify-between gap-3"><h2 className="text-sm font-extrabold tracking-tight">Public-market snapshot</h2><span className="text-[10px] font-semibold uppercase tracking-[.08em] text-axal-faint">{snapshot.ticker} · FMP</span></div><div className="mt-3 grid grid-cols-2 gap-x-5 gap-y-5 sm:grid-cols-4"><Fact label="Last price" value={`$${snapshot.last_price}`} /><Fact label="Market cap" value={snapshot.market_cap} /><Fact label="1Y price change" value={`${snapshot.price_change_1y_pct}%`} /><Fact label="Employees" value={snapshot.employees?.toLocaleString()} /><Fact label="TTM gross margin" value={`${(snapshot.gross_margin_ttm * 100).toFixed(1)}%`} /><Fact label="TTM operating margin" value={`${(snapshot.operating_margin_ttm * 100).toFixed(1)}%`} /><Fact label="TTM P/E" value={snapshot.pe_ttm} /><Fact label="Next earnings" value={snapshot.next_earnings} /></div></Card><Card><h2 className="text-sm font-extrabold tracking-tight">Latest quarterly performance</h2><div className="mt-3 grid grid-cols-2 gap-x-5 gap-y-5 sm:grid-cols-4"><Fact label="Period" value={snapshot.latest_quarter} /><Fact label="Revenue" value={snapshot.revenue_latest_quarter} /><Fact label="Net income" value={snapshot.net_income_latest_quarter} /><Fact label="Free cash flow" value={snapshot.fcf_latest_quarter} /></div>{fmpSnapshot?.quarterly && <div className="mt-4 grid grid-cols-3 gap-2">{fmpSnapshot.quarterly.map((q) => <div key={q.date} className="rounded-lg border border-axal-hairline p-2 dark:border-gray-800"><div className="text-[10px] font-bold text-axal-faint">{q.period}</div><div className="mt-1 text-[12px] font-bold text-axal-ink dark:text-gray-100">${(q.revenue / 1e9).toFixed(1)}B revenue</div><div className="text-[10px] text-axal-muted">${(q.net_income / 1e9).toFixed(1)}B net income · EPS {q.eps}</div></div>)}</div>}<p className="mt-3 text-[11px] text-axal-faint">Source: Financial Modeling Prep quarterly statements; values are not investment recommendations.</p></Card></>}
    {phoenixSnapshot && <Card className="border-violet-200 dark:border-violet-900"><div className="flex items-baseline justify-between gap-3"><h2 className="text-sm font-extrabold tracking-tight">GTM intelligence</h2><span className="text-[10px] font-semibold uppercase tracking-[.08em] text-violet-700 dark:text-violet-300">Phoenix by HG Insights</span></div><div className="mt-3 grid grid-cols-2 gap-x-5 gap-y-5 sm:grid-cols-4"><Fact label="AI maturity" value={`${phoenixSnapshot.ai_maturity_score}/100`} /><Fact label="GenAI intent" value={phoenixSnapshot.genai_intent_score?.toLocaleString()} /><Fact label="Total IT spend" value={`$${(phoenixSnapshot.it_spend / 1e9).toFixed(1)}B`} /><Fact label="AI spend" value={`$${(phoenixSnapshot.total_ai_spend / 1e9).toFixed(1)}B`} /><Fact label="Employees" value={phoenixSnapshot.employees?.toLocaleString()} /><Fact label="Cloud mix" value={`${phoenixSnapshot.current_products_used_cloud_percent}%`} /><Fact label="Cloud provider" value={phoenixSnapshot.dominant_cloud_provider} /><Fact label="Data maturity" value={phoenixSnapshot.data_maturity_level} /></div><p className="mt-3 text-[11px] leading-relaxed text-axal-faint">Modeled firmographic, technographic, intent, and spend signals. Use the <Link to={`/research/gtm?domain=${phoenixSnapshot.domain}`} className="font-semibold text-axal-violet underline">Phoenix qualification workspace</Link> for the account brief.</p></Card>}
    <Card><div className="flex items-baseline justify-between gap-3"><h2 className="text-sm font-extrabold tracking-tight">Company intelligence</h2><span className="text-[10px] font-semibold uppercase tracking-[.08em] text-axal-faint">Evidence required</span></div><div className="mt-3 grid grid-cols-2 gap-x-5 gap-y-5 sm:grid-cols-4"><Fact label="Funding" /><Fact label="Valuation" /><Fact label="Revenue" /><Fact label="Employees" /><Fact label="Market share" /><Fact label="Growth" /><Fact label="Competitor status" /><Fact label="Diligence status" /></div><p className="mt-3 text-[11px] leading-relaxed text-axal-muted">These fields are intentionally not inferred from the public identity baseline. Use the competitor-analysis workspace and attach primary evidence before recording a figure.</p></Card>
    <div className="grid gap-4 lg:grid-cols-2"><Card><h2 className="text-sm font-extrabold tracking-tight">Competitor research workspace</h2><p className="mt-2 text-[12.5px] leading-relaxed text-axal-muted">The analysis tool can assess market players, gaps, positioning, pricing signals, traction signals, and a suggested wedge. Its output is a research artifact, not a sourced fact about this company until the evidence rail is reviewed.</p><Link to={analysisUrl} className="mt-3 inline-block text-[12px] font-semibold text-axal-violet underline">Open analysis with {company.name} prefilled →</Link></Card><Card><h2 className="text-sm font-extrabold tracking-tight">Source</h2><p className="mt-2 text-[12px] text-axal-muted">{company.source_license}</p><a href={company.source_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-[12px] text-axal-violet underline">Open Wikidata record <ExternalLink size={12} /></a><p className="mt-2 text-[11px] text-axal-faint">Retrieved {data.source?.retrieved_at || company.as_of}</p></Card></div>
  </div>;
}
