import React, { useEffect, useMemo, useState } from 'react';
import {
  Banknote, FileText, RefreshCw, Plus, X, AlertTriangle, CheckCircle2,
  PieChart as PieIcon, TrendingUp, Wallet, Send, ScrollText,
} from 'lucide-react';
import {
  BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, LineChart, Line,
} from 'recharts';
import { api } from '../lib/api';

const fmtCents = (cents) => {
  const v = Number(cents || 0) / 100;
  if (v >= 1_000_000) return `$${(v / 1_000_000).toFixed(2)}M`;
  if (v >= 1_000) return `$${(v / 1_000).toFixed(1)}K`;
  return `$${v.toFixed(0)}`;
};
const fmtDollars = (d) => {
  const v = Number(d || 0);
  if (v >= 1_000_000) return `$${(v / 1_000_000).toFixed(2)}M`;
  if (v >= 1_000) return `$${(v / 1_000).toFixed(1)}K`;
  return `$${v.toFixed(0)}`;
};

function StatusPill({ status }) {
  const map = {
    fundraising: 'bg-amber-100 text-amber-800',
    active: 'bg-emerald-100 text-emerald-800',
    closed: 'bg-gray-200 text-gray-700',
    wound_down: 'bg-red-100 text-red-700',
    pending: 'bg-amber-100 text-amber-800',
    paid: 'bg-emerald-100 text-emerald-800',
    failed: 'bg-red-100 text-red-700',
    committed: 'bg-amber-100 text-amber-800',
    redeemed: 'bg-gray-200 text-gray-700',
  };
  return <span className={`inline-block px-2 py-0.5 rounded text-[11px] font-medium ${map[status] || 'bg-gray-100 text-gray-700'}`}>{status}</span>;
}

function CreateFundModal({ onClose }) {
  const [name, setName] = useState('');
  const [vintage, setVintage] = useState(new Date().getFullYear());
  const [sizeM, setSizeM] = useState('');
  const [carry, setCarry] = useState(0.20);
  const [mgmt, setMgmt] = useState(0.02);
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState('');

  const submit = async (e) => {
    e.preventDefault();
    if (!name) return setErr('Name required.');
    setBusy(true); setErr('');
    try {
      await api.fundsCreateV2({
        name,
        vintage_year: parseInt(vintage, 10),
        fund_size_cents: Math.round(Number(sizeM || 0) * 1_000_000 * 100),
        carried_interest: Number(carry),
        management_fee: Number(mgmt),
        status: 'fundraising',
      });
      onClose(true);
    } catch (e) { setErr(e.message); }
    finally { setBusy(false); }
  };

  return (
    <div className="fixed inset-0 bg-black/40 z-50 flex items-end md:items-center justify-center p-3" onClick={() => onClose()}>
      <form onSubmit={submit} className="bg-white rounded-xl shadow-xl max-w-md w-full p-5" onClick={e => e.stopPropagation()}>
        <div className="flex items-start justify-between mb-3">
          <div className="text-base font-semibold text-gray-900 flex items-center gap-2">
            <Plus size={16} className="text-violet-600" /> Create new VC fund
          </div>
          <button type="button" onClick={() => onClose()}><X size={18} className="text-gray-400 hover:text-gray-700" /></button>
        </div>
        <p className="text-xs text-gray-500 mb-3">An LPA will be auto-generated by the AI legal engine.</p>
        {err && <div className="bg-red-50 text-red-700 text-xs rounded px-2 py-1 mb-2 flex items-center gap-1.5"><AlertTriangle size={12} /> {err}</div>}
        <div className="space-y-3">
          <Field label="Fund Name" required value={name} onChange={setName} />
          <Field label="Vintage Year" type="number" value={vintage} onChange={setVintage} />
          <Field label="Target Fund Size ($M)" type="number" step="0.1" value={sizeM} onChange={setSizeM} placeholder="50" />
          <Field label="Carried Interest (0.20 = 20%)" type="number" step="0.01" value={carry} onChange={setCarry} />
          <Field label="Management Fee (0.02 = 2%)" type="number" step="0.005" value={mgmt} onChange={setMgmt} />
        </div>
        <div className="mt-4 flex justify-end gap-2">
          <button type="button" onClick={() => onClose()} className="px-3 py-1.5 text-sm border border-gray-300 rounded-lg">Cancel</button>
          <button type="submit" disabled={busy} className="px-3 py-1.5 text-sm bg-violet-600 hover:bg-violet-700 disabled:bg-violet-300 text-white rounded-lg">
            {busy ? 'Creating…' : 'Create fund'}
          </button>
        </div>
      </form>
    </div>
  );
}

function Field({ label, value, onChange, required, type = 'text', step, placeholder }) {
  return (
    <label className="block">
      <span className="text-xs font-medium text-gray-700">{label}</span>
      <input type={type} step={step} value={value} required={required} placeholder={placeholder}
        onChange={e => onChange(e.target.value)}
        className="mt-1 w-full border border-gray-300 rounded-lg px-3 py-2 text-sm text-gray-900" />
    </label>
  );
}

function CapitalCallModal({ fund, onClose }) {
  const [amountM, setAmountM] = useState('');
  const [note, setNote] = useState('');
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState('');
  const submit = async (e) => {
    e.preventDefault();
    setBusy(true); setErr('');
    try {
      await api.fundsCapitalCallV2(fund.id, Math.round(Number(amountM || 0) * 1_000_000 * 100), note);
      onClose(true);
    } catch (e) { setErr(e.message); }
    finally { setBusy(false); }
  };
  return (
    <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-3" onClick={() => onClose()}>
      <form onSubmit={submit} className="bg-white rounded-xl shadow-xl max-w-md w-full p-5" onClick={e => e.stopPropagation()}>
        <div className="flex items-start justify-between mb-3">
          <div className="text-base font-semibold text-gray-900 flex items-center gap-2">
            <Send size={16} className="text-violet-600" /> Capital call · {fund.name}
          </div>
          <button type="button" onClick={() => onClose()}><X size={18} className="text-gray-400" /></button>
        </div>
        {err && <div className="bg-red-50 text-red-700 text-xs rounded px-2 py-1 mb-2">{err}</div>}
        <Field label="Amount ($M)" type="number" step="0.01" value={amountM} onChange={setAmountM} required />
        <div className="mt-3"><Field label="Note (optional)" value={note} onChange={setNote} /></div>
        <div className="mt-4 flex justify-end gap-2">
          <button type="button" onClick={() => onClose()} className="px-3 py-1.5 text-sm border border-gray-300 rounded-lg">Cancel</button>
          <button type="submit" disabled={busy} className="px-3 py-1.5 text-sm bg-violet-600 hover:bg-violet-700 disabled:bg-violet-300 text-white rounded-lg">
            {busy ? 'Sending…' : 'Send notices'}
          </button>
        </div>
      </form>
    </div>
  );
}

function DistributionModal({ fund, onClose }) {
  const [proceedsM, setProceedsM] = useState('');
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState('');
  const submit = async (e) => {
    e.preventDefault();
    setBusy(true); setErr('');
    try {
      await api.fundsExecuteDistribution({
        fund_id: fund.id,
        proceeds_cents: Math.round(Number(proceedsM || 0) * 1_000_000 * 100),
      });
      onClose(true);
    } catch (e) { setErr(e.message); }
    finally { setBusy(false); }
  };
  return (
    <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-3" onClick={() => onClose()}>
      <form onSubmit={submit} className="bg-white rounded-xl shadow-xl max-w-md w-full p-5" onClick={e => e.stopPropagation()}>
        <div className="flex items-start justify-between mb-3">
          <div className="text-base font-semibold text-gray-900 flex items-center gap-2">
            <Banknote size={16} className="text-emerald-600" /> Run distribution · {fund.name}
          </div>
          <button type="button" onClick={() => onClose()}><X size={18} className="text-gray-400" /></button>
        </div>
        <p className="text-xs text-gray-500 mb-3">Splits proceeds pro-rata to LPs (after {((fund.carried_interest ?? 0.2) * 100).toFixed(0)}% carry).</p>
        {err && <div className="bg-red-50 text-red-700 text-xs rounded px-2 py-1 mb-2">{err}</div>}
        <Field label="Proceeds ($M)" type="number" step="0.01" value={proceedsM} onChange={setProceedsM} required />
        <div className="mt-4 flex justify-end gap-2">
          <button type="button" onClick={() => onClose()} className="px-3 py-1.5 text-sm border border-gray-300 rounded-lg">Cancel</button>
          <button type="submit" disabled={busy} className="px-3 py-1.5 text-sm bg-emerald-600 hover:bg-emerald-700 disabled:bg-emerald-300 text-white rounded-lg">
            {busy ? 'Running…' : 'Distribute'}
          </button>
        </div>
      </form>
    </div>
  );
}

function LPADrawer({ fundId, onClose }) {
  const [doc, setDoc] = useState(null);
  const [err, setErr] = useState('');
  useEffect(() => {
    let cancelled = false;
    api.fundsLpa(fundId)
      .then(r => { if (!cancelled) setDoc(r.doc); })
      .catch(e => { if (!cancelled) setErr(e.message); });
    return () => { cancelled = true; };
  }, [fundId]);
  return (
    <div className="fixed inset-0 bg-black/40 z-50 flex justify-end" onClick={onClose}>
      <div className="bg-white w-full max-w-2xl h-full overflow-y-auto p-6" onClick={e => e.stopPropagation()}>
        <div className="flex items-start justify-between mb-3">
          <div className="text-base font-semibold text-gray-900 flex items-center gap-2"><ScrollText size={16} className="text-violet-600" /> LPA — Fund #{fundId}</div>
          <button onClick={onClose}><X size={18} className="text-gray-400" /></button>
        </div>
        {err && <div className="bg-red-50 text-red-700 text-xs rounded px-2 py-1">{err}</div>}
        {!doc ? <div className="text-xs text-gray-400 py-8 text-center">Loading…</div> : (
          <>
            <div className="text-xs text-gray-500 mb-3">v{doc.version} · {doc.status} · {doc.created_at && new Date(doc.created_at + 'Z').toLocaleString()}</div>
            {doc.content
              ? <pre className="whitespace-pre-wrap text-xs text-gray-800 bg-gray-50 p-4 rounded-lg border border-gray-200">{doc.content}</pre>
              : <div className="text-xs text-gray-400">Content redacted (you are not an LP of this fund).</div>}
          </>
        )}
      </div>
    </div>
  );
}

// ----- Admin/Operator view -----
function AdminFundsView() {
  const [funds, setFunds] = useState(null);
  const [active, setActive] = useState(null);          // selected fund
  const [activeDistribs, setActiveDistribs] = useState([]);
  const [activeLPs, setActiveLPs] = useState([]);
  const [showCreate, setShowCreate] = useState(false);
  const [showCC, setShowCC] = useState(null);
  const [showDist, setShowDist] = useState(null);
  const [showLpa, setShowLpa] = useState(null);
  const [err, setErr] = useState('');
  const [busy, setBusy] = useState(false);

  const load = async () => {
    setBusy(true); setErr('');
    try {
      const r = await api.fundsList();
      setFunds(r.items || []);
      if (active) {
        const [d, l] = await Promise.all([
          api.fundsDistributions(active.id),
          api.fundsLpsList(active.id),
        ]);
        setActiveDistribs(d.items || []);
        setActiveLPs(l.items || []);
      }
    } catch (e) { setErr(e.message); }
    finally { setBusy(false); }
  };
  useEffect(() => { load(); /* eslint-disable-next-line */ }, [active?.id]);

  const markPaid = async (id) => {
    try { await api.fundsMarkDistributionPaid(id); load(); }
    catch (e) { setErr(e.message); }
  };
  const regenLpa = async (id) => {
    try { await api.fundsRegenerateLpa(id); setTimeout(load, 1500); }
    catch (e) { setErr(e.message); }
  };

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div className="text-sm font-semibold text-gray-900">All funds ({funds?.length ?? 0})</div>
        <div className="flex gap-2">
          <button onClick={() => setShowCreate(true)}
            className="px-3 py-1.5 text-sm bg-violet-600 hover:bg-violet-700 text-white rounded-lg flex items-center gap-1.5">
            <Plus size={13} /> New fund
          </button>
          <button onClick={load} disabled={busy}
            className="px-3 py-1.5 text-sm bg-white border border-gray-300 rounded-lg flex items-center gap-1.5">
            <RefreshCw size={13} className={busy ? 'animate-spin' : ''} /> Refresh
          </button>
        </div>
      </div>
      {err && <div className="bg-red-50 text-red-700 text-sm rounded px-3 py-2">{err}</div>}

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
        {(funds || []).map(f => (
          <button key={f.id}
            onClick={() => setActive(f)}
            className={`text-left bg-white border rounded-xl p-4 hover:border-violet-400 transition
              ${active?.id === f.id ? 'border-violet-500 ring-2 ring-violet-200' : 'border-gray-200'}`}>
            <div className="flex items-start justify-between">
              <div className="text-sm font-semibold text-gray-900">{f.name}</div>
              <StatusPill status={f.status} />
            </div>
            <div className="text-xs text-gray-500 mt-0.5">Vintage {f.vintage_year || '—'}</div>
            <div className="grid grid-cols-2 gap-2 mt-3 text-xs">
              <div><div className="text-gray-500">Fund size</div><div className="font-medium text-gray-900">{fmtCents(f.fund_size_cents)}</div></div>
              <div><div className="text-gray-500">LPs</div><div className="font-medium text-gray-900">{f.lp_count}</div></div>
              <div><div className="text-gray-500">Carry</div><div className="font-medium text-gray-900">{((f.carried_interest ?? 0.2) * 100).toFixed(0)}%</div></div>
              <div><div className="text-gray-500">Mgmt fee</div><div className="font-medium text-gray-900">{((f.management_fee ?? 0.02) * 100).toFixed(2)}%</div></div>
            </div>
            <div className="text-[11px] mt-2 flex items-center gap-1.5">
              <FileText size={11} className={f.lpa_doc_id ? 'text-emerald-600' : 'text-amber-600'} />
              {f.lpa_doc_id ? <span className="text-emerald-700">LPA on file</span> : <span className="text-amber-700">LPA pending</span>}
            </div>
          </button>
        ))}
        {!funds?.length && <div className="col-span-full text-sm text-gray-400 text-center py-12">No funds yet.</div>}
      </div>

      {active && (
        <div className="bg-white border border-gray-200 rounded-xl p-5">
          <div className="flex items-start justify-between mb-3">
            <div>
              <div className="text-sm font-semibold text-gray-900">{active.name}</div>
              <div className="text-xs text-gray-500">Vintage {active.vintage_year || '—'} · {active.lp_count} LPs · {fmtCents(active.fund_size_cents)} target</div>
            </div>
            <div className="flex gap-2 flex-wrap">
              <button onClick={() => setShowLpa(active.id)} className="px-2.5 py-1 text-xs bg-gray-100 hover:bg-gray-200 rounded flex items-center gap-1"><FileText size={11} /> View LPA</button>
              <button onClick={() => regenLpa(active.id)} className="px-2.5 py-1 text-xs bg-gray-100 hover:bg-gray-200 rounded">Regenerate LPA</button>
              <button onClick={() => setShowCC(active)} className="px-2.5 py-1 text-xs bg-violet-600 hover:bg-violet-700 text-white rounded flex items-center gap-1"><Send size={11} /> Capital call</button>
              <button onClick={() => setShowDist(active)} className="px-2.5 py-1 text-xs bg-emerald-600 hover:bg-emerald-700 text-white rounded flex items-center gap-1"><Banknote size={11} /> Distribute</button>
            </div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-3">
            <div>
              <div className="text-xs font-medium text-gray-700 mb-2">Limited Partners</div>
              {!activeLPs.length ? <div className="text-xs text-gray-400">No LPs yet.</div> : (
                <table className="w-full text-xs">
                  <thead className="text-gray-500"><tr>
                    <th className="text-left py-1 font-medium">LP</th>
                    <th className="text-right font-medium">Commit</th>
                    <th className="text-right font-medium">Invested</th>
                    <th className="text-left font-medium">LPA</th>
                  </tr></thead>
                  <tbody>
                    {activeLPs.map(lp => (
                      <tr key={lp.id} className="border-t border-gray-100">
                        <td className="py-1">{lp.name || lp.email || `user#${lp.user_id}`}</td>
                        <td className="text-right">{fmtDollars(lp.commitment_amount)}</td>
                        <td className="text-right">{fmtDollars(lp.invested_amount)}</td>
                        <td>{lp.lpa_signed ? <span className="text-emerald-700">signed</span> : <span className="text-amber-700">pending</span>}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
            <div>
              <div className="text-xs font-medium text-gray-700 mb-2">Recent distributions</div>
              {!activeDistribs.length ? <div className="text-xs text-gray-400">No distributions yet.</div> : (
                <table className="w-full text-xs">
                  <thead className="text-gray-500"><tr>
                    <th className="text-left py-1 font-medium">Date</th>
                    <th className="text-left font-medium">LP</th>
                    <th className="text-left font-medium">Type</th>
                    <th className="text-right font-medium">Amount</th>
                    <th></th>
                  </tr></thead>
                  <tbody>
                    {activeDistribs.map(d => (
                      <tr key={d.id} className="border-t border-gray-100">
                        <td className="py-1 text-gray-500">{new Date((d.distributed_at || d.created_at) + 'Z').toLocaleDateString()}</td>
                        <td>{d.lp_name || d.lp_email || `lp#${d.lp_id}`}</td>
                        <td>{d.distribution_type}</td>
                        <td className="text-right font-medium">{fmtCents(d.amount_cents)}</td>
                        <td className="text-right">
                          {d.status === 'pending'
                            ? <button onClick={() => markPaid(d.id)} className="text-violet-600 hover:underline">mark paid</button>
                            : <StatusPill status={d.status} />}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
          </div>
        </div>
      )}

      {showCreate && <CreateFundModal onClose={(refresh) => { setShowCreate(false); if (refresh) load(); }} />}
      {showCC && <CapitalCallModal fund={showCC} onClose={(refresh) => { setShowCC(null); if (refresh) load(); }} />}
      {showDist && <DistributionModal fund={showDist} onClose={(refresh) => { setShowDist(null); if (refresh) load(); }} />}
      {showLpa && <LPADrawer fundId={showLpa} onClose={() => setShowLpa(null)} />}
    </div>
  );
}

// ----- LP Portal view -----
function LPPortalView() {
  const [data, setData] = useState(null);
  const [err, setErr] = useState('');
  const [busy, setBusy] = useState(false);
  const [showLpa, setShowLpa] = useState(null);

  const load = async () => {
    setBusy(true); setErr('');
    try { setData(await api.fundsLpPortal()); }
    catch (e) { setErr(e.message); }
    finally { setBusy(false); }
  };
  useEffect(() => { load(); }, []);

  const sign = async (lpId) => {
    try { await api.fundsSignLpa(lpId); load(); }
    catch (e) { setErr(e.message); }
  };

  const totals = useMemo(() => {
    const commit = (data?.lp_holdings || []).reduce((s, lp) => s + Number(lp.commitment_amount || 0), 0);
    const invested = (data?.lp_holdings || []).reduce((s, lp) => s + Number(lp.invested_amount || 0), 0);
    const distCents = (data?.distributions || []).reduce((s, d) => s + Number(d.amount_cents || 0), 0);
    return { commit, invested, distCents };
  }, [data]);

  const perfChart = useMemo(() =>
    (data?.performance || []).map(p => ({ name: p.fund_name, TVPI: p.tvpi, DPI: p.dpi })),
    [data]);

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div className="text-sm font-semibold text-gray-900">My LP Portal</div>
        <button onClick={load} disabled={busy} className="px-3 py-1.5 text-sm bg-white border border-gray-300 rounded-lg flex items-center gap-1.5">
          <RefreshCw size={13} className={busy ? 'animate-spin' : ''} /> Refresh
        </button>
      </div>
      {err && <div className="bg-red-50 text-red-700 text-sm rounded px-3 py-2">{err}</div>}

      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        <Card icon={Wallet} accent="violet" label="Commitment" value={fmtDollars(totals.commit)} sub="Across funds" />
        <Card icon={TrendingUp} accent="emerald" label="Invested" value={fmtDollars(totals.invested)} sub="Drawn so far" />
        <Card icon={Banknote} accent="emerald" label="Distributions" value={fmtCents(totals.distCents)} sub={`${(data?.distributions || []).length} payouts`} />
        <Card icon={PieIcon} accent="blue" label="Funds" value={data?.lp_holdings?.length ?? 0} sub="Active positions" />
      </div>

      <div className="bg-white border border-gray-200 rounded-xl p-5">
        <div className="text-sm font-semibold text-gray-900 mb-3">My commitments</div>
        {!data?.lp_holdings?.length ? <div className="text-xs text-gray-400 text-center py-6">No LP positions on file.</div> : (
          <table className="w-full text-xs">
            <thead className="text-gray-500"><tr>
              <th className="text-left py-1 font-medium">Fund</th>
              <th className="text-right font-medium">Commitment</th>
              <th className="text-right font-medium">Invested</th>
              <th className="text-right font-medium">Returns</th>
              <th className="text-left font-medium">Status</th>
              <th className="text-left font-medium">LPA</th>
              <th></th>
            </tr></thead>
            <tbody>
              {data.lp_holdings.map(lp => (
                <tr key={lp.id} className="border-t border-gray-100">
                  <td className="py-1.5 text-gray-900">{lp.fund_name}</td>
                  <td className="text-right">{fmtDollars(lp.commitment_amount)}</td>
                  <td className="text-right">{fmtDollars(lp.invested_amount)}</td>
                  <td className="text-right text-emerald-700">{fmtDollars(lp.returns)}</td>
                  <td><StatusPill status={lp.status} /></td>
                  <td>{lp.lpa_signed ? <span className="text-emerald-700 inline-flex items-center gap-1"><CheckCircle2 size={11} /> signed</span> : <span className="text-amber-700">pending</span>}</td>
                  <td className="text-right">
                    <div className="flex gap-2 justify-end">
                      <button onClick={() => setShowLpa(lp.fund_id)} className="text-violet-600 hover:underline">view LPA</button>
                      {!lp.lpa_signed && <button onClick={() => sign(lp.id)} className="text-emerald-600 hover:underline">sign</button>}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-white border border-gray-200 rounded-xl p-5">
          <div className="text-sm font-semibold text-gray-900 mb-3">Performance (TVPI / DPI)</div>
          {perfChart.length === 0
            ? <div className="text-xs text-gray-400 text-center py-6">No data yet.</div>
            : (
              <ResponsiveContainer width="100%" height={220}>
                <BarChart data={perfChart}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#eee" />
                  <XAxis dataKey="name" tick={{ fontSize: 10 }} />
                  <YAxis tick={{ fontSize: 10 }} />
                  <Tooltip />
                  <Bar dataKey="TVPI" fill="#7c3aed" />
                  <Bar dataKey="DPI" fill="#10b981" />
                </BarChart>
              </ResponsiveContainer>
            )}
        </div>
        <div className="bg-white border border-gray-200 rounded-xl p-5">
          <div className="text-sm font-semibold text-gray-900 mb-3">Distributions over time</div>
          {!data?.distributions?.length
            ? <div className="text-xs text-gray-400 text-center py-6">None yet.</div>
            : (
              <ResponsiveContainer width="100%" height={220}>
                <LineChart data={(data.distributions || []).slice().reverse().map(d => ({
                  date: (d.distributed_at || d.created_at)?.slice(0, 10),
                  amount: Number(d.amount_cents || 0) / 100,
                }))}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#eee" />
                  <XAxis dataKey="date" tick={{ fontSize: 10 }} />
                  <YAxis tick={{ fontSize: 10 }} />
                  <Tooltip />
                  <Line type="monotone" dataKey="amount" stroke="#7c3aed" />
                </LineChart>
              </ResponsiveContainer>
            )}
        </div>
      </div>

      <div className="bg-white border border-gray-200 rounded-xl p-5">
        <div className="text-sm font-semibold text-gray-900 mb-3">Capital calls</div>
        {!data?.capital_calls?.length ? <div className="text-xs text-gray-400 text-center py-4">No calls yet.</div> : (
          <table className="w-full text-xs">
            <thead className="text-gray-500"><tr>
              <th className="text-left py-1 font-medium">Date</th>
              <th className="text-right font-medium">Amount</th>
              <th className="text-left font-medium">Status</th>
            </tr></thead>
            <tbody>
              {data.capital_calls.map(cc => (
                <tr key={cc.id} className="border-t border-gray-100">
                  <td className="py-1 text-gray-500">{cc.created_at?.slice(0, 10)}</td>
                  <td className="text-right">{fmtDollars(cc.amount)}</td>
                  <td><StatusPill status={cc.status} /></td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {showLpa && <LPADrawer fundId={showLpa} onClose={() => setShowLpa(null)} />}
    </div>
  );
}

function Card({ icon: Icon, label, value, sub, accent }) {
  return (
    <div className="bg-white border border-gray-200 rounded-xl p-4">
      <div className="flex items-center justify-between mb-2">
        <span className="text-xs text-gray-500 uppercase tracking-wider font-medium">{label}</span>
        {Icon && <Icon size={14} className={`text-${accent}-600`} />}
      </div>
      <div className="text-2xl font-bold text-gray-900">{value}</div>
      {sub && <div className="text-[11px] text-gray-500 mt-1">{sub}</div>}
    </div>
  );
}

export default function FundsPage({ currentUser }) {
  const isAdmin = currentUser?.role === 'admin';
  const [tab, setTab] = useState(isAdmin ? 'admin' : 'lp');

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
          <Banknote size={22} className="text-violet-600" /> VC Funds
        </h1>
        <p className="text-sm text-gray-600 mt-1">Fund operations, LPA management, capital calls and returns distribution.</p>
      </div>

      {isAdmin && (
        <div className="border-b border-gray-200 flex gap-1">
          {[
            { id: 'admin', label: 'Fund Operations' },
            { id: 'lp', label: 'LP Portal (preview)' },
          ].map(t => (
            <button key={t.id} onClick={() => setTab(t.id)}
              className={`px-4 py-2 text-sm font-medium border-b-2 -mb-px ${
                tab === t.id ? 'border-violet-600 text-violet-700' : 'border-transparent text-gray-500 hover:text-gray-800'
              }`}>{t.label}</button>
          ))}
        </div>
      )}

      {tab === 'admin' && isAdmin ? <AdminFundsView /> : <LPPortalView />}
    </div>
  );
}
