import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Check, Rocket } from 'lucide-react';
import PublicNav from '../components/PublicNav';
import PublicFooter from '../components/PublicFooter';

const APPLY_HREF = '/register?lane=founder&product=spinout-lab';
// No public /contact route yet — keep the secondary CTA on a guaranteed
// mailto so cold traffic never lands on a dead page. Swap to /contact
// once the route ships.
const CONTACT_HREF = 'mailto:hello@axal.vc?subject=Spin-Out%20Lab';

// Stable feature route map used across the playbook unlocks. Every name
// here resolves to a real route in frontend/src/App.jsx — verified
// against the source of truth at edit time.
const FEATURE_LINK = {
  Projects: '/projects',
  'Customer Discovery': '/customer-discovery',
  'Market Intelligence': '/market-intel',
  Roadmap: '/build/roadmap',
  'Pitch Deck Builder': '/build/deck',
  'Brand Builder': '/build/brand',
  'Diligence & Scoring Engine': '/scoring',
  Mentors: '/mentors',
  'Office Hours': '/office-hours',
  'Co-founder Match': '/cofounder',
  Incorporate: '/incorporate',
  'Cap Table': '/build/captable',
  'Section 83(b)': '/incorporate/83b',
  'Cofounder Agreement': '/incorporate/cofounder-agreement',
  Capital: '/capital',
  Compliance: '/compliance',
  KYC: '/kyc',
};

function FeatureLink({ name }) {
  const href = FEATURE_LINK[name];
  if (!href) return <span className="font-medium text-gray-900">{name}</span>;
  return (
    <Link to={href} className="font-medium text-violet-700 hover:text-violet-900 underline-offset-2 hover:underline">
      {name}
    </Link>
  );
}

const PLAYBOOK = [
  {
    n: 1,
    title: 'Idea & Customer',
    youDo:
      'Define the problem, ICP, market sizing seed, talk to ≥5 customers, log every interview.',
    unlocks: ['Startups', 'Customer Discovery', 'Market Intelligence'],
    unlocksTail: ' (read-only), Personal Advisor (spinout persona, week 1 question bank).',
    leaveWith: '1 Startup record, ≥5 logged interviews, sized TAM/SAM with citations.',
  },
  {
    n: 2,
    title: 'Solution & Roadmap',
    youDo: 'Scope the MVP, set 90-day OKRs, draft brand v1, draft pitch deck v1.',
    unlocks: ['Roadmap', 'Brand Builder', 'Pitch Deck Builder'],
    unlocksTail: ', Studio Ops cadence.',
    leaveWith: '3+ OKRs, brand basics, deck v1.',
  },
  {
    n: 3,
    title: 'Validate & Team',
    youDo:
      'Run your first venture-readiness score, match with mentors, decide co-founder track, pressure-test scoring weak points.',
    unlocks: ['Diligence & Scoring Engine', 'Mentors', 'Office Hours', 'Co-founder Match'],
    unlocksTail: ', MI investor signals.',
    leaveWith:
      'A score with evidence-confidence %, a mentor cadence, a co-founder lead or a clear "going solo" plan.',
  },
  {
    n: 4,
    title: 'Incorporate & Capital',
    youDo:
      'Incorporate the entity, issue founder stock with vesting, file 83(b), sign cofounder agreement, lock the fundraise ask.',
    unlocks: ['Incorporate', 'Cap Table', 'Section 83(b)', 'Cofounder Agreement', 'Capital', 'Compliance', 'KYC'],
    unlocksTail:
      ' (KYC is investor-side — your introductions complete it before any wire). Plus LP / partner introductions on Axal VC\u2019s network.',
    leaveWith:
      'Incorporated entity, signed cap table with vesting, 83(b) filed in window, fundraise plan + ask, three warm investor introductions.',
  },
];

const WHAT_YOU_GET = [
  {
    title: 'Personal Advisor on every page',
    body:
      'Workers AI · Llama 3.3 70B FP8 via Axal VC\u2019s dedicated AI Gateway. Walks you through every screen — never a blank one.',
  },
  {
    title: 'Founder → Investor introductions',
    body:
      'Gated by a three-way NDA (Founder + Investor + Axal VC). Three warm intros minimum in Week 4 for qualified founders.',
  },
  {
    title: 'Mentor track',
    body:
      'Operators in your sector matched by expertise, availability, language, time zone, and rating.',
  },
  {
    title: 'Services-for-equity / services-for-fee partners',
    body:
      'Legal, design, recruiting, technical DD — pre-vetted, Axal VC network rates.',
  },
  {
    title: 'Market intelligence access',
    body:
      'Sector heat, investor signals, sentiment, TALC positioning, demand & supply atlas, capital velocity — refreshed nightly.',
  },
  {
    title: 'Document automation',
    body:
      'Incorporation packet, 83(b), cofounder agreement, SAFE template, NDAs. Generated by the platform, e-signed in-product.',
  },
  {
    title: 'Alumni community for life',
    body: 'Quarterly updates, alumni-only network, co-marketing slots.',
  },
  {
    title: 'Equity-for-platform option',
    body:
      'For accepted ventures only, under a separately negotiated partnership. Never automatic.',
  },
];

const STRONG_SIGNALS = [
  { t: 'Domain expertise', d: 'years in the target sector' },
  { t: 'Customer access', d: 'warm intros to ICP from day 1' },
  { t: 'Commitment level', d: 'full-time, not nights-and-weekends' },
  { t: 'Lived insight', d: 'a non-obvious view about what\u2019s broken' },
  { t: 'Coachability', d: 'you adjust when evidence contradicts you' },
  {
    t: 'Founder + market fit',
    d: 'right person for this specific problem, not just "any startup"',
  },
];

const FILTERS = [
  'Sector fit: AI · Blockchain · Quantum · Digital Infrastructure · Frontier Software',
  'Geography we can support',
  'Founder ≥ 18',
  'No sanctions / PEP / bad-actor disqualifications',
];

const REASONS_WE_SAY_NO = [
  'Too generic a thesis',
  'No customer access',
  'Part-time only with no plan to flip',
  'Conflicts of interest',
  'Sector mismatch',
];

const NETWORK = [
  'Operating partners — legal, GTM, design, recruiting, data, technical DD, finance.',
  'Investor signals from Axal VC\u2019s investor pipeline (anonymised until pairwise NDA signed).',
  'Mentor pool with expertise tags and availability calendars.',
  'Co-marketing partners across the network for distribution.',
  'Alumni founders who graduated previous cohorts.',
];

const MARKET_DATA = [
  { t: 'Sector compass', d: 'best sub-sectors given your profile' },
  {
    t: 'Investor signals',
    d: 'live aggregate of investor thesis + deployment patterns (k-anonymity ≥ 5)',
  },
  {
    t: 'TALC positioning',
    d:
      'where the market is on the technology-adoption lifecycle, where you think you are, and the gap',
  },
  { t: 'Demand & supply atlas', d: 'needs vs. offers across the network' },
  { t: 'Founder ↔ investor fit', d: 'embeddings-based thesis match' },
  { t: 'Capital velocity', d: 'deployment pace per stage per sector' },
];

const FAQ = [
  {
    q: 'I already have a co-founder.',
    a: 'Week 3 is still useful for scoring and investor exposure.',
  },
  {
    q: 'I missed a milestone.',
    a:
      'You stay at the current week until you complete it. Personal Advisor will list what\u2019s missing.',
  },
  {
    q: 'Do you take equity?',
    a: 'Only under a separately negotiated partnership / spin-out agreement. Never automatically.',
  },
  {
    q: 'Can I bring an existing startup?',
    a: 'Yes — fast-forward through weeks you\u2019ve already completed.',
  },
  {
    q: 'What jurisdictions?',
    a:
      'Delaware C-Corp default. LLC, UK Ltd, French SAS, German GmbH supported with partner counsel.',
  },
];

export default function SpinoutLabMarketingPage() {
  return (
    <div className="min-h-screen bg-white text-gray-900">
      <PublicNav />

      {/* HERO */}
      <section className="pt-32 pb-16 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 bg-violet-100 border border-violet-300 rounded-full text-xs text-violet-700 mb-6">
            <Rocket size={12} /> Spin-Out Lab · 30-day venture sprint
          </div>
          <h1
            style={{ fontFamily: "'Space Grotesk', sans-serif" }}
            className="text-4xl md:text-6xl font-bold leading-tight tracking-tight text-gray-900 mb-5"
          >
            Spin-Out Lab — <span className="text-violet-600">30 days</span> from idea to
            incorporated.
          </h1>
          <p className="text-lg md:text-xl text-gray-600 max-w-3xl mx-auto leading-relaxed">
            Four weeks. Four milestones. Personal Advisor at every step. Ends with a Delaware
            C-Corp (or your jurisdiction equivalent), a vesting cap table, 83(b) on file, a pitch
            deck, and a venture-readiness score.
          </p>
          <div className="mt-8 flex flex-col sm:flex-row gap-3 items-center justify-center">
            <Link
              to={APPLY_HREF}
              className="inline-flex items-center gap-2 bg-violet-600 hover:bg-violet-700 transition-colors px-7 py-3.5 rounded-xl text-sm font-medium text-white shadow-lg shadow-violet-600/30"
            >
              Start your 30-day Lab <ArrowRight size={16} />
            </Link>
            <a
              href={CONTACT_HREF}
              className="inline-flex items-center gap-2 border border-gray-300 hover:border-gray-400 transition-colors px-7 py-3.5 rounded-xl text-sm font-medium text-gray-800"
            >
              Talk to us first
            </a>
          </div>
        </div>
      </section>

      {/* PLAYBOOK */}
      <section id="playbook" className="py-20 px-6 bg-gray-50 scroll-mt-24">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-3 text-gray-900">
              The 4-week playbook.
            </h2>
            <p className="text-gray-600 max-w-xl mx-auto">
              Same engine as the rest of the platform — compressed into 30 days.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {PLAYBOOK.map((w) => (
              <div
                key={w.n}
                id={`week${w.n}`}
                className="scroll-mt-24 bg-white border border-gray-200 rounded-2xl p-6 hover:border-violet-300 hover:shadow-lg transition-all"
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-9 h-9 rounded-full bg-violet-600 text-white text-sm font-bold flex items-center justify-center">
                    {w.n}
                  </div>
                  <h3 className="text-lg font-semibold text-gray-900">
                    Week {w.n} — {w.title}
                  </h3>
                </div>
                <dl className="space-y-3 text-sm leading-relaxed">
                  <div>
                    <dt className="text-xs uppercase tracking-wider text-violet-700 font-semibold mb-1">
                      What you do
                    </dt>
                    <dd className="text-gray-700">{w.youDo}</dd>
                  </div>
                  <div>
                    <dt className="text-xs uppercase tracking-wider text-violet-700 font-semibold mb-1">
                      What unlocks
                    </dt>
                    <dd className="text-gray-700">
                      {w.unlocks.map((name, i) => (
                        <React.Fragment key={name}>
                          <FeatureLink name={name} />
                          {i < w.unlocks.length - 1 ? ', ' : ''}
                        </React.Fragment>
                      ))}
                      {w.unlocksTail}
                    </dd>
                  </div>
                  <div>
                    <dt className="text-xs uppercase tracking-wider text-violet-700 font-semibold mb-1">
                      You leave with
                    </dt>
                    <dd className="text-gray-700">{w.leaveWith}</dd>
                  </div>
                </dl>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* WHAT YOU GET */}
      <section id="what-you-get" className="py-20 px-6 scroll-mt-24">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-3 text-center">
            What you get.
          </h2>
          <p className="text-gray-600 text-center max-w-xl mx-auto mb-12">
            Every Lab founder gets the full operating stack.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            {WHAT_YOU_GET.map((g) => (
              <div key={g.title} className="bg-white border border-gray-200 rounded-2xl p-5">
                <div className="flex items-start gap-2 mb-2">
                  <Check size={14} className="text-violet-600 mt-1 shrink-0" />
                  <h3 className="text-sm font-semibold text-gray-900">{g.title}</h3>
                </div>
                <p className="text-xs text-gray-600 leading-relaxed pl-6">{g.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* WHAT WE LOOK FOR */}
      <section id="what-we-look-for" className="py-20 px-6 bg-gray-50 scroll-mt-24">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-3 text-center">
            What we look for.
          </h2>
          <p className="text-gray-600 text-center max-w-xl mx-auto mb-12">
            Honest. Not every applicant is a fit.
          </p>
          <div className="grid md:grid-cols-2 gap-6">
            <div className="bg-white border border-gray-200 rounded-2xl p-6">
              <h3 className="text-sm uppercase tracking-wider text-violet-700 font-semibold mb-4">
                Strong signals
              </h3>
              <ul className="space-y-3">
                {STRONG_SIGNALS.map((s) => (
                  <li key={s.t} className="flex items-start gap-2 text-sm text-gray-700">
                    <Check size={14} className="text-violet-600 mt-1 shrink-0" />
                    <div>
                      <span className="font-semibold text-gray-900">{s.t}</span> — {s.d}
                    </div>
                  </li>
                ))}
              </ul>
            </div>
            <div className="bg-white border border-gray-200 rounded-2xl p-6">
              <h3 className="text-sm uppercase tracking-wider text-violet-700 font-semibold mb-4">
                Filters
              </h3>
              <ul className="space-y-3 mb-6">
                {FILTERS.map((f) => (
                  <li key={f} className="flex items-start gap-2 text-sm text-gray-700">
                    <Check size={14} className="text-violet-600 mt-1 shrink-0" />
                    <span>{f}</span>
                  </li>
                ))}
              </ul>
              <h3 className="text-sm uppercase tracking-wider text-gray-500 font-semibold mb-3">
                Reasons we say no
              </h3>
              <p className="text-sm text-gray-600 leading-relaxed">
                {REASONS_WE_SAY_NO.join(' · ')}.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* NETWORK */}
      <section id="network" className="py-20 px-6 scroll-mt-24">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-3 text-center">
            Network.
          </h2>
          <p className="text-gray-600 text-center max-w-xl mx-auto mb-10">
            Inside the Lab you tap the full Axal VC network.
          </p>
          <div className="bg-white border border-gray-200 rounded-2xl p-6">
            <ul className="space-y-3">
              {NETWORK.map((n) => (
                <li key={n} className="flex items-start gap-2 text-sm text-gray-700 leading-relaxed">
                  <Check size={14} className="text-violet-600 mt-1 shrink-0" />
                  <span>{n}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      {/* MARKET DATA */}
      <section id="market-data" className="py-20 px-6 bg-gray-50 scroll-mt-24">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-3 text-center">
            Market data.
          </h2>
          <p className="text-gray-600 text-center max-w-xl mx-auto mb-12">
            Six dashboards every founder gets on day one.{' '}
            <Link to="/market-intel" className="text-violet-700 hover:text-violet-900 underline-offset-2 hover:underline">
              Preview Market Intelligence →
            </Link>
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {MARKET_DATA.map((m) => (
              <div key={m.t} className="bg-white border border-gray-200 rounded-2xl p-5">
                <h3 className="text-sm font-semibold text-gray-900 mb-1">{m.t}</h3>
                <p className="text-xs text-gray-600 leading-relaxed">{m.d}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* PRICING */}
      <section id="pricing" className="py-20 px-6 scroll-mt-24">
        <div className="max-w-3xl mx-auto bg-violet-50/40 border-2 border-violet-200 rounded-3xl p-8 md:p-12 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">Pricing.</h2>
          <p className="text-base text-gray-700 leading-relaxed">
            <span className="font-semibold text-gray-900">Free during the 30-day sprint.</span>{' '}
            After graduation: standard Founder tiers (Free / Growth / Studio). Services partners
            are separately priced.
          </p>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="py-20 px-6 bg-gray-50 scroll-mt-24">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-10 text-center">FAQ.</h2>
          <div className="space-y-3">
            {FAQ.map((f, i) => (
              <details
                key={i}
                className="group bg-white border border-gray-200 rounded-xl p-5 open:border-violet-300 open:bg-violet-50/40"
              >
                <summary className="cursor-pointer text-sm font-semibold text-gray-900 list-none flex items-center justify-between">
                  {f.q}
                  <span className="text-violet-600 text-xs group-open:rotate-180 transition-transform">
                    ▾
                  </span>
                </summary>
                <p className="text-sm text-gray-700 leading-relaxed mt-3">{f.a}</p>
              </details>
            ))}
          </div>
          <div className="mt-12 flex flex-col sm:flex-row gap-3 items-center justify-center">
            <Link
              to={APPLY_HREF}
              className="inline-flex items-center gap-2 bg-violet-600 hover:bg-violet-700 transition-colors px-7 py-3.5 rounded-xl text-sm font-medium text-white shadow-lg shadow-violet-600/30"
            >
              Start your 30-day Lab <ArrowRight size={16} />
            </Link>
            <a
              href={CONTACT_HREF}
              className="inline-flex items-center gap-2 border border-gray-300 hover:border-gray-400 transition-colors px-7 py-3.5 rounded-xl text-sm font-medium text-gray-800"
            >
              Talk to us first
            </a>
          </div>
        </div>
      </section>

      <PublicFooter />
    </div>
  );
}
