#!/usr/bin/env node
/**
 * Bake per-route Open Graph metadata into the built SPA output.
 *
 * THE PROBLEM THIS SOLVES
 * -----------------------
 * axal.vc is a client-rendered Vite SPA. Cloudflare Workers Static Assets is
 * configured with `not_found_handling = "single-page-application"`, so *every*
 * route that has no file of its own is answered with the same `docs/index.html`
 * — one `<title>`, one `og:title`, one `og:image`, for the whole site.
 *
 * `usePageMeta()` in `frontend/src/lib/seo.js` fixes that in the browser, but
 * link-preview crawlers do not run JavaScript. WhatsApp, iMessage, Facebook,
 * LinkedIn and Slack read the raw HTTP response and nothing else, so they only
 * ever saw the shell's generic tags — which is why every axal.vc link previewed
 * identically no matter which page was shared.
 *
 * THE FIX
 * -------
 * After `vite build`, write a real `docs/<route>/index.html` for each public
 * route, identical to the shell except for its `<head>` metadata. Static Assets
 * resolves `/spinout-lab` to `docs/spinout-lab/index.html` (directory-index
 * handling) *before* the SPA fallback runs, so a crawler gets correct tags in
 * the raw response with no JavaScript and no worker involvement.
 *
 * The SPA itself is unaffected: every emitted file is the same document with
 * the same script tags, so React boots and client-routes exactly as before.
 *
 * Usage:
 *   node scripts/prerender-og.mjs               # write into ./docs
 *   node scripts/prerender-og.mjs --out DIR     # write elsewhere
 *   node scripts/prerender-og.mjs --check       # verify, write nothing
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { OG_ROUTES, ogTagsFor } from '../frontend/src/lib/ogRegistry.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function arg(flag, fallback) {
  const i = process.argv.indexOf(flag);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const OUT_DIR = path.resolve(ROOT, arg('--out', 'docs'));
const CHECK = process.argv.includes('--check');

/** Tags this script owns. Any pre-existing copy is stripped before injecting. */
const MANAGED = [
  /<title>[\s\S]*?<\/title>\s*/gi,
  /<meta\s+name=["']description["'][^>]*>\s*/gi,
  /<meta\s+property=["']og:[^"']+["'][^>]*>\s*/gi,
  /<meta\s+name=["']og:[^"']+["'][^>]*>\s*/gi,
  /<meta\s+name=["']twitter:[^"']+["'][^>]*>\s*/gi,
  /<meta\s+property=["']twitter:[^"']+["'][^>]*>\s*/gi,
  /<link\s+rel=["']canonical["'][^>]*>\s*/gi,
];

function esc(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Build the metadata block for a route.
 *
 * `og:image` is emitted as an absolute https URL — several crawlers (WhatsApp
 * and LinkedIn among them) will not resolve a relative image path, which is a
 * common and silent way for previews to end up blank.
 */
function metaBlock(tags) {
  const lines = [
    `<title>${esc(tags.title)}</title>`,
    `<meta name="description" content="${esc(tags.description)}" />`,
    `<link rel="canonical" href="${esc(tags.url)}" />`,
    '',
    `<meta property="og:type" content="${esc(tags.type)}" />`,
    `<meta property="og:site_name" content="${esc(tags.siteName)}" />`,
    `<meta property="og:title" content="${esc(tags.title)}" />`,
    `<meta property="og:description" content="${esc(tags.description)}" />`,
    `<meta property="og:url" content="${esc(tags.url)}" />`,
    `<meta property="og:image" content="${esc(tags.image)}" />`,
    `<meta property="og:image:secure_url" content="${esc(tags.image)}" />`,
    `<meta property="og:image:type" content="image/png" />`,
    `<meta property="og:image:width" content="1200" />`,
    `<meta property="og:image:height" content="630" />`,
    `<meta property="og:image:alt" content="${esc(tags.imageAlt)}" />`,
    '',
    `<meta name="twitter:card" content="${esc(tags.card)}" />`,
    `<meta name="twitter:title" content="${esc(tags.title)}" />`,
    `<meta name="twitter:description" content="${esc(tags.description)}" />`,
    `<meta name="twitter:image" content="${esc(tags.image)}" />`,
    `<meta name="twitter:image:alt" content="${esc(tags.imageAlt)}" />`,
  ];
  // No trailing newline: the injector adds the single leading newline and the
  // strip regex removes exactly that one, which is what keeps re-runs stable.
  return `  <!-- BEGIN og:managed — generated by scripts/prerender-og.mjs. Edit
       frontend/src/lib/ogRegistry.js instead; changes here are overwritten. -->
${lines.map((l) => (l ? `  ${l}` : '')).join('\n')}
  <!-- END og:managed -->`;
}

/** Replace the shell's head metadata with this route's. */
function renderRoute(shell, pathname) {
  const tags = ogTagsFor(pathname);

  // Drop any previously-injected block first so re-running is idempotent. The
  // leading `\n?` pairs with the newline added at injection time — without it
  // each run leaves one more blank line behind and the output never converges.
  let html = shell.replace(
    /\n?[ \t]*<!-- BEGIN og:managed[\s\S]*?<!-- END og:managed -->/g,
    '',
  );
  for (const re of MANAGED) html = html.replace(re, '');

  const inject = metaBlock(tags);
  if (/<head[^>]*>/i.test(html)) {
    html = html.replace(/(<head[^>]*>)/i, `$1\n${inject}`);
  } else {
    // No <head> is not something we should paper over silently.
    throw new Error('Shell HTML has no <head> — cannot inject metadata.');
  }
  return { html, tags };
}

function outFileFor(pathname) {
  return pathname === '/'
    ? path.join(OUT_DIR, 'index.html')
    : path.join(OUT_DIR, pathname.replace(/^\//, ''), 'index.html');
}

function main() {
  const shellFile = path.join(OUT_DIR, 'index.html');
  if (!fs.existsSync(shellFile)) {
    console.error(
      `No built shell at ${path.relative(ROOT, shellFile)}.\n` +
        'Run the frontend build first (cd frontend && npm run build).',
    );
    process.exit(1);
  }

  // Read the shell once, before we start overwriting the root file.
  const shell = fs.readFileSync(shellFile, 'utf8');
  const problems = [];
  let written = 0;

  for (const route of OG_ROUTES) {
    const { html, tags } = renderRoute(shell, route.path);
    const outFile = outFileFor(route.path);

    if (CHECK) {
      if (!fs.existsSync(outFile)) {
        problems.push(`missing: ${path.relative(ROOT, outFile)}`);
      } else if (fs.readFileSync(outFile, 'utf8') !== html) {
        problems.push(`stale:   ${path.relative(ROOT, outFile)}`);
      }
      continue;
    }

    fs.mkdirSync(path.dirname(outFile), { recursive: true });
    fs.writeFileSync(outFile, html);
    written += 1;
    console.log(`  ${route.path.padEnd(24)} → ${path.relative(ROOT, outFile)}`);
    console.log(`  ${''.padEnd(24)}   ${tags.image}`);
  }

  if (CHECK) {
    if (problems.length) {
      console.error('Prerender check FAILED:');
      for (const p of problems) console.error(`  - ${p}`);
      console.error('\nRun: node scripts/prerender-og.mjs');
      process.exit(1);
    }
    console.log(`Prerender check passed — ${OG_ROUTES.length} routes up to date.`);
    return;
  }

  console.log(`\nPrerendered ${written} routes into ${path.relative(ROOT, OUT_DIR)}/`);
}

main();
